/*
 * Java bean class for entity table RM_BRANCH 
 * Created on 3 Oct 2013 ( Time 12:18:01 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.dao.impl;

import java.util.List;

import org.hibernate.criterion.Restrictions;
import org.springframework.stereotype.Repository;

import com.pruvn.rms.dao.BranchDao;
import com.pruvn.rms.domain.Branch;
import com.pruvn.rms.utils.Constant.ParameterApplication;


/**
 * Data Access Object implementation for table "RM_BRANCH"
 * 
 * @author Telosys Tools Generator
 *
 */
public class BranchHibernateDao extends AbstractHibernateDAO<Branch, Integer> implements BranchDao {

    
	/**
	 * Find RmBranch by code
	 */
	public List<Branch> findBycode(String code) {
		return findByCriteria(Restrictions.eq("code", code));
	}
	
	/**
	 * Find RmBranch by name
	 */
	public List<Branch> findByname(String name) {
		return findByCriteria(Restrictions.eq("name", name));
	}	
	
	/**
	 * Find RmBranch by name
	 */
	public List<Branch> findAllActive() {
		return findByCriteria(Restrictions.eq("isActived", ParameterApplication.ACTIVE.getStatus()));
	}
	
}