/*
 * Java bean class for entity table RM_UploadData 
 * Created on 3 Oct 2013 ( Time 12:18:01 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.dao.impl;

import com.pruvn.rms.dao.CSUploadDataDao;
import com.pruvn.rms.domain.CSUploadData;


/**
 * Data Access Object implementation for table "RM_UploadData"
 * 
 * @author Telosys Tools Generator
 *
 */
public class CSUploadDataHibernateDao extends AbstractHibernateDAO<CSUploadData, Integer> implements CSUploadDataDao {

	
}