/*
 * Java bean class for entity table RM_HomeLoan 
 * Created on 3 Oct 2013 ( Time 12:18:01 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.dao.impl;

import java.util.List;

import org.hibernate.criterion.MatchMode;
import org.hibernate.criterion.Restrictions;

import com.pruvn.rms.dao.HomeLoanDao;
import com.pruvn.rms.domain.HomeLoan;
import com.pruvn.rms.domain.MRC;


/**
 * Data Access Object implementation for table "RM_HOME_LOAN"
 * 
 * @author Telosys Tools Generator
 *
 */
public class HomeLoanHibernateDao extends AbstractHibernateDAO<HomeLoan, Integer> implements HomeLoanDao {

	public HomeLoan findByLoanNo(String loanNo) {
		List<HomeLoan> list =  findByCriteria(Restrictions.eq("loanNo", loanNo));		
		if(list != null && list.size() > 0){
			return list.get(0);
		}
		return null;
	}
	
	public List<HomeLoan> searchByLoanNo(String loanNo) {
		List<HomeLoan> list =  findByCriteria(Restrictions.like("loanNo", loanNo,MatchMode.ANYWHERE));		
		return list;
	}
	
	
	
}