/*
 * Java bean class for entity table RM_Insurance 
 * Created on 3 Oct 2013 ( Time 12:18:01 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.dao.impl;

import java.util.List;

import org.hibernate.criterion.MatchMode;
import org.hibernate.criterion.Restrictions;

import com.pruvn.rms.dao.InsuranceDao;
import com.pruvn.rms.domain.Insurance;


/**
 * Data Access Object implementation for table "RM_Insurance"
 * 
 * @author Telosys Tools Generator
 *
 */
public class InsuranceHibernateDao extends AbstractHibernateDAO<Insurance, Integer> implements InsuranceDao {

	
	public Insurance findByLoanNo(String loanNo) {
		List<Insurance> list =  findByCriteria(Restrictions.eq("loanNo", loanNo));		
		if(list != null && list.size() > 0){
			return list.get(0);
		}
		return null;
	}
	
	public List<Insurance> searchByLoanNo(String loanNo) {
		List<Insurance> list =  findByCriteria(Restrictions.like("loanNo", loanNo,MatchMode.ANYWHERE));		
		return list;
	}
}