/*
 * Java bean class for entity table RM_PRODUCT 
 * Created on 3 Oct 2013 ( Time 12:18:07 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.dao.impl;

import java.util.List;

import org.hibernate.criterion.Restrictions;

import com.pruvn.rms.dao.ProductDao;
import com.pruvn.rms.domain.Product;

/**
 * Data Access Object implementation for table "RM_PRODUCT"
 * 
 * @author Telosys Tools Generator
 *
 */
public class ProductHibernateDao extends AbstractHibernateDAO<Product,Integer>  implements ProductDao
{
    
	/**
	 * Find RmProduct by code
	 */
	public List<Product> findByCode(String code) {
		return findByCriteria(Restrictions.eq("code", code));
	}
	
	/**
	 * Find RmProduct by name
	 */
	public List<Product> findByName(String name) {
		return findByCriteria(Restrictions.eq("name", name));
	}
	
	/**
	 * Find RmProduct by description
	 */
	public List<Product> findByDescription(String description) {
		return findByCriteria(Restrictions.eq("description", description));
	}
	
	/**
	 * Find RmProduct by branchId
	 */
	public List<Product> findByBranchId(Integer branchId) {
		return findByCriteria(Restrictions.and(Restrictions.eq("branchId", branchId), Restrictions.eq("isActived", 1)));
	}
	
}