/*
 * Java bean class for entity table RM_TB6 
 * Created on 3 Oct 2013 ( Time 12:18:01 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.dao.impl;

import java.sql.SQLException;
import java.util.List;

import org.hibernate.HibernateException;
import org.hibernate.SQLQuery;
import org.hibernate.Session;
import org.hibernate.criterion.MatchMode;
import org.hibernate.criterion.Restrictions;
import org.springframework.orm.hibernate3.HibernateCallback;

import com.pruvn.rms.dao.TB6Dao;
import com.pruvn.rms.domain.RecordFL2;
import com.pruvn.rms.domain.TB6;
import com.pruvn.rms.model.FilterMRCForm;
import com.pruvn.rms.utils.CommonUtils;
import com.pruvn.rms.utils.SqlConstant;
import com.pruvn.rms.utils.Constant.TB6_STAGE;


/**
 * Data Access Object implementation for table "RM_TB6"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TB6HibernateDao extends AbstractHibernateDAO<TB6, Integer> implements TB6Dao {

	
	public TB6 findByLoanNo(String loanNo) {
		List<TB6> list =  findByCriteria(Restrictions.eq("loanNo", loanNo));		
		if(list != null && list.size() > 0){
			return list.get(0);
		}
		return null;
	}
	
	public List<TB6> searchByLoanNo(String loanNo) {
		List<TB6> list =  findByCriteria(Restrictions.like("loanNo", loanNo,MatchMode.ANYWHERE));		
		return list;
	}
	
	@SuppressWarnings({ "unchecked", "rawtypes" })
	public List<TB6> getTB6List(final String stage,
			final FilterMRCForm filterMRCForm) {
		return (List<TB6>) getHibernateTemplate().execute(new HibernateCallback() {
            public Object doInHibernate(final Session session) throws HibernateException, SQLException {
            	StringBuffer sqlQuery  = new StringBuffer(SqlConstant.SELECT_TB6_LIST_ACL);
            	if(!CommonUtils.isNullOrEmpty(stage)) {  
            		sqlQuery.append(" AND STAGE= '" + stage + "'");
            	}
            	if(!CommonUtils.isNullOrEmpty(filterMRCForm.getLoanNo())) {            		
            		sqlQuery.append(" AND LOAN_NO like '%" + filterMRCForm.getLoanNo() + "%'");
            	}
            	
             	if(!CommonUtils.isNullOrEmpty(filterMRCForm.getDateSend())) {            		
            		sqlQuery.append(" AND SEND_DATE = to_date('" + filterMRCForm.getDateSend() + "','dd/MM/rrrr')");
            	}
            	
        		SQLQuery query = session.createSQLQuery(
        				sqlQuery.toString());
        		//query.setParameter("username", username);
        		//query.setParameter("stage", stage);
        		query.addEntity(TB6.class);
        		List<TB6> result = query.list();
        		return result;
            }
        });
		
		
		
		
		
		
	}
	
	
}