/*
 * Java bean class for entity table RM_UploadData 
 * Created on 3 Oct 2013 ( Time 12:18:01 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.dao.impl;

import java.sql.SQLException;
import java.util.List;

import org.hibernate.HibernateException;
import org.hibernate.SQLQuery;
import org.hibernate.Session;
import org.hibernate.criterion.Restrictions;
import org.springframework.orm.hibernate3.HibernateCallback;

import com.pruvn.rms.dao.UploadDataDao;
import com.pruvn.rms.domain.Record;
import com.pruvn.rms.domain.UploadData;
import com.pruvn.rms.utils.SqlConstant;
import com.pruvn.rms.utils.Constant.ParameterApplication;


/**
 * Data Access Object implementation for table "RM_UploadData"
 * 
 * @author Telosys Tools Generator
 *
 */
public class UploadDataHibernateDao extends AbstractHibernateDAO<UploadData, Integer> implements UploadDataDao {

	
}