/*
 * Java bean class for entity table user_level_m 
 * Created on 17 May 2013 ( Time 17:03:25 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.dao.impl;

import java.util.List;

import org.hibernate.criterion.Restrictions;

import com.pruvn.rms.dao.UserLevelMDao;
import com.pruvn.rms.domain.UserLevelM;


/**
 * Data Access Object implementation for table "user_level_m"
 * 
 * @author Telosys Tools Generator
 *
 */
public class UserLevelMHibernateDao extends AbstractHibernateDAO<UserLevelM,Integer>  implements UserLevelMDao
{
    
	/**
	 * Find UserLevelM by levelcode
	 */
	public List<UserLevelM> findBylevelcode(String levelcode) {
		return findByCriteria(Restrictions.eq("levelcode", levelcode));
	}
	
	/**
	 * Find UserLevelM by levelname
	 */
	public List<UserLevelM> findBylevelname(String levelname) {
		return findByCriteria(Restrictions.eq("levelname", levelname));
	}
	
	/**
	 * Find UserLevelM by leveldesc
	 */
	public List<UserLevelM> findByleveldesc(String leveldesc) {
		return findByCriteria(Restrictions.eq("leveldesc", leveldesc));
	}
	
}