/*
 * Java bean class for entity table RM_PRODUCT 
 * Created on 3 Oct 2013 ( Time 12:18:07 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.model;


import java.util.List;

import com.pruvn.rms.domain.Branch;

/**
 * Model/Form for table "RM_PRODUCT"
 * 
 * @author Telosys Tools Generator
 *
 */
public class ProductForm
{

    private Integer id           ; // Primary Key

    private String     code         ;
    private String     name         ;
    private String     description  ;
    private Integer branchId     ;
    private Boolean isActived     ;
    
    private List<Branch> branchs     ;

    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "ID" ( type "NUMBER", NotNull : true ) 
     * @param id
     */
	public void setId( Integer id )
    {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "ID" ( type "NUMBER", NotNull : true ) 
     * @return the field value
     */
	public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : CODE ( VARCHAR2 ) 
    /**
     * Set the "code" field value
     * This field is mapped on the database column "CODE" ( type "VARCHAR2", NotNull : false ) 
     * @param code
     */
    public void setCode( String code )
    {
        this.code = code;
    }
    /**
     * Get the "code" field value
     * This field is mapped on the database column "CODE" ( type "VARCHAR2", NotNull : false ) 
     * @return the field value
     */
    public String getCode()
    {
        return this.code;
    }

    //--- DATABASE MAPPING : NAME ( VARCHAR2 ) 
    /**
     * Set the "name" field value
     * This field is mapped on the database column "NAME" ( type "VARCHAR2", NotNull : false ) 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    }
    /**
     * Get the "name" field value
     * This field is mapped on the database column "NAME" ( type "VARCHAR2", NotNull : false ) 
     * @return the field value
     */
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : DESCRIPTION ( VARCHAR2 ) 
    /**
     * Set the "description" field value
     * This field is mapped on the database column "DESCRIPTION" ( type "VARCHAR2", NotNull : false ) 
     * @param description
     */
    public void setDescription( String description )
    {
        this.description = description;
    }
    /**
     * Get the "description" field value
     * This field is mapped on the database column "DESCRIPTION" ( type "VARCHAR2", NotNull : false ) 
     * @return the field value
     */
    public String getDescription()
    {
        return this.description;
    }

    //--- DATABASE MAPPING : BRANCH_ID ( NUMBER ) 
    /**
     * Set the "branchId" field value
     * This field is mapped on the database column "BRANCH_ID" ( type "NUMBER", NotNull : false ) 
     * @param branchId
     */
    public void setBranchId( Integer branchId )
    {
        this.branchId = branchId;
    }
    /**
     * Get the "branchId" field value
     * This field is mapped on the database column "BRANCH_ID" ( type "NUMBER", NotNull : false ) 
     * @return the field value
     */
    public Integer getBranchId()
    {
        return this.branchId;
    }
	public Boolean getIsActived() {
		return isActived;
	}
	public void setIsActived(Boolean isActived) {
		this.isActived = isActived;
	}
	public List<Branch> getBranchs() {
		return branchs;
	}
	public void setBranchs(List<Branch> branchs) {
		this.branchs = branchs;
	}

}
