/*
 * Java bean class for entity table RM_SCREEN 
 * Created on 3 Oct 2013 ( Time 12:18:01 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.model;



/**
 * Model/Form for table "RM_SCREEN"
 * 
 * @author Telosys Tools Generator
 *
 */
public class ScreenForm
{

    private Integer    id           ; // Primary Key

    private String     stage         ;
    private String     name         ;
    private String     viewName         ;
    private String     priority1         ;
    private String     priority2         ;
    private Boolean     isActived         ;
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getStage() {
		return stage;
	}
	public void setStage(String stage) {
		this.stage = stage;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getViewName() {
		return viewName;
	}
	public void setViewName(String viewName) {
		this.viewName = viewName;
	}
	public String getPriority1() {
		return priority1;
	}
	public void setPriority1(String priority1) {
		this.priority1 = priority1;
	}
	public String getPriority2() {
		return priority2;
	}
	public void setPriority2(String priority2) {
		this.priority2 = priority2;
	}
	public Boolean getIsActived() {
		return isActived;
	}
	public void setIsActived(Boolean isActived) {
		this.isActived = isActived;
	}

    
   
}
