/*
 * Java bean class for entity table user_level_a 
 * Created on 17 May 2013 ( Time 17:03:25 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.model;



/**
 * Model/Form for table "user_level_a"
 * 
 * @author Telosys Tools Generator
 *
 */
public class UserLevelAForm
{

    private int        userlevelid  ; // Primary Key

    private Integer    userid       ;
    private Integer    levelid      ;

    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "userlevelid" field value
     * This field is mapped on the database column "userlevelid" ( type "INT", NotNull : true ) 
     * @param userlevelid
     */
	public void setUserlevelid( int userlevelid )
    {
        this.userlevelid = userlevelid ;
    }
    /**
     * Get the "userlevelid" field value
     * This field is mapped on the database column "userlevelid" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public int getUserlevelid()
    {
        return this.userlevelid;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : userid ( INT ) 
    /**
     * Set the "userid" field value
     * This field is mapped on the database column "userid" ( type "INT", NotNull : false ) 
     * @param userid
     */
    public void setUserid( Integer userid )
    {
        this.userid = userid;
    }
    /**
     * Get the "userid" field value
     * This field is mapped on the database column "userid" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getUserid()
    {
        return this.userid;
    }

    //--- DATABASE MAPPING : levelid ( INT ) 
    /**
     * Set the "levelid" field value
     * This field is mapped on the database column "levelid" ( type "INT", NotNull : false ) 
     * @param levelid
     */
    public void setLevelid( Integer levelid )
    {
        this.levelid = levelid;
    }
    /**
     * Get the "levelid" field value
     * This field is mapped on the database column "levelid" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getLevelid()
    {
        return this.levelid;
    }

}
