/*
 * Java bean class for entity table user_level_a 
 * Created on 17 May 2013 ( Time 17:03:25 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.dto;

import java.io.Serializable;

import com.pruvn.rms.dao.UserMDAO;
import com.pruvn.rms.domain.UserLevelM;
import com.pruvn.rms.domain.UserM;


/**
 * Data Transfer Object for table "user_level_a"
 * 
 * @author Telosys Tools Generator
 *
 */
public class UserLevelADto implements Serializable
{
    private static final long serialVersionUID = 1L;

    private int        userlevelid  ; // Primary Key

    private UserM    user       ;
    private UserLevelM    level      ;

    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "userlevelid" field value
     * This field is mapped on the database column "userlevelid" ( type "INT", NotNull : true ) 
     * @param userlevelid
     */
	public void setUserlevelid( int userlevelid )
    {
        this.userlevelid = userlevelid ;
    }
    /**
     * Get the "userlevelid" field value
     * This field is mapped on the database column "userlevelid" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public int getUserlevelid()
    {
        return this.userlevelid;
    }
	/**
	 * @return the user
	 */
	public UserM getUser() {
		return user;
	}
	/**
	 * @param user the user to set
	 */
	public void setUser(UserM user) {
		this.user = user;
	}
	/**
	 * @return the level
	 */
	public UserLevelM getLevel() {
		return level;
	}
	/**
	 * @param level the level to set
	 */
	public void setLevel(UserLevelM level) {
		this.level = level;
	}

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : userid ( INT ) 
    

}
