/*
 * Java bean class for entity table auditlog 
 * Created on 5 Mar 2014 ( Time 16:51:13 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.tools.printserver;

import java.util.Date;
import java.util.List;

import com.pruvn.tools.printserver.pojo.Auditlog;

/**
 * Data Access Object interface for table "auditlog"
 * 
 * @author Telosys Tools Generator
 *
 */

public interface AuditlogDAO extends GenericDAO<Auditlog,Integer> 
{
    

	/**
	 * Find Auditlog by username
	 */
	public List<Auditlog> findByaction(String action);
	/**
	 * Find Auditlog by username
	 */
	public List<Auditlog> findBydetail(String detail);
	/**
	 * Find Auditlog by username
	 */
	public List<Auditlog> findBycreatedDate(Date createdDate);
	/**
	 * Find Auditlog by username
	 */
	public List<Auditlog> findByentityId(Integer entityId);
	/**
	 * Find Auditlog by username
	 */
	public List<Auditlog> findByentityName(String entityName);
	/**
	 * Find Auditlog by username
	 */
	public List<Auditlog> findBydetailOut(String detailOut);
}


