/*
 * Java bean class for entity table RM_BRANCH 
 * Created on 3 Oct 2013 ( Time 12:18:01 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.service;

import java.util.List;

import com.pruvn.rms.domain.Branch;
import com.pruvn.rms.service.abstracts.GenericService;


/**
 * Service interface for table "RM_BRANCH"
 * 
 * @author Telosys Tools Generator
 *
 */
public interface BranchService extends GenericService<Branch, Integer>
{
    

	/**
	 * Find RmBranch by code
	 */
	public Branch findBycode(String code);
	/**
	 * Find RmBranch by name
	 */
	public List<Branch> findByname(String name);
}