/*
 * Java bean class for entity table RM_PRODUCT 
 * Created on 3 Oct 2013 ( Time 12:18:07 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.service;

import java.util.List;

import com.pruvn.rms.domain.Branch;
import com.pruvn.rms.domain.Product;
import com.pruvn.rms.service.abstracts.GenericService;

/**
 * Service interface for table "RM_PRODUCT"
 * 
 * @author Telosys Tools Generator
 *
 */
public interface ProductService extends GenericService<Product, Integer>
{
    

	/**
	 * Find RmProduct by username
	 */
	public Product findByCode(String code);
	/**
	 * Find RmProduct by username
	 */
	public List<Product> findByName(String name);
	/**
	 * Find RmProduct by username
	 */
	public List<Product> findByDescription(String description);
	/**
	 * Find RmProduct by username
	 */
	public List<Product> findByBranchId(Integer branchId);
	
	public List<Branch> getAllActiveBranchs();
}