/*
 * Java bean class for entity table user_level_m 
 * Created on 17 May 2013 ( Time 17:03:25 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.service;

import java.util.List;

import com.pruvn.rms.domain.UserLevelM;
import com.pruvn.rms.dto.UserLevelMDto;
import com.pruvn.rms.service.abstracts.GenericService;


/**
 * Service interface for table "user_level_m"
 * 
 * @author Telosys Tools Generator
 *
 */
public interface UserLevelMService extends GenericService<UserLevelM, Integer> 
{
    

	/**
	 * Find UserLevelM by username
	 */
	public List<UserLevelMDto> findBylevelcode(String levelcode);
	/**
	 * Find UserLevelM by username
	 */
	public List<UserLevelMDto> findBylevelname(String levelname);
	/**
	 * Find UserLevelM by username
	 */
	public List<UserLevelMDto> findByleveldesc(String leveldesc);
	UserLevelM findBylevelcode1(String levelcode);
}