/*
 * Java bean class for entity table auditlog 
 * Created on 5 Mar 2014 ( Time 16:51:13 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.tools.printserver.hibernate;

import java.util.Date;
import java.util.List;

import org.hibernate.criterion.Restrictions;
import org.springframework.stereotype.Repository;

import com.pruvn.tools.printserver.AuditlogDAO;
import com.pruvn.tools.printserver.pojo.Auditlog;

/**
 * Data Access Object implementation for table "auditlog"
 * 
 * @author Telosys Tools Generator
 *
 */

public class AuditlogHibernateDAO extends AbstractHibernateDAO<Auditlog,Integer>  implements AuditlogDAO
{
    
	/**
	 * Find Auditlog by action
	 */
	public List<Auditlog> findByaction(String action) {
		return findByCriteria(Restrictions.eq("action", action));
	}
	
	/**
	 * Find Auditlog by detail
	 */
	public List<Auditlog> findBydetail(String detail) {
		return findByCriteria(Restrictions.eq("detail", detail));
	}
	
	/**
	 * Find Auditlog by createdDate
	 */
	public List<Auditlog> findBycreatedDate(Date createdDate) {
		return findByCriteria(Restrictions.eq("createdDate", createdDate));
	}
	
	/**
	 * Find Auditlog by entityId
	 */
	public List<Auditlog> findByentityId(Integer entityId) {
		return findByCriteria(Restrictions.eq("entityId", entityId));
	}
	
	/**
	 * Find Auditlog by entityName
	 */
	public List<Auditlog> findByentityName(String entityName) {
		return findByCriteria(Restrictions.eq("entityName", entityName));
	}
	
	/**
	 * Find Auditlog by detailOut
	 */
	public List<Auditlog> findBydetailOut(String detailOut) {
		return findByCriteria(Restrictions.eq("detailOut", detailOut));
	}
	
}