package com.pruvn.printserver.entity;
/*
 * Java bean class for entity table auditlog 
 * Created on 5 Mar 2014 ( Time 16:50:30 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */



import java.util.List;
import java.io.Serializable;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import java.util.Date;

/**
 * Domain/Entity bean for table "auditlog"
 * 
 * @author Telosys Tools Generator
 *
 */
@Entity 
@Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Table(name="AUDITLOG")
public class AuditLog implements Serializable
{
    private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="AUDITLOG_SEQ")
	@SequenceGenerator(name="AUDITLOG_SEQ", sequenceName="AUDITLOG_SEQ")
	@Column(name="AUDIT_LOG_ID")
    private Long    auditLogId   ; // Primary Key

	@Column(name="ACTION")
    private String     action       ;
	@Column(name="DETAIL")
    private String     detail       ;
	@Column(name="CREATED_DATE")
    private Date       createdDate  ;
	@Column(name="ENTITY_ID")
    private Long    entityId     ;
	@Column(name="ENTITY_NAME")
    private String     entityName   ;
	@Column(name="DETAIL_OUT")
    private String     detailOut    ;
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "auditLogId" field value
     * This field is mapped on the database column "AUDIT_LOG_ID" ( type "INT UNSIGNED", NotNull : true ) 
     * @param auditLogId
     */
	

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : ACTION ( VARCHAR ) 
    /**
     * Set the "action" field value
     * This field is mapped on the database column "ACTION" ( type "VARCHAR", NotNull : false ) 
     * @param action
     */
    public void setAction( String action )
    {
        this.action = action;
    }
    /**
     * Get the "action" field value
     * This field is mapped on the database column "ACTION" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getAction()
    {
        return this.action;
    }

    //--- DATABASE MAPPING : DETAIL ( TEXT ) 
    /**
     * Set the "detail" field value
     * This field is mapped on the database column "DETAIL" ( type "TEXT", NotNull : false ) 
     * @param detail
     */
    public void setDetail( String detail )
    {
        this.detail = detail;
    }
    /**
     * Get the "detail" field value
     * This field is mapped on the database column "DETAIL" ( type "TEXT", NotNull : false ) 
     * @return the field value
     */
    public String getDetail()
    {
        return this.detail;
    }

    //--- DATABASE MAPPING : CREATED_DATE ( DATETIME ) 
    /**
     * Set the "createdDate" field value
     * This field is mapped on the database column "CREATED_DATE" ( type "DATETIME", NotNull : false ) 
     * @param createdDate
     */
    public void setCreatedDate( Date createdDate )
    {
        this.createdDate = createdDate;
    }
    /**
     * Get the "createdDate" field value
     * This field is mapped on the database column "CREATED_DATE" ( type "DATETIME", NotNull : false ) 
     * @return the field value
     */
    public Date getCreatedDate()
    {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : ENTITY_ID ( INT UNSIGNED ) 
    /**
     * Set the "entityId" field value
     * This field is mapped on the database column "ENTITY_ID" ( type "INT UNSIGNED", NotNull : false ) 
     * @param entityId
     */
   

    //--- DATABASE MAPPING : ENTITY_NAME ( VARCHAR ) 
    /**
     * Set the "entityName" field value
     * This field is mapped on the database column "ENTITY_NAME" ( type "VARCHAR", NotNull : false ) 
     * @param entityName
     */
    public void setEntityName( String entityName )
    {
        this.entityName = entityName;
    }
    /**
     * Get the "entityName" field value
     * This field is mapped on the database column "ENTITY_NAME" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getEntityName()
    {
        return this.entityName;
    }

    //--- DATABASE MAPPING : DETAIL_OUT ( TEXT ) 
    /**
     * Set the "detailOut" field value
     * This field is mapped on the database column "DETAIL_OUT" ( type "TEXT", NotNull : false ) 
     * @param detailOut
     */
    public void setDetailOut( String detailOut )
    {
        this.detailOut = detailOut;
    }
    /**
     * Get the "detailOut" field value
     * This field is mapped on the database column "DETAIL_OUT" ( type "TEXT", NotNull : false ) 
     * @return the field value
     */
    public String getDetailOut()
    {
        return this.detailOut;
    }

    

    public Long getAuditLogId() {
		return auditLogId;
	}
	public void setAuditLogId(Long auditLogId) {
		this.auditLogId = auditLogId;
	}
	public Long getEntityId() {
		return entityId;
	}
	public void setEntityId(Long entityId) {
		this.entityId = entityId;
	}
	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(auditLogId); 
        sb.append("|"); 
        sb.append(action); 
        sb.append( "|" ); 
        sb.append(detail); 
        sb.append( "|" ); 
        sb.append(createdDate); 
        sb.append( "|" ); 
        sb.append(entityId); 
        sb.append( "|" ); 
        sb.append(entityName); 
        sb.append( "|" ); 
        sb.append(detailOut); 
        return sb.toString();
    }

}