package com.pruvn.printserver.entity;

// Generated Jan 14, 2011 9:45:52 PM by Hibernate Tools 3.4.0.Beta1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * CmsSurvey generated by hbm2java
 */
@Entity
@Table(name = "USERMASTER")
@Cache (usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class Usermaster implements java.io.Serializable {
	
private String  username;
private Long  id ;
private String  loggedin;
private Long    role_id ;
private String  session_id;
private String  finnone_security_code;
private String  email_code;
private String  password;
private Date last_changed_pw;
private String  user_place;
private String  department;
private String  fullname;
private String	  usercodeid;
private Long   status ;
private Date  lastlogindate ;
private Date  date_login_temp ;
private Long  count_login_temp ;
private String reason_lock;
private String  channel_id;
	
	
	public Usermaster() {
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="USERMASTER_SEQ")
	@SequenceGenerator(name="USERMASTER_SEQ", sequenceName="USERMASTER_SEQ")
	@Column(name = "ID", unique = true, nullable = false)	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@Column(name = "USERNAME")	
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
	@Column(name = "LOGGEDIN")	
	public String getLoggedin() {
		return loggedin;
	}

	public void setLoggedin(String loggedin) {
		this.loggedin = loggedin;
	}
	@Column(name = "ROLE_ID")	
	public Long getRole_id() {
		return role_id;
	}

	public void setRole_id(Long role_id) {
		this.role_id = role_id;
	}
	@Column(name = "SESSION_ID")	
	public String getSession_id() {
		return session_id;
	}

	public void setSession_id(String session_id) {
		this.session_id = session_id;
	}
	@Column(name = "FINNONE_SECURITY_CODE")	
	public String getFinnone_security_code() {
		return finnone_security_code;
	}

	public void setFinnone_security_code(String finnone_security_code) {
		this.finnone_security_code = finnone_security_code;
	}
	@Column(name = "EMAIL_CODE")	
	public String getEmail_code() {
		return email_code;
	}

	public void setEmail_code(String email_code) {
		this.email_code = email_code;
	}
	@Column(name = "PASSWORD")	
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	@Column(name = "LAST_CHANGED_PW")	
	public Date getLast_changed_pw() {
		return last_changed_pw;
	}

	public void setLast_changed_pw(Date last_changed_pw) {
		this.last_changed_pw = last_changed_pw;
	}
	@Column(name = "USER_PLACE")	
	public String getUser_place() {
		return user_place;
	}

	public void setUser_place(String user_place) {
		this.user_place = user_place;
	}
	@Column(name = "DEPARTMENT")	
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}
	@Column(name = "FULLNAME")	
	public String getFullname() {
		return fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}
	@Column(name = "USERCODEID")	
	public String getUsercodeid() {
		return usercodeid;
	}

	public void setUsercodeid(String usercodeid) {
		this.usercodeid = usercodeid;
	}
	@Column(name = "STATUS")	
	public Long getStatus() {
		return status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}
	@Column(name = "LASTLOGINDATE")	
	public Date getLastlogindate() {
		return lastlogindate;
	}

	public void setLastlogindate(Date lastlogindate) {
		this.lastlogindate = lastlogindate;
	}
	@Column(name = "DATE_LOGIN_TEMP")	
	public Date getDate_login_temp() {
		return date_login_temp;
	}

	public void setDate_login_temp(Date date_login_temp) {
		this.date_login_temp = date_login_temp;
	}
	@Column(name = "COUNT_LOGIN_TEMP")	
	public Long getCount_login_temp() {
		return count_login_temp;
	}

	public void setCount_login_temp(Long count_login_temp) {
		this.count_login_temp = count_login_temp;
	}
	@Column(name = "REASON_LOCK")	
	public String getReason_lock() {
		return reason_lock;
	}

	public void setReason_lock(String reason_lock) {
		this.reason_lock = reason_lock;
	}
	@Column(name = "CHANNEL_ID")	
	public String getChannel_id() {
		return channel_id;
	}

	public void setChannel_id(String channel_id) {
		this.channel_id = channel_id;
	}
	


	

}
