package com.pruvn.printserver.entity;

// Generated Jan 14, 2011 9:45:52 PM by Hibernate Tools 3.4.0.Beta1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * CmsSurvey generated by hbm2java
 */
@Entity
@Table(name = "USERROLEM")
@Cache (usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class UserRoleM implements java.io.Serializable {
	
	private Long  id;
	private String  role_name ;
	
	
	public UserRoleM() {
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@Column(name = "ROLE_NAME")	
	public String getRole_name() {
		return role_name;
	}

	public void setRole_name(String role_name) {
		this.role_name = role_name;
	}
	


	

}
