/*
 * Java bean class for entity table RM_BRANCH 
 * Created on 3 Oct 2013 ( Time 12:18:01 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.dao;

import java.util.List;

import com.pruvn.rms.domain.Branch;


/**
 * Data Access Object interface for table "RM_BRANCH"
 * 
 * @author Telosys Tools Generator
 *
 */

public interface BranchDao extends GenericDAO<Branch,Integer> 
{
    

	/**
	 * Find RmBranch by username
	 */
	public List<Branch> findBycode(String code);
	/**
	 * Find RmBranch by username
	 */
	public List<Branch> findByname(String name);
	
	public List<Branch> findAllActive();
}


