/*
 * Java bean class for entity table RM_SCREEN 
 * Created on 3 Oct 2013 ( Time 12:18:01 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.dao;

import java.util.List;

import com.pruvn.rms.domain.Foreclosure;
import com.pruvn.rms.domain.TB6;
import com.pruvn.rms.model.FilterMRCForm;


/**
 * Data Access Object interface for table "RM_MRC"
 * 
 * @author Telosys Tools Generator
 *
 */

public interface ForeclosureDao extends GenericDAO<Foreclosure,Integer> 
{

	Foreclosure findByLoanNo(String loanNo);
    
	List<Foreclosure> searchByLoanNo(String loanNo);

	List<Foreclosure> getForeclosureList(String stage,
			FilterMRCForm filterMRCForm);
}


