/*
 * Java bean class for entity table RM_SCREEN 
 * Created on 3 Oct 2013 ( Time 12:18:01 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.dao;

import java.util.List;

import com.pruvn.rms.domain.HomeLoan;


/**
 * Data Access Object interface for table "RM_HOME_LOAN"
 * 
 * @author Telosys Tools Generator
 *
 */

public interface HomeLoanDao extends GenericDAO<HomeLoan,Integer> 
{

	HomeLoan findByLoanNo(String loanNo);
    
	List<HomeLoan> searchByLoanNo(String loanNo);

//	/**
//	 * Find RmScreen by username
//	 */
//	public List<Screen> findByStage(String stage);
//	/**
//	 * Find RmScreen by username
//	 */
//	public List<Screen> findByname(String name);
//	
//	public List<Screen> findAllActive();
//	
//	public List<Screen> getListScreen(String stage, String system);
//	
//	public List<Screen> getListScreen2(String stage2, String system);
}


