/*
 * Java bean class for entity table RM_SCREEN 
 * Created on 3 Oct 2013 ( Time 12:18:01 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.dao;

import java.util.List;

import com.pruvn.rms.domain.MRC;
import com.pruvn.rms.model.FilterMRCForm;


/**
 * Data Access Object interface for table "RM_MRC"
 * 
 * @author Telosys Tools Generator
 *
 */

public interface MRCDao extends GenericDAO<MRC,Integer> 
{

	MRC findByLoanNo(String loanNo);
    
	List<MRC> searchByLoanNo(String loanNo);

	List<MRC> getMRCList(FilterMRCForm filterMRCForm);

//	/**
//	 * Find RmScreen by username
//	 */
//	public List<Screen> findByStage(String stage);
//	/**
//	 * Find RmScreen by username
//	 */
//	public List<Screen> findByname(String name);
//	
//	public List<Screen> findAllActive();
//	
//	public List<Screen> getListScreen(String stage, String system);
//	
//	public List<Screen> getListScreen2(String stage2, String system);
}


