/*
 * Java bean class for entity table RM_PRODUCT 
 * Created on 3 Oct 2013 ( Time 12:18:07 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.dao;

import java.util.List;

import com.pruvn.rms.domain.Product;

/**
 * Data Access Object interface for table "RM_PRODUCT"
 * 
 * @author Telosys Tools Generator
 *
 */

public interface ProductDao extends GenericDAO<Product,Integer>
{
    

	/**
	 * Find RmProduct by username
	 */
	public List<Product> findByCode(String code);
	/**
	 * Find RmProduct by username
	 */
	public List<Product> findByName(String name);
	/**
	 * Find RmProduct by username
	 */
	public List<Product> findByDescription(String description);
	/**
	 * Find RmProduct by username
	 */
	public List<Product> findByBranchId(Integer branchId);
}


