/*
 * Java bean class for entity table RM_SCREEN 
 * Created on 3 Oct 2013 ( Time 12:18:01 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.dao;

import java.util.List;

import com.pruvn.rms.domain.StoredLoan;
import com.pruvn.rms.model.FilterStoredLoanForm;


/**
 * Data Access Object interface for table "RM_MRC"
 * 
 * @author Telosys Tools Generator
 *
 */

public interface StoredLoanDao extends GenericDAO<StoredLoan,Integer> 
{
	StoredLoan findByBarCodeAndNameBox(String barCode,String nameBox);
	List<StoredLoan> getForeclosureList(FilterStoredLoanForm filterMRCForm);
	int updateDestroyStoredLoan(StoredLoan store,String username);
}


