/*
 * Java bean class for entity table RM_SCREEN 
 * Created on 3 Oct 2013 ( Time 12:18:01 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.dao;

import java.util.List;

import com.pruvn.rms.domain.TB6;
import com.pruvn.rms.model.FilterMRCForm;
import com.pruvn.rms.utils.Constant.TB6_STAGE;


/**
 * Data Access Object interface for table "RM_MRC"
 * 
 * @author Telosys Tools Generator
 *
 */

public interface TB6Dao extends GenericDAO<TB6,Integer> 
{

	TB6 findByLoanNo(String loanNo);
    
	List<TB6> searchByLoanNo(String loanNo);

	List<TB6> getTB6List(String stage,
			FilterMRCForm filterMRCForm);
}


