/*
 * Java bean class for entity table RM_UploadData 
 * Created on 3 Oct 2013 ( Time 12:18:01 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.dao;

import com.pruvn.rms.domain.UploadData;


/**
 * Data Access Object interface for table "RM_UploadData"
 * 
 * @author Telosys Tools Generator
 *
 */

public interface UploadDataDao extends GenericDAO<UploadData,Integer> 
{
    
}


