/*
 * Java bean class for entity table user_level_a 
 * Created on 17 May 2013 ( Time 17:03:25 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.dao;

import java.util.List;

import com.pruvn.rms.domain.UserLevelA;
import com.pruvn.rms.domain.UserLevelM;
import com.pruvn.rms.domain.UserM;


/**
 * Data Access Object interface for table "user_level_a"
 * 
 * @author Telosys Tools Generator
 *
 */

public interface UserLevelADao extends GenericDAO<UserLevelA,Integer> 
{
    

	/**
	 * Find UserLevelA by username
	 */
	public UserLevelA findByuserid(UserM userid);
	/**
	 * Find UserLevelA by username
	 */
	public UserLevelA findBylevelid(UserLevelM levelid);
	
	public void deleteByUserId(Integer userId);
}


