/*
 * Java bean class for entity table user_level_m 
 * Created on 17 May 2013 ( Time 17:03:25 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.dao;

import java.util.List;

import com.pruvn.rms.domain.UserLevelM;


/**
 * Data Access Object interface for table "user_level_m"
 * 
 * @author Telosys Tools Generator
 *
 */

public interface UserLevelMDao extends GenericDAO<UserLevelM,Integer> 
{
    

	/**
	 * Find UserLevelM by username
	 */
	public List<UserLevelM> findBylevelcode(String levelcode);
	/**
	 * Find UserLevelM by username
	 */
	public List<UserLevelM> findBylevelname(String levelname);
	/**
	 * Find UserLevelM by username
	 */
	public List<UserLevelM> findByleveldesc(String leveldesc);
}


