package com.pruvn.rms.domain;

// Generated Jan 27, 2010 7:12:23 PM by Hibernate Tools 3.2.5.Beta

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Auditlog generated by hbm2java
 */

@Entity
@Table(name = "AUDIT_LOG")
public class AuditLog implements java.io.Serializable {

	@Id
	@GenericGenerator(name = "generator", strategy = "sequence-identity", parameters = @Parameter(name = "sequence", value = "SEQ_AUDIT_LOG"))
    @GeneratedValue(generator = "generator")
	@Column(name = "AUDIT_LOG_ID")
	private Integer auditLogId;
	
	@Column(name = "ACTION", nullable = true)
	private String action;
	
	@Column(name = "DETAIL", nullable = true)
	private String detail;
	
	@Column(name = "CREATED_DATE", nullable = true)
	@Temporal(TemporalType.TIMESTAMP)
	private Date createdDate;
	
	@Column(name = "ENTITY_ID", nullable = true)
	private Integer entityId;
	
	@Column(name = "ENTITY_NAME", nullable = true)
	private String entityName;

	public AuditLog() {
	}

	public AuditLog(String action, String detail, Date createdDate,
			Integer entityId, String entityName) {
		this.action = action;
		this.detail = detail;
		this.createdDate = createdDate;
		this.entityId = entityId;
		this.entityName = entityName;
	}


	public Integer getAuditLogId() {
		return auditLogId;
	}

	public void setAuditLogId(Integer auditLogId) {
		this.auditLogId = auditLogId;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Integer getEntityId() {
		return entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	public String getEntityName() {
		return this.entityName;
	}

	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}

}
