/*
 * Java bean class for entity table RM_LOG_TRANSACTION 
 * Created on 21 Aug 2013 ( Time 15:15:34 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.domain;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;


/**
 * Domain/Entity bean for table "RM_LOG_TRANSACTION"
 * 
 * @author Telosys Tools Generator
 *
 */
@Entity 
@Table(name="CS_LOG_TRANSACTION_V")
public class CSLogTransaction implements Serializable
{
    private static final long serialVersionUID = 1L;


	@Id
	@Column(name="ID")
	@GenericGenerator(name = "generator", strategy = "sequence-identity", parameters = @Parameter(name = "sequence", value = "CS_LOG_TRANSACTION_SEQ"))
    @GeneratedValue(generator = "generator")
    private Integer    id           ;
	
	@Column(name="LOG_DATE")
    private Date       logDate      ;
	
	@Column(name="CUR_STAGE")
    private String     curStage     ;
	
	@Column(name="SCREEN_NAME")
    private String     screenName     ;
	
	@Column(name="NEXT_STAGE")
    private String     nextStage     ;
	
	@Column(name="TO_SCREEN_NAME")
    private String     toScreenName     ;
	
	@Column(name="ACTION")
    private String     action       ;
	
	@Column(name="CREATE_BY")
    private String     createBy     ;
	
	@Column(name="RECORD_ID")
    private Integer    recordId     ;
	
	@Column(name="DESCRIPTION")
    private String     description       ;
	    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : ID ( NUMBER ) 
    /**
     * Set the "id" field value
     * This field is mapped on the database column "ID" ( type "NUMBER", NotNull : false ) 
     * @param id
     */
    public void setId( Integer id )
    {
        this.id = id;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "ID" ( type "NUMBER", NotNull : false ) 
     * @return the field value
     */
    public Integer getId()
    {
        return this.id;
    }

    //--- DATABASE MAPPING : LOG_DATE ( DATE ) 
    /**
     * Set the "logDate" field value
     * This field is mapped on the database column "LOG_DATE" ( type "DATE", NotNull : false ) 
     * @param logDate
     */
    public void setLogDate( Date logDate )
    {
        this.logDate = logDate;
    }
    /**
     * Get the "logDate" field value
     * This field is mapped on the database column "LOG_DATE" ( type "DATE", NotNull : false ) 
     * @return the field value
     */
    public Date getLogDate()
    {
        return this.logDate;
    }

    //--- DATABASE MAPPING : CUR_STAGE ( VARCHAR2 ) 
    /**
     * Set the "curStage" field value
     * This field is mapped on the database column "CUR_STAGE" ( type "VARCHAR2", NotNull : false ) 
     * @param curStage
     */
    public void setCurStage( String curStage )
    {
        this.curStage = curStage;
    }
    /**
     * Get the "curStage" field value
     * This field is mapped on the database column "CUR_STAGE" ( type "VARCHAR2", NotNull : false ) 
     * @return the field value
     */
    public String getCurStage()
    {
        return this.curStage;
    }

    public String getScreenName() {
		return screenName;
	}
	public void setScreenName(String screenName) {
		this.screenName = screenName;
	}
	//--- DATABASE MAPPING : ACTION ( VARCHAR2 ) 
    /**
     * Set the "action" field value
     * This field is mapped on the database column "ACTION" ( type "VARCHAR2", NotNull : false ) 
     * @param action
     */
    public void setAction( String action )
    {
        this.action = action;
    }
    /**
     * Get the "action" field value
     * This field is mapped on the database column "ACTION" ( type "VARCHAR2", NotNull : false ) 
     * @return the field value
     */
    public String getAction()
    {
        return this.action;
    }

    //--- DATABASE MAPPING : CREATE_BY ( VARCHAR2 ) 
    /**
     * Set the "createBy" field value
     * This field is mapped on the database column "CREATE_BY" ( type "VARCHAR2", NotNull : false ) 
     * @param createBy
     */
    public void setCreateBy( String createBy )
    {
        this.createBy = createBy;
    }
    /**
     * Get the "createBy" field value
     * This field is mapped on the database column "CREATE_BY" ( type "VARCHAR2", NotNull : false ) 
     * @return the field value
     */
    public String getCreateBy()
    {
        return this.createBy;
    }

    //--- DATABASE MAPPING : RECORD_ID ( NUMBER ) 
    /**
     * Set the "recordId" field value
     * This field is mapped on the database column "RECORD_ID" ( type "NUMBER", NotNull : false ) 
     * @param recordId
     */
    public void setRecordId( Integer recordId )
    {
        this.recordId = recordId;
    }
    /**
     * Get the "recordId" field value
     * This field is mapped on the database column "RECORD_ID" ( type "NUMBER", NotNull : false ) 
     * @return the field value
     */
    public Integer getRecordId()
    {
        return this.recordId;
    }

    

    public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	

    public String getNextStage() {
		return nextStage;
	}
	public void setNextStage(String nextStage) {
		this.nextStage = nextStage;
	}
	public String getToScreenName() {
		return toScreenName;
	}
	public void setToScreenName(String toScreenName) {
		this.toScreenName = toScreenName;
	}
	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(id); 
        sb.append("|"); 
        sb.append(logDate); 
        sb.append( "|" ); 
        sb.append(curStage); 
        sb.append( "|" ); 
        sb.append(action); 
        sb.append( "|" ); 
        sb.append(createBy); 
        sb.append( "|" ); 
        sb.append(recordId); 
        sb.append( "|" ); 
        sb.append(description); 
        sb.append( "|" ); 
        return sb.toString();
    }

}
