/*
 * Java bean class for entity table RM_PRODUCT 
 * Created on 3 Oct 2013 ( Time 12:18:07 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.domain;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Domain/Entity bean for table "RM_PRODUCT"
 * 
 * @author Telosys Tools Generator
 * 
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Table(name = "CS_UPLOAD_DATA")
public class CSUploadData implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID")
	@GenericGenerator(name = "generator", strategy = "sequence-identity", parameters = @Parameter(name = "sequence", value = "CS_UPLOAD_DATA_SEQ"))
	@GeneratedValue(generator = "generator")
	private Integer id; // Primary Key

	@Column(name = "RECORD_ID")
	private Integer recordID;
	
	@Column(name = "LOAN_ID")
	private String loanID;

	@Column(name = "CUSTOMER_NAME")
	private String customerName;

	@Column(name = "PENDING_DATE")
	private String pendingDate;

	@Column(name = "PENDING_REASON")
	private String pendingReason;
	
	@Column(name = "FAILED_DATE")
	private String failedDate;

	@Column(name = "FAILED_REASON")
	private String failedReason;
	
	@Column(name = "DELIVER_DATE")
	private String deliverDate;

	@Column(name = "RECEIVE_DATE")
	private String receiveDate;
	
	@Column(name = "FAIL_TO_COMPLETE_NOTE")
	private String failToCompleteNote;	
	
	@Column(name = "COMPLETE_TO_FAIL_NOTE")
	private String completeToFailNote;	

	@Column(name = "ERROR_MESSAGE")
	private String errorMessage;
	
	@Column(name = "UPLOAD_TYPE")
	private String uploadType;
	
	@Column(name = "UPLOAD_STATUS")
	private String uploadStatus;
	
	@Column(name = "UPLOAD_DATE")
	@Temporal(TemporalType.TIMESTAMP)
	private Date uploadDate;
	
	@Column(name = "UPLOAD_USER")
	private String uploadUser;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getRecordID() {
		return recordID;
	}

	public void setRecordID(Integer recordID) {
		this.recordID = recordID;
	}

	public String getLoanID() {
		return loanID;
	}

	public void setLoanID(String loanID) {
		this.loanID = loanID;
	}

	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getPendingDate() {
		return pendingDate;
	}

	public void setPendingDate(String pendingDate) {
		this.pendingDate = pendingDate;
	}

	public String getPendingReason() {
		return pendingReason;
	}

	public void setPendingReason(String pendingReason) {
		this.pendingReason = pendingReason;
	}

	public String getFailedDate() {
		return failedDate;
	}

	public void setFailedDate(String failedDate) {
		this.failedDate = failedDate;
	}

	public String getFailedReason() {
		return failedReason;
	}

	public void setFailedReason(String failedReason) {
		this.failedReason = failedReason;
	}

	public String getDeliverDate() {
		return deliverDate;
	}

	public void setDeliverDate(String deliverDate) {
		this.deliverDate = deliverDate;
	}


	public String getReceiveDate() {
		return receiveDate;
	}

	public void setReceiveDate(String receiveDate) {
		this.receiveDate = receiveDate;
	}

	public String getFailToCompleteNote() {
		return failToCompleteNote;
	}

	public void setFailToCompleteNote(String failToCompleteNote) {
		this.failToCompleteNote = failToCompleteNote;
	}

	public String getCompleteToFailNote() {
		return completeToFailNote;
	}

	public void setCompleteToFailNote(String completeToFailNote) {
		this.completeToFailNote = completeToFailNote;
	}

	public String getErrorMessage() {
		return errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

	public String getUploadType() {
		return uploadType;
	}

	public void setUploadType(String uploadType) {
		this.uploadType = uploadType;
	}

	public String getUploadStatus() {
		return uploadStatus;
	}

	public void setUploadStatus(String uploadStatus) {
		this.uploadStatus = uploadStatus;
	}

	public Date getUploadDate() {
		return uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	public String getUploadUser() {
		return uploadUser;
	}

	public void setUploadUser(String uploadUser) {
		this.uploadUser = uploadUser;
	}
	
}