/*
 * Java bean class for entity table RM_PRODUCT 
 * Created on 3 Oct 2013 ( Time 12:18:07 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Domain/Entity bean for table "RM_PRODUCT"
 * 
 * @author Telosys Tools Generator
 *
 */
@Entity 
@Table(name="RM_LOAN")
public class Icm implements Serializable
{
    private static final long serialVersionUID = 1L;

	@Id
	@Column(name="LOANNO")
    private String loanNo ; // Primary Key

	@Column(name="AFN")
    private String    appFormNo;
	
	@Column(name="ARN")
    private String arn;

	public String getLoanNo() {
		return loanNo;
	}

	public void setLoanNo(String loanNo) {
		this.loanNo = loanNo;
	}

	public String getAppFormNo() {
		return appFormNo;
	}

	public void setAppFormNo(String appFormNo) {
		this.appFormNo = appFormNo;
	}

	public String getArn() {
		return arn;
	}

	public void setArn(String arn) {
		this.arn = arn;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	

}