/*
 * Java bean class for entity table RM_PRODUCT 
 * Created on 3 Oct 2013 ( Time 12:18:07 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.domain;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Domain/Entity bean for table "RM_PRODUCT"
 * 
 * @author Telosys Tools Generator
 * 
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Table(name = "RM_UPLOAD_DATA")
public class UploadData implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID")
	@GenericGenerator(name = "generator", strategy = "sequence-identity", parameters = @Parameter(name = "sequence", value = "RM_UPLOAD_DATA_SEQ"))
	@GeneratedValue(generator = "generator")
	private Integer id; // Primary Key

	@Column(name = "RECORD_ID")
	private Integer recordID;
	
	@Column(name = "LOAN_ID")
	private String loanID;

	@Column(name = "CUSTOMER_NAME")
	private String customerName;

	@Column(name = "RETURN_DATE")
	@Temporal(TemporalType.TIMESTAMP)
	private Date returnDate;

	@Column(name = "REASON_POST")
	private String reasonPost;

	@Column(name = "BILL_NO")
	private String billNo;
	
	@Column(name = "DELIVERED_DATE")
	@Temporal(TemporalType.TIMESTAMP)
	private Date deliveredDate;
	
	@Column(name = "RECEIVER")
	private String receiver;
	

	@Column(name = "ERROR_MESSAGE")
	private String errorMessage;
	
	@Column(name = "UPLOAD_TYPE")
	private String uploadType;
	
	@Column(name = "UPLOAD_STATUS")
	private String uploadStatus;
	
	@Column(name = "UPLOAD_DATE")
	@Temporal(TemporalType.TIMESTAMP)
	private Date uploadDate;
	
	@Column(name = "UPLOAD_USER")
	private String uploadUser;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getRecordID() {
		return recordID;
	}

	public void setRecordID(Integer recordID) {
		this.recordID = recordID;
	}

	public String getLoanID() {
		return loanID;
	}

	public void setLoanID(String loanID) {
		this.loanID = loanID;
	}

	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public Date getReturnDate() {
		return returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

	public String getReasonPost() {
		return reasonPost;
	}

	public void setReasonPost(String reasonPost) {
		this.reasonPost = reasonPost;
	}

	public String getBillNo() {
		return billNo;
	}

	public void setBillNo(String billNo) {
		this.billNo = billNo;
	}

	public Date getDeliveredDate() {
		return deliveredDate;
	}

	public void setDeliveredDate(Date deliveredDate) {
		this.deliveredDate = deliveredDate;
	}

	public String getReceiver() {
		return receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	public String getErrorMessage() {
		return errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

	public String getUploadType() {
		return uploadType;
	}

	public void setUploadType(String uploadType) {
		this.uploadType = uploadType;
	}

	public String getUploadStatus() {
		return uploadStatus;
	}

	public void setUploadStatus(String uploadStatus) {
		this.uploadStatus = uploadStatus;
	}

	public Date getUploadDate() {
		return uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	public String getUploadUser() {
		return uploadUser;
	}

	public void setUploadUser(String uploadUser) {
		this.uploadUser = uploadUser;
	}
	
}