/*
 * Java bean class for entity table user_level_a 
 * Created on 17 May 2013 ( Time 17:03:25 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.domain;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;


/**
 * Domain/Entity bean for table "user_level_a"
 * 
 * @author Telosys Tools Generator
 *
 */
@Entity
@Table(name = "USER_LEVEL_A")
public class UserLevelA implements Serializable
{
    private static final long serialVersionUID = 1L;

	@Id
	@GenericGenerator(name = "generator", strategy = "sequence-identity", parameters = @Parameter(name = "sequence", value = "SEQ_USER_LEVEL_A"))
    @GeneratedValue(generator = "generator")
	@Column(name = "USERLEVELID")
    private Integer        userlevelid  ; // Primary Key

	@ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH} , fetch = FetchType.LAZY)	
	@JoinColumn(name = "USERID", nullable = false)
    private UserM    user       ;
	
	@ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH}, fetch = FetchType.LAZY)	
	@JoinColumn(name = "LEVELID", nullable = false)
    private UserLevelM    level      ;
	/**
	 * @return the userlevelid
	 */
	public Integer getUserlevelid() {
		return userlevelid;
	}
	/**
	 * @param userlevelid the userlevelid to set
	 */
	public void setUserlevelid(Integer userlevelid) {
		this.userlevelid = userlevelid;
	}
	/**
	 * @return the user
	 */
	public UserM getUser() {
		return user;
	}
	/**
	 * @param user the user to set
	 */
	public void setUser(UserM user) {
		this.user = user;
	}
	/**
	 * @return the level
	 */
	public UserLevelM getLevel() {
		return level;
	}
	/**
	 * @param level the level to set
	 */
	public void setLevel(UserLevelM level) {
		this.level = level;
	}
    
    
}
