package com.pruvn.tools.common.hibernate.finnone.lending;

// Generated May 31, 2011 2:37:34 PM by Hibernate Tools 3.2.4.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LEA_AGREEMENT_DTL generated by hbm2java
 */
public class LEA_AGREEMENT_DTL implements java.io.Serializable {

	private int PROPOSALID;
	private Integer AGREEMENTID;
	private String AGREEMENTTYPE;
	private String AGREEMENTNO;
	private int APPLID;
	private BigDecimal ASSETCOST;
	private BigDecimal AMTFIN;
	private BigDecimal INTRATE;
	private BigDecimal EFFRATE;
	private BigDecimal MARKUP;
	private String INTTYPE;
	private short TENURE;
	private String FREQ;
	private short NUMINSTL;
	private String INSTALTYPE;
	private String INSTLMODE;
	private Short ADVANCEINSTL;
	private BigDecimal PRETAXIRR;
	private BigDecimal POSTTAXIRR;
	private Date SANCTIONDATE;
	private Integer AUTHID;
	private Integer STATEID;
	private Integer CATGID;
	private BigDecimal TAXRATE;
	private BigDecimal BOUNCECHEQUEFEE;
	private BigDecimal BROKERAGERATE;
	private BigDecimal MGMTFEERATE;
	private BigDecimal RVRATE;
	private BigDecimal SDRATE;
	private BigDecimal OVERDUERATE;
	private Date AGREEMENTDATE;
	private Date COMMENCEDATE;
	private Date CLOSUREDATE;
	private Date RESCHEDULEDATE;
	private String STATUS;
	private BigDecimal SPOTINTRATE;
	private Integer SCHEMEID;
	private BigDecimal MARGINMONEY;
	private Date PROPOSALCRDATE;
	private String PROPOSALCRBY;
	private Date AGREEMENTCRDATE;
	private String AGREEMENTCRBY;
	private Date PROPOSALMODDATE;
	private String PROPOSALMODBY;
	private Date CREDITAUTHDATE;
	private String CREDITAUTHBY;
	private Date PRDDOCAUTHDATE;
	private String PRDDOCAUTHBY;
	private Date PODDOCAUTHDATE;
	private String PODDOCAUTHBY;
	private String CREDITAUTHREQD;
	private String PRDAUTHREQD;
	private String PODAUTHREQD;
	private Integer LESSEEID;
	private String ACTION;
	private Date ACTIONDATE;
	private String PRINT_FLAG;
	private String DUEDAY;
	private String CREDITAUTHREQD_S;
	private Date CREDITAUTHDATE_S;
	private String CREDITAUTHBY_S;
	private String CREDITAUTHREQD_O;
	private Date CREDITAUTHDATE_O;
	private String CREDITAUTHBY_O;
	private BigDecimal AMTOTHERS;
	private BigDecimal REBATE;
	private BigDecimal PENALTY;
	private String ACCRUAL_FLAG;
	private String CURRENCYID;
	private String PRININTCAL;
	private String DEANNUALIZE;
	private Integer BRANCHID;
	private Date APPDATE;
	private BigDecimal EMI;
	private BigDecimal RESVALUE;
	private BigDecimal ACCESSAMT;
	private BigDecimal PREPAYPENALTY;
	private BigDecimal MARGINRATE;
	private String FINALSOURCE;
	private String FINALSOURCEID;
	private String FIRSTSOURCE;
	private String FIRSTSOURCEID;
	private String PROMOTIONSCHEME;
	private String LOAN_IN_NAME;
	private Integer SUPPLIERID;
	private String DPERYR;
	private Date DISBURSALDATE;
	private Byte FORECLOSELOCKLN;
	private String PRODUCTFLAG;
	private String PDCFLAG;
	private Boolean DECIMALS;
	private String RS_CONFIRM;
	private BigDecimal GRACEPERIOD;
	private Date LEA_LAST_ACR_DATE;
	private Date LEA_NON_ACR_FLAG;
	private BigDecimal LEA_ACR_INT_AMT;
	private Integer BATCHNUMBER;
	private BigDecimal ACCOUNTING_MONTHLY_IRR;
	private BigDecimal LEA_MONTHLY_IRR;
	private BigDecimal MARGIN_MONEY_2;
	private String NOTEPAD;
	private BigDecimal VAT_PRIN_RATE;
	private BigDecimal VAT_INT_RATE;
	private Integer CRSCORE;
	private Short AGE;
	private Short MATURITY_AGE;
	private String NPA_STAGEID;
	private String BILL_FLAG;
	private Date LAST_LPI_DATE;
	private Date NPA_DATE;
	private Integer DPD;
	private String DPD_STRING;
	private Date DATELASTUPDT;
	private BigDecimal DISBURSEDAMOUNT;
	private BigDecimal FINANCECHARGE;
	private BigDecimal BENEFITAMOUNT;
	private String DISBURSALTO;
	private Integer MKTGID;
	private Integer BROKERID;
	private Integer REFAGREEMENTID;
	private BigDecimal ADVDISBINTRATE;
	private BigDecimal VAT_INSTL_RATE;
	private BigDecimal VAT_INPUT;
	private Date DPD_STRING_STAMPDATE;
	private Short BUCKET;
	private Byte CURRSEQNO;
	private String GRACE_INTEREST_CHARGE;
	private String GRACE_ADJUST_SCHEDULE;
	private Integer SANCTIONID;
	private String AUTCLOS_FLAG;
	private String MANUAL_NPA_MOVEMENT_FLAG;
	private String DISB_TYPE;
	private Short NO_DISBURSAL;
	private BigDecimal PEMI_RATE;
	private BigDecimal INTTAXRATE;
	private BigDecimal TDSRATE;
	private BigDecimal LPIRATE;
	private String FLOATINGFLG;
	private String PLRTYPE;
	private String TAXAPPLICABLE;
	private String BALANCE_TRANSFER;
	private BigDecimal RELATIONAL_DISCOUNT;
	private BigDecimal OTHER_DISCOUNT;
	private String CO_APPL_REQ;
	private String GUARANTOR_REQ;
	private String SEC_DEPOSIT_REQ;
	private String FORECLOSE_ALLOWED;
	private BigDecimal FORECLOSE_PENALTY;
	private Short FORECLOSE_LOCK_PERIOD;
	private Long ATMCODE;
	private BigDecimal RATE;
	private BigDecimal FEERATE;
	private BigDecimal COSTOFFUNDS;
	private BigDecimal LOSS;
	private BigDecimal EXPENSES;
	private BigDecimal CUSTOMERYIELD;
	private BigDecimal PRETAXROI;
	private BigDecimal ROI;
	private BigDecimal TAX;
	private BigDecimal TAX_PERCENTAGE;
	private BigDecimal SECURITYCOVER;
	private BigDecimal SECURITYTAKEN;
	private String CROSS_COLLATERAL;
	private Integer BILLNO;
	private String RELATIONSHIP_DISC;
	private String PROFESSIONAL_DISC;
	private String PREPAY_ALLOWED;
	private String PREPAY_PENALTY;
	private Short PREPAY_LOCK_PERIOD;
	private String FORECLOSURE_PENALTY;
	private Integer DSSNO;
	private Date MATURITYDATE;
	private String DEL_MONTHLY_STRING;
	private BigDecimal MATURITYAMT;
	private String TENURETYPE;
	private String LPITYPE;
	private Short ACTUAL_MONTHS;
	private Short ACTUAL_DAYS;
	private String MATCH_FOUND;
	private String DEDUPE_RESULT;
	private Integer EMPLOYERID;
	private Date REPAYMENT_EFFECTIVE_DATE;
	private BigDecimal OUTSTANDINGPRINPRECENT;
	private BigDecimal MIN_PENALAMOUNT;
	private String EMP_FLAG;
	private BigDecimal PLRRATE;
	private Integer INSURCOID;
	private Integer INSUR_PRODUCTID;
	private String INSURANCE_FLAG;
	private Date INSURED_TILL;
	private String DEPOSIT_ACCOUNT;
	private BigDecimal SPREAD2;
	private Short FLOATING_FREQUENCY;
	private Date LAST_FLOAT_SPREAD_DATE;
	private BigDecimal LTV_MULTIPLIER;
	private String DISBURSEMENT_DIRECT_CREDIT;
	private Short STAT_ACC_FREQUENCY;
	private String SYSTEM;
	private BigDecimal AMTFIN_REGULAR;
	private BigDecimal AMTFIN_BONUS;
	private String FREQ_BONUS;
	private String INSTLMODE_BONUS;
	private Short ADVANCEINSTL_BONUS;
	private Date DISBURSALDATE_BONUS;
	private String INT_ROUNDOFF_PARA;
	private Integer INT_ROUNDTILL;
	private String INSTLAMT_ROUNDOFF_PARA;
	private Integer INSTLAMT_ROUNDTILL;
	private Short PRIN_BASE_UNIT;
	private Integer FIXED_TERM;
	private Date INTSTART_DATE_BONUS;
	private String INSTALTYPE_BONUS;
	private String INS_BILL_FLAG;
	private BigDecimal SPECIAL_SPREAD;
	private BigDecimal EMI_BONUS;
	private Date NEXT_FLOAT_PRIME_DATE;
	private Date NEXT_FLOAT_SPREAD_DATE;
	private Integer REFINANCE_RECEIPTID;
	private BigDecimal STEP_RATE;
	private Short AGE_PAST_AGR;
	private String INVOICE_FLAG;
	private String RC_FLAG;
	private BigDecimal SERVICETAXRATE;
	private Integer DME_ID;
	private Integer GROUPID;
	private Integer PROMOTIONID;
	private String FILENO;
	private String APP_FORMNO;
	private String HFI_FLAG;
	private String HFI;
	private Integer EMPLOYER_ADDRESSID;
	private String EMPCODE;
	private Integer SPREADID;
	private BigDecimal INITIAL_EFFRATE;
	private Date INTSTART_DATE_REGULAR;
	private String TRANCHING_FLAG;
	private String TRANCHING_TYPE;
	private String COMPOUND_FREQ;
	private String INT_REBATE_FLAG;
	private BigDecimal ACTUALIRR;
	private String DISB_STATUS;
	private BigDecimal GROSS_LTV;
	private BigDecimal NET_LTV;
	private BigDecimal AMT_REQUESTED;
	private Short TENURE_REQUESTED;
	private String RATE_EMI_FLAG;
	private String ASSET_MARKED;
	private BigDecimal DISBURSALAMOUNT;
	private Integer ORG_SCHEMEID;
	private String LSI_AGREEMENT_NO;
	private String CHRG_FLG;
	private String DISB_FLAG;
	private String HL_FILE_NO;
	private String OLD_AGREEMENTNO;
	private String PEMI_BILLING;
	private String REPAY_FLG;
	private String TEMPUPD_DUEDATE;
	private BigDecimal MIN_FLOAT_RATE;
	private String PUTCALL_FLAG;
	private String BILLTYPE;
	private String HUNDINO;
	private Date HUNDIDATE;
	private Date HUNDIDUEDATE;
	private BigDecimal HUNDIAMT;
	private BigDecimal STAMPVALUE;
	private BigDecimal STAMPRATE;
	private BigDecimal INTTAX;
	private String PROGRAM;
	private String DIVISION;
	private Integer MARGINDAYS;
	private String REMARKS;
	private BigDecimal TDS;
	private Integer PARTYID;
	private String CUMULATIVE_INTEREST;
	private BigDecimal FINANCIAL_QUANTUM;
	private String CPF_FIRST_CHARGE_FLAG;
	private String CPF_ARPS_NUMBER;
	private BigDecimal CPF_APP_AMOUNT;
	private BigDecimal CPF_MAXIMUM_MONTHLY;
	private BigDecimal DEALER_PARTICIPATION_RATE;
	private String OVERDUE_PLRTYPE;
	private BigDecimal OVERDUE_MARKUP;
	private BigDecimal APP_LOAN_LIMIT;
	private String PSB_APPL_NO;
	private BigDecimal SUB_ACCT;
	private BigDecimal COLLATERAL_ACCT;
	private BigDecimal FLAT_SPREAD;
	private byte GRACE_DAYS;
	private BigDecimal GRACE_AMT;
	private Integer PREV_LOAN_NO;
	private Integer LINECODEID;
	private Integer SECURITY_CODE;
	private String INSTL_FLAG;
	private String ADMINFEE_CALC_FLAG;
	private String LPP_STOP_FLAG;
	private String DISBURSEMENT_STOP_FLAG;
	private Integer GST_RATE;
	private String GST_CONSTANT;
	private String RULE_OF_78;
	private BigDecimal CPF_INITIAL_WITHDRAWN;
	private String REVOLVING_FLAG;
	private String REDEMPTION_FLAG;
	private String INTEREST_UPFRONT_FLAG;
	private BigDecimal INTEREST_UPFRONT_AMT;
	private String INTEREST_STARTMONTH;
	private Date REPAYMENT_STARTDATE;
	private String TAX_STOP;
	private String NPA_PRO_FLAG;
	private String NPA_PRO_REMARKS;
	private String FINAL_NPA_STAGEID;
	private String NPA_MANUAL_FLAG;
	private Integer NPA_REASON;
	private Date NPA_STAMP_DATE;
	private Date REREGULAR_DATE;
	private String RESCHEDULE_STOP;
	private String NPA_MANUAL_REMARKS;
	private Integer FT_BATCHNUMBER;
	private String LOS_AGREEMENT;
	private Set LEA_REPAYSCH_DTLs = new HashSet(0);

	public LEA_AGREEMENT_DTL() {
	}

	public LEA_AGREEMENT_DTL(int PROPOSALID, String AGREEMENTTYPE, int APPLID,
			BigDecimal ASSETCOST, BigDecimal AMTFIN, short TENURE, String FREQ,
			short NUMINSTL, Date AGREEMENTDATE, String DPERYR,
			String BILL_FLAG, Date DATELASTUPDT, String OVERDUE_PLRTYPE,
			BigDecimal OVERDUE_MARKUP, BigDecimal APP_LOAN_LIMIT,
			byte GRACE_DAYS, BigDecimal GRACE_AMT, String INSTL_FLAG,
			String ADMINFEE_CALC_FLAG) {
		this.PROPOSALID = PROPOSALID;
		this.AGREEMENTTYPE = AGREEMENTTYPE;
		this.APPLID = APPLID;
		this.ASSETCOST = ASSETCOST;
		this.AMTFIN = AMTFIN;
		this.TENURE = TENURE;
		this.FREQ = FREQ;
		this.NUMINSTL = NUMINSTL;
		this.AGREEMENTDATE = AGREEMENTDATE;
		this.DPERYR = DPERYR;
		this.BILL_FLAG = BILL_FLAG;
		this.DATELASTUPDT = DATELASTUPDT;
		this.OVERDUE_PLRTYPE = OVERDUE_PLRTYPE;
		this.OVERDUE_MARKUP = OVERDUE_MARKUP;
		this.APP_LOAN_LIMIT = APP_LOAN_LIMIT;
		this.GRACE_DAYS = GRACE_DAYS;
		this.GRACE_AMT = GRACE_AMT;
		this.INSTL_FLAG = INSTL_FLAG;
		this.ADMINFEE_CALC_FLAG = ADMINFEE_CALC_FLAG;
	}	

	public int getPROPOSALID() {
		return this.PROPOSALID;
	}

	public void setPROPOSALID(int PROPOSALID) {
		this.PROPOSALID = PROPOSALID;
	}

	public Integer getAGREEMENTID() {
		return this.AGREEMENTID;
	}

	public void setAGREEMENTID(Integer AGREEMENTID) {
		this.AGREEMENTID = AGREEMENTID;
	}

	public String getAGREEMENTTYPE() {
		return this.AGREEMENTTYPE;
	}

	public void setAGREEMENTTYPE(String AGREEMENTTYPE) {
		this.AGREEMENTTYPE = AGREEMENTTYPE;
	}

	public String getAGREEMENTNO() {
		return this.AGREEMENTNO;
	}

	public void setAGREEMENTNO(String AGREEMENTNO) {
		this.AGREEMENTNO = AGREEMENTNO;
	}

	public int getAPPLID() {
		return this.APPLID;
	}

	public void setAPPLID(int APPLID) {
		this.APPLID = APPLID;
	}

	public BigDecimal getASSETCOST() {
		return this.ASSETCOST;
	}

	public void setASSETCOST(BigDecimal ASSETCOST) {
		this.ASSETCOST = ASSETCOST;
	}

	public BigDecimal getAMTFIN() {
		return this.AMTFIN;
	}

	public void setAMTFIN(BigDecimal AMTFIN) {
		this.AMTFIN = AMTFIN;
	}

	public BigDecimal getINTRATE() {
		return this.INTRATE;
	}

	public void setINTRATE(BigDecimal INTRATE) {
		this.INTRATE = INTRATE;
	}

	public BigDecimal getEFFRATE() {
		return this.EFFRATE;
	}

	public void setEFFRATE(BigDecimal EFFRATE) {
		this.EFFRATE = EFFRATE;
	}

	public BigDecimal getMARKUP() {
		return this.MARKUP;
	}

	public void setMARKUP(BigDecimal MARKUP) {
		this.MARKUP = MARKUP;
	}

	public String getINTTYPE() {
		return this.INTTYPE;
	}

	public void setINTTYPE(String INTTYPE) {
		this.INTTYPE = INTTYPE;
	}

	public short getTENURE() {
		return this.TENURE;
	}

	public void setTENURE(short TENURE) {
		this.TENURE = TENURE;
	}

	public String getFREQ() {
		return this.FREQ;
	}

	public void setFREQ(String FREQ) {
		this.FREQ = FREQ;
	}

	public short getNUMINSTL() {
		return this.NUMINSTL;
	}

	public void setNUMINSTL(short NUMINSTL) {
		this.NUMINSTL = NUMINSTL;
	}

	public String getINSTALTYPE() {
		return this.INSTALTYPE;
	}

	public void setINSTALTYPE(String INSTALTYPE) {
		this.INSTALTYPE = INSTALTYPE;
	}

	public String getINSTLMODE() {
		return this.INSTLMODE;
	}

	public void setINSTLMODE(String INSTLMODE) {
		this.INSTLMODE = INSTLMODE;
	}

	public Short getADVANCEINSTL() {
		return this.ADVANCEINSTL;
	}

	public void setADVANCEINSTL(Short ADVANCEINSTL) {
		this.ADVANCEINSTL = ADVANCEINSTL;
	}

	public BigDecimal getPRETAXIRR() {
		return this.PRETAXIRR;
	}

	public void setPRETAXIRR(BigDecimal PRETAXIRR) {
		this.PRETAXIRR = PRETAXIRR;
	}

	public BigDecimal getPOSTTAXIRR() {
		return this.POSTTAXIRR;
	}

	public void setPOSTTAXIRR(BigDecimal POSTTAXIRR) {
		this.POSTTAXIRR = POSTTAXIRR;
	}

	public Date getSANCTIONDATE() {
		return this.SANCTIONDATE;
	}

	public void setSANCTIONDATE(Date SANCTIONDATE) {
		this.SANCTIONDATE = SANCTIONDATE;
	}

	public Integer getAUTHID() {
		return this.AUTHID;
	}

	public void setAUTHID(Integer AUTHID) {
		this.AUTHID = AUTHID;
	}

	public Integer getSTATEID() {
		return this.STATEID;
	}

	public void setSTATEID(Integer STATEID) {
		this.STATEID = STATEID;
	}

	public Integer getCATGID() {
		return this.CATGID;
	}

	public void setCATGID(Integer CATGID) {
		this.CATGID = CATGID;
	}

	public BigDecimal getTAXRATE() {
		return this.TAXRATE;
	}

	public void setTAXRATE(BigDecimal TAXRATE) {
		this.TAXRATE = TAXRATE;
	}

	public BigDecimal getBOUNCECHEQUEFEE() {
		return this.BOUNCECHEQUEFEE;
	}

	public void setBOUNCECHEQUEFEE(BigDecimal BOUNCECHEQUEFEE) {
		this.BOUNCECHEQUEFEE = BOUNCECHEQUEFEE;
	}

	public BigDecimal getBROKERAGERATE() {
		return this.BROKERAGERATE;
	}

	public void setBROKERAGERATE(BigDecimal BROKERAGERATE) {
		this.BROKERAGERATE = BROKERAGERATE;
	}

	public BigDecimal getMGMTFEERATE() {
		return this.MGMTFEERATE;
	}

	public void setMGMTFEERATE(BigDecimal MGMTFEERATE) {
		this.MGMTFEERATE = MGMTFEERATE;
	}

	public BigDecimal getRVRATE() {
		return this.RVRATE;
	}

	public void setRVRATE(BigDecimal RVRATE) {
		this.RVRATE = RVRATE;
	}

	public BigDecimal getSDRATE() {
		return this.SDRATE;
	}

	public void setSDRATE(BigDecimal SDRATE) {
		this.SDRATE = SDRATE;
	}

	public BigDecimal getOVERDUERATE() {
		return this.OVERDUERATE;
	}

	public void setOVERDUERATE(BigDecimal OVERDUERATE) {
		this.OVERDUERATE = OVERDUERATE;
	}

	public Date getAGREEMENTDATE() {
		return this.AGREEMENTDATE;
	}

	public void setAGREEMENTDATE(Date AGREEMENTDATE) {
		this.AGREEMENTDATE = AGREEMENTDATE;
	}

	public Date getCOMMENCEDATE() {
		return this.COMMENCEDATE;
	}

	public void setCOMMENCEDATE(Date COMMENCEDATE) {
		this.COMMENCEDATE = COMMENCEDATE;
	}

	public Date getCLOSUREDATE() {
		return this.CLOSUREDATE;
	}

	public void setCLOSUREDATE(Date CLOSUREDATE) {
		this.CLOSUREDATE = CLOSUREDATE;
	}

	public Date getRESCHEDULEDATE() {
		return this.RESCHEDULEDATE;
	}

	public void setRESCHEDULEDATE(Date RESCHEDULEDATE) {
		this.RESCHEDULEDATE = RESCHEDULEDATE;
	}

	public String getSTATUS() {
		return this.STATUS;
	}

	public void setSTATUS(String STATUS) {
		this.STATUS = STATUS;
	}

	public BigDecimal getSPOTINTRATE() {
		return this.SPOTINTRATE;
	}

	public void setSPOTINTRATE(BigDecimal SPOTINTRATE) {
		this.SPOTINTRATE = SPOTINTRATE;
	}

	public Integer getSCHEMEID() {
		return this.SCHEMEID;
	}

	public void setSCHEMEID(Integer SCHEMEID) {
		this.SCHEMEID = SCHEMEID;
	}

	public BigDecimal getMARGINMONEY() {
		return this.MARGINMONEY;
	}

	public void setMARGINMONEY(BigDecimal MARGINMONEY) {
		this.MARGINMONEY = MARGINMONEY;
	}

	public Date getPROPOSALCRDATE() {
		return this.PROPOSALCRDATE;
	}

	public void setPROPOSALCRDATE(Date PROPOSALCRDATE) {
		this.PROPOSALCRDATE = PROPOSALCRDATE;
	}

	public String getPROPOSALCRBY() {
		return this.PROPOSALCRBY;
	}

	public void setPROPOSALCRBY(String PROPOSALCRBY) {
		this.PROPOSALCRBY = PROPOSALCRBY;
	}

	public Date getAGREEMENTCRDATE() {
		return this.AGREEMENTCRDATE;
	}

	public void setAGREEMENTCRDATE(Date AGREEMENTCRDATE) {
		this.AGREEMENTCRDATE = AGREEMENTCRDATE;
	}

	public String getAGREEMENTCRBY() {
		return this.AGREEMENTCRBY;
	}

	public void setAGREEMENTCRBY(String AGREEMENTCRBY) {
		this.AGREEMENTCRBY = AGREEMENTCRBY;
	}

	public Date getPROPOSALMODDATE() {
		return this.PROPOSALMODDATE;
	}

	public void setPROPOSALMODDATE(Date PROPOSALMODDATE) {
		this.PROPOSALMODDATE = PROPOSALMODDATE;
	}

	public String getPROPOSALMODBY() {
		return this.PROPOSALMODBY;
	}

	public void setPROPOSALMODBY(String PROPOSALMODBY) {
		this.PROPOSALMODBY = PROPOSALMODBY;
	}

	public Date getCREDITAUTHDATE() {
		return this.CREDITAUTHDATE;
	}

	public void setCREDITAUTHDATE(Date CREDITAUTHDATE) {
		this.CREDITAUTHDATE = CREDITAUTHDATE;
	}

	public String getCREDITAUTHBY() {
		return this.CREDITAUTHBY;
	}

	public void setCREDITAUTHBY(String CREDITAUTHBY) {
		this.CREDITAUTHBY = CREDITAUTHBY;
	}

	public Date getPRDDOCAUTHDATE() {
		return this.PRDDOCAUTHDATE;
	}

	public void setPRDDOCAUTHDATE(Date PRDDOCAUTHDATE) {
		this.PRDDOCAUTHDATE = PRDDOCAUTHDATE;
	}

	public String getPRDDOCAUTHBY() {
		return this.PRDDOCAUTHBY;
	}

	public void setPRDDOCAUTHBY(String PRDDOCAUTHBY) {
		this.PRDDOCAUTHBY = PRDDOCAUTHBY;
	}

	public Date getPODDOCAUTHDATE() {
		return this.PODDOCAUTHDATE;
	}

	public void setPODDOCAUTHDATE(Date PODDOCAUTHDATE) {
		this.PODDOCAUTHDATE = PODDOCAUTHDATE;
	}

	public String getPODDOCAUTHBY() {
		return this.PODDOCAUTHBY;
	}

	public void setPODDOCAUTHBY(String PODDOCAUTHBY) {
		this.PODDOCAUTHBY = PODDOCAUTHBY;
	}

	public String getCREDITAUTHREQD() {
		return this.CREDITAUTHREQD;
	}

	public void setCREDITAUTHREQD(String CREDITAUTHREQD) {
		this.CREDITAUTHREQD = CREDITAUTHREQD;
	}

	public String getPRDAUTHREQD() {
		return this.PRDAUTHREQD;
	}

	public void setPRDAUTHREQD(String PRDAUTHREQD) {
		this.PRDAUTHREQD = PRDAUTHREQD;
	}

	public String getPODAUTHREQD() {
		return this.PODAUTHREQD;
	}

	public void setPODAUTHREQD(String PODAUTHREQD) {
		this.PODAUTHREQD = PODAUTHREQD;
	}

	public Integer getLESSEEID() {
		return this.LESSEEID;
	}

	public void setLESSEEID(Integer LESSEEID) {
		this.LESSEEID = LESSEEID;
	}

	public String getACTION() {
		return this.ACTION;
	}

	public void setACTION(String ACTION) {
		this.ACTION = ACTION;
	}

	public Date getACTIONDATE() {
		return this.ACTIONDATE;
	}

	public void setACTIONDATE(Date ACTIONDATE) {
		this.ACTIONDATE = ACTIONDATE;
	}

	public String getPRINT_FLAG() {
		return this.PRINT_FLAG;
	}

	public void setPRINT_FLAG(String PRINT_FLAG) {
		this.PRINT_FLAG = PRINT_FLAG;
	}

	public String getDUEDAY() {
		return this.DUEDAY;
	}

	public void setDUEDAY(String DUEDAY) {
		this.DUEDAY = DUEDAY;
	}

	public String getCREDITAUTHREQD_S() {
		return this.CREDITAUTHREQD_S;
	}

	public void setCREDITAUTHREQD_S(String CREDITAUTHREQD_S) {
		this.CREDITAUTHREQD_S = CREDITAUTHREQD_S;
	}

	public Date getCREDITAUTHDATE_S() {
		return this.CREDITAUTHDATE_S;
	}

	public void setCREDITAUTHDATE_S(Date CREDITAUTHDATE_S) {
		this.CREDITAUTHDATE_S = CREDITAUTHDATE_S;
	}

	public String getCREDITAUTHBY_S() {
		return this.CREDITAUTHBY_S;
	}

	public void setCREDITAUTHBY_S(String CREDITAUTHBY_S) {
		this.CREDITAUTHBY_S = CREDITAUTHBY_S;
	}

	public String getCREDITAUTHREQD_O() {
		return this.CREDITAUTHREQD_O;
	}

	public void setCREDITAUTHREQD_O(String CREDITAUTHREQD_O) {
		this.CREDITAUTHREQD_O = CREDITAUTHREQD_O;
	}

	public Date getCREDITAUTHDATE_O() {
		return this.CREDITAUTHDATE_O;
	}

	public void setCREDITAUTHDATE_O(Date CREDITAUTHDATE_O) {
		this.CREDITAUTHDATE_O = CREDITAUTHDATE_O;
	}

	public String getCREDITAUTHBY_O() {
		return this.CREDITAUTHBY_O;
	}

	public void setCREDITAUTHBY_O(String CREDITAUTHBY_O) {
		this.CREDITAUTHBY_O = CREDITAUTHBY_O;
	}

	public BigDecimal getAMTOTHERS() {
		return this.AMTOTHERS;
	}

	public void setAMTOTHERS(BigDecimal AMTOTHERS) {
		this.AMTOTHERS = AMTOTHERS;
	}

	public BigDecimal getREBATE() {
		return this.REBATE;
	}

	public void setREBATE(BigDecimal REBATE) {
		this.REBATE = REBATE;
	}

	public BigDecimal getPENALTY() {
		return this.PENALTY;
	}

	public void setPENALTY(BigDecimal PENALTY) {
		this.PENALTY = PENALTY;
	}

	public String getACCRUAL_FLAG() {
		return this.ACCRUAL_FLAG;
	}

	public void setACCRUAL_FLAG(String ACCRUAL_FLAG) {
		this.ACCRUAL_FLAG = ACCRUAL_FLAG;
	}

	public String getCURRENCYID() {
		return this.CURRENCYID;
	}

	public void setCURRENCYID(String CURRENCYID) {
		this.CURRENCYID = CURRENCYID;
	}

	public String getPRININTCAL() {
		return this.PRININTCAL;
	}

	public void setPRININTCAL(String PRININTCAL) {
		this.PRININTCAL = PRININTCAL;
	}

	public String getDEANNUALIZE() {
		return this.DEANNUALIZE;
	}

	public void setDEANNUALIZE(String DEANNUALIZE) {
		this.DEANNUALIZE = DEANNUALIZE;
	}

	public Integer getBRANCHID() {
		return this.BRANCHID;
	}

	public void setBRANCHID(Integer BRANCHID) {
		this.BRANCHID = BRANCHID;
	}

	public Date getAPPDATE() {
		return this.APPDATE;
	}

	public void setAPPDATE(Date APPDATE) {
		this.APPDATE = APPDATE;
	}

	public BigDecimal getEMI() {
		return this.EMI;
	}

	public void setEMI(BigDecimal EMI) {
		this.EMI = EMI;
	}

	public BigDecimal getRESVALUE() {
		return this.RESVALUE;
	}

	public void setRESVALUE(BigDecimal RESVALUE) {
		this.RESVALUE = RESVALUE;
	}

	public BigDecimal getACCESSAMT() {
		return this.ACCESSAMT;
	}

	public void setACCESSAMT(BigDecimal ACCESSAMT) {
		this.ACCESSAMT = ACCESSAMT;
	}

	public BigDecimal getPREPAYPENALTY() {
		return this.PREPAYPENALTY;
	}

	public void setPREPAYPENALTY(BigDecimal PREPAYPENALTY) {
		this.PREPAYPENALTY = PREPAYPENALTY;
	}

	public BigDecimal getMARGINRATE() {
		return this.MARGINRATE;
	}

	public void setMARGINRATE(BigDecimal MARGINRATE) {
		this.MARGINRATE = MARGINRATE;
	}

	public String getFINALSOURCE() {
		return this.FINALSOURCE;
	}

	public void setFINALSOURCE(String FINALSOURCE) {
		this.FINALSOURCE = FINALSOURCE;
	}

	public String getFINALSOURCEID() {
		return this.FINALSOURCEID;
	}

	public void setFINALSOURCEID(String FINALSOURCEID) {
		this.FINALSOURCEID = FINALSOURCEID;
	}

	public String getFIRSTSOURCE() {
		return this.FIRSTSOURCE;
	}

	public void setFIRSTSOURCE(String FIRSTSOURCE) {
		this.FIRSTSOURCE = FIRSTSOURCE;
	}

	public String getFIRSTSOURCEID() {
		return this.FIRSTSOURCEID;
	}

	public void setFIRSTSOURCEID(String FIRSTSOURCEID) {
		this.FIRSTSOURCEID = FIRSTSOURCEID;
	}

	public String getPROMOTIONSCHEME() {
		return this.PROMOTIONSCHEME;
	}

	public void setPROMOTIONSCHEME(String PROMOTIONSCHEME) {
		this.PROMOTIONSCHEME = PROMOTIONSCHEME;
	}

	public String getLOAN_IN_NAME() {
		return this.LOAN_IN_NAME;
	}

	public void setLOAN_IN_NAME(String LOAN_IN_NAME) {
		this.LOAN_IN_NAME = LOAN_IN_NAME;
	}

	public Integer getSUPPLIERID() {
		return this.SUPPLIERID;
	}

	public void setSUPPLIERID(Integer SUPPLIERID) {
		this.SUPPLIERID = SUPPLIERID;
	}

	public String getDPERYR() {
		return this.DPERYR;
	}

	public void setDPERYR(String DPERYR) {
		this.DPERYR = DPERYR;
	}

	public Date getDISBURSALDATE() {
		return this.DISBURSALDATE;
	}

	public void setDISBURSALDATE(Date DISBURSALDATE) {
		this.DISBURSALDATE = DISBURSALDATE;
	}

	public Byte getFORECLOSELOCKLN() {
		return this.FORECLOSELOCKLN;
	}

	public void setFORECLOSELOCKLN(Byte FORECLOSELOCKLN) {
		this.FORECLOSELOCKLN = FORECLOSELOCKLN;
	}

	public String getPRODUCTFLAG() {
		return this.PRODUCTFLAG;
	}

	public void setPRODUCTFLAG(String PRODUCTFLAG) {
		this.PRODUCTFLAG = PRODUCTFLAG;
	}

	public String getPDCFLAG() {
		return this.PDCFLAG;
	}

	public void setPDCFLAG(String PDCFLAG) {
		this.PDCFLAG = PDCFLAG;
	}

	public Boolean getDECIMALS() {
		return this.DECIMALS;
	}

	public void setDECIMALS(Boolean DECIMALS) {
		this.DECIMALS = DECIMALS;
	}

	public String getRS_CONFIRM() {
		return this.RS_CONFIRM;
	}

	public void setRS_CONFIRM(String RS_CONFIRM) {
		this.RS_CONFIRM = RS_CONFIRM;
	}

	public BigDecimal getGRACEPERIOD() {
		return this.GRACEPERIOD;
	}

	public void setGRACEPERIOD(BigDecimal GRACEPERIOD) {
		this.GRACEPERIOD = GRACEPERIOD;
	}

	public Date getLEA_LAST_ACR_DATE() {
		return this.LEA_LAST_ACR_DATE;
	}

	public void setLEA_LAST_ACR_DATE(Date LEA_LAST_ACR_DATE) {
		this.LEA_LAST_ACR_DATE = LEA_LAST_ACR_DATE;
	}

	public Date getLEA_NON_ACR_FLAG() {
		return this.LEA_NON_ACR_FLAG;
	}

	public void setLEA_NON_ACR_FLAG(Date LEA_NON_ACR_FLAG) {
		this.LEA_NON_ACR_FLAG = LEA_NON_ACR_FLAG;
	}

	public BigDecimal getLEA_ACR_INT_AMT() {
		return this.LEA_ACR_INT_AMT;
	}

	public void setLEA_ACR_INT_AMT(BigDecimal LEA_ACR_INT_AMT) {
		this.LEA_ACR_INT_AMT = LEA_ACR_INT_AMT;
	}

	public Integer getBATCHNUMBER() {
		return this.BATCHNUMBER;
	}

	public void setBATCHNUMBER(Integer BATCHNUMBER) {
		this.BATCHNUMBER = BATCHNUMBER;
	}

	public BigDecimal getACCOUNTING_MONTHLY_IRR() {
		return this.ACCOUNTING_MONTHLY_IRR;
	}

	public void setACCOUNTING_MONTHLY_IRR(BigDecimal ACCOUNTING_MONTHLY_IRR) {
		this.ACCOUNTING_MONTHLY_IRR = ACCOUNTING_MONTHLY_IRR;
	}

	public BigDecimal getLEA_MONTHLY_IRR() {
		return this.LEA_MONTHLY_IRR;
	}

	public void setLEA_MONTHLY_IRR(BigDecimal LEA_MONTHLY_IRR) {
		this.LEA_MONTHLY_IRR = LEA_MONTHLY_IRR;
	}

	public BigDecimal getMARGIN_MONEY_2() {
		return this.MARGIN_MONEY_2;
	}

	public void setMARGIN_MONEY_2(BigDecimal MARGIN_MONEY_2) {
		this.MARGIN_MONEY_2 = MARGIN_MONEY_2;
	}

	public String getNOTEPAD() {
		return this.NOTEPAD;
	}

	public void setNOTEPAD(String NOTEPAD) {
		this.NOTEPAD = NOTEPAD;
	}

	public BigDecimal getVAT_PRIN_RATE() {
		return this.VAT_PRIN_RATE;
	}

	public void setVAT_PRIN_RATE(BigDecimal VAT_PRIN_RATE) {
		this.VAT_PRIN_RATE = VAT_PRIN_RATE;
	}

	public BigDecimal getVAT_INT_RATE() {
		return this.VAT_INT_RATE;
	}

	public void setVAT_INT_RATE(BigDecimal VAT_INT_RATE) {
		this.VAT_INT_RATE = VAT_INT_RATE;
	}

	public Integer getCRSCORE() {
		return this.CRSCORE;
	}

	public void setCRSCORE(Integer CRSCORE) {
		this.CRSCORE = CRSCORE;
	}

	public Short getAGE() {
		return this.AGE;
	}

	public void setAGE(Short AGE) {
		this.AGE = AGE;
	}

	public Short getMATURITY_AGE() {
		return this.MATURITY_AGE;
	}

	public void setMATURITY_AGE(Short MATURITY_AGE) {
		this.MATURITY_AGE = MATURITY_AGE;
	}

	public String getNPA_STAGEID() {
		return this.NPA_STAGEID;
	}

	public void setNPA_STAGEID(String NPA_STAGEID) {
		this.NPA_STAGEID = NPA_STAGEID;
	}

	public String getBILL_FLAG() {
		return this.BILL_FLAG;
	}

	public void setBILL_FLAG(String BILL_FLAG) {
		this.BILL_FLAG = BILL_FLAG;
	}

	public Date getLAST_LPI_DATE() {
		return this.LAST_LPI_DATE;
	}

	public void setLAST_LPI_DATE(Date LAST_LPI_DATE) {
		this.LAST_LPI_DATE = LAST_LPI_DATE;
	}

	public Date getNPA_DATE() {
		return this.NPA_DATE;
	}

	public void setNPA_DATE(Date NPA_DATE) {
		this.NPA_DATE = NPA_DATE;
	}

	public Integer getDPD() {
		return this.DPD;
	}

	public void setDPD(Integer DPD) {
		this.DPD = DPD;
	}

	public String getDPD_STRING() {
		return this.DPD_STRING;
	}

	public void setDPD_STRING(String DPD_STRING) {
		this.DPD_STRING = DPD_STRING;
	}

	public Date getDATELASTUPDT() {
		return this.DATELASTUPDT;
	}

	public void setDATELASTUPDT(Date DATELASTUPDT) {
		this.DATELASTUPDT = DATELASTUPDT;
	}

	public BigDecimal getDISBURSEDAMOUNT() {
		return this.DISBURSEDAMOUNT;
	}

	public void setDISBURSEDAMOUNT(BigDecimal DISBURSEDAMOUNT) {
		this.DISBURSEDAMOUNT = DISBURSEDAMOUNT;
	}

	public BigDecimal getFINANCECHARGE() {
		return this.FINANCECHARGE;
	}

	public void setFINANCECHARGE(BigDecimal FINANCECHARGE) {
		this.FINANCECHARGE = FINANCECHARGE;
	}

	public BigDecimal getBENEFITAMOUNT() {
		return this.BENEFITAMOUNT;
	}

	public void setBENEFITAMOUNT(BigDecimal BENEFITAMOUNT) {
		this.BENEFITAMOUNT = BENEFITAMOUNT;
	}

	public String getDISBURSALTO() {
		return this.DISBURSALTO;
	}

	public void setDISBURSALTO(String DISBURSALTO) {
		this.DISBURSALTO = DISBURSALTO;
	}

	public Integer getMKTGID() {
		return this.MKTGID;
	}

	public void setMKTGID(Integer MKTGID) {
		this.MKTGID = MKTGID;
	}

	public Integer getBROKERID() {
		return this.BROKERID;
	}

	public void setBROKERID(Integer BROKERID) {
		this.BROKERID = BROKERID;
	}

	public Integer getREFAGREEMENTID() {
		return this.REFAGREEMENTID;
	}

	public void setREFAGREEMENTID(Integer REFAGREEMENTID) {
		this.REFAGREEMENTID = REFAGREEMENTID;
	}

	public BigDecimal getADVDISBINTRATE() {
		return this.ADVDISBINTRATE;
	}

	public void setADVDISBINTRATE(BigDecimal ADVDISBINTRATE) {
		this.ADVDISBINTRATE = ADVDISBINTRATE;
	}

	public BigDecimal getVAT_INSTL_RATE() {
		return this.VAT_INSTL_RATE;
	}

	public void setVAT_INSTL_RATE(BigDecimal VAT_INSTL_RATE) {
		this.VAT_INSTL_RATE = VAT_INSTL_RATE;
	}

	public BigDecimal getVAT_INPUT() {
		return this.VAT_INPUT;
	}

	public void setVAT_INPUT(BigDecimal VAT_INPUT) {
		this.VAT_INPUT = VAT_INPUT;
	}

	public Date getDPD_STRING_STAMPDATE() {
		return this.DPD_STRING_STAMPDATE;
	}

	public void setDPD_STRING_STAMPDATE(Date DPD_STRING_STAMPDATE) {
		this.DPD_STRING_STAMPDATE = DPD_STRING_STAMPDATE;
	}

	public Short getBUCKET() {
		return this.BUCKET;
	}

	public void setBUCKET(Short BUCKET) {
		this.BUCKET = BUCKET;
	}

	public Byte getCURRSEQNO() {
		return this.CURRSEQNO;
	}

	public void setCURRSEQNO(Byte CURRSEQNO) {
		this.CURRSEQNO = CURRSEQNO;
	}

	public String getGRACE_INTEREST_CHARGE() {
		return this.GRACE_INTEREST_CHARGE;
	}

	public void setGRACE_INTEREST_CHARGE(String GRACE_INTEREST_CHARGE) {
		this.GRACE_INTEREST_CHARGE = GRACE_INTEREST_CHARGE;
	}

	public String getGRACE_ADJUST_SCHEDULE() {
		return this.GRACE_ADJUST_SCHEDULE;
	}

	public void setGRACE_ADJUST_SCHEDULE(String GRACE_ADJUST_SCHEDULE) {
		this.GRACE_ADJUST_SCHEDULE = GRACE_ADJUST_SCHEDULE;
	}

	public Integer getSANCTIONID() {
		return this.SANCTIONID;
	}

	public void setSANCTIONID(Integer SANCTIONID) {
		this.SANCTIONID = SANCTIONID;
	}

	public String getAUTCLOS_FLAG() {
		return this.AUTCLOS_FLAG;
	}

	public void setAUTCLOS_FLAG(String AUTCLOS_FLAG) {
		this.AUTCLOS_FLAG = AUTCLOS_FLAG;
	}

	public String getMANUAL_NPA_MOVEMENT_FLAG() {
		return this.MANUAL_NPA_MOVEMENT_FLAG;
	}

	public void setMANUAL_NPA_MOVEMENT_FLAG(String MANUAL_NPA_MOVEMENT_FLAG) {
		this.MANUAL_NPA_MOVEMENT_FLAG = MANUAL_NPA_MOVEMENT_FLAG;
	}

	public String getDISB_TYPE() {
		return this.DISB_TYPE;
	}

	public void setDISB_TYPE(String DISB_TYPE) {
		this.DISB_TYPE = DISB_TYPE;
	}

	public Short getNO_DISBURSAL() {
		return this.NO_DISBURSAL;
	}

	public void setNO_DISBURSAL(Short NO_DISBURSAL) {
		this.NO_DISBURSAL = NO_DISBURSAL;
	}

	public BigDecimal getPEMI_RATE() {
		return this.PEMI_RATE;
	}

	public void setPEMI_RATE(BigDecimal PEMI_RATE) {
		this.PEMI_RATE = PEMI_RATE;
	}

	public BigDecimal getINTTAXRATE() {
		return this.INTTAXRATE;
	}

	public void setINTTAXRATE(BigDecimal INTTAXRATE) {
		this.INTTAXRATE = INTTAXRATE;
	}

	public BigDecimal getTDSRATE() {
		return this.TDSRATE;
	}

	public void setTDSRATE(BigDecimal TDSRATE) {
		this.TDSRATE = TDSRATE;
	}

	public BigDecimal getLPIRATE() {
		return this.LPIRATE;
	}

	public void setLPIRATE(BigDecimal LPIRATE) {
		this.LPIRATE = LPIRATE;
	}

	public String getFLOATINGFLG() {
		return this.FLOATINGFLG;
	}

	public void setFLOATINGFLG(String FLOATINGFLG) {
		this.FLOATINGFLG = FLOATINGFLG;
	}

	public String getPLRTYPE() {
		return this.PLRTYPE;
	}

	public void setPLRTYPE(String PLRTYPE) {
		this.PLRTYPE = PLRTYPE;
	}

	public String getTAXAPPLICABLE() {
		return this.TAXAPPLICABLE;
	}

	public void setTAXAPPLICABLE(String TAXAPPLICABLE) {
		this.TAXAPPLICABLE = TAXAPPLICABLE;
	}

	public String getBALANCE_TRANSFER() {
		return this.BALANCE_TRANSFER;
	}

	public void setBALANCE_TRANSFER(String BALANCE_TRANSFER) {
		this.BALANCE_TRANSFER = BALANCE_TRANSFER;
	}

	public BigDecimal getRELATIONAL_DISCOUNT() {
		return this.RELATIONAL_DISCOUNT;
	}

	public void setRELATIONAL_DISCOUNT(BigDecimal RELATIONAL_DISCOUNT) {
		this.RELATIONAL_DISCOUNT = RELATIONAL_DISCOUNT;
	}

	public BigDecimal getOTHER_DISCOUNT() {
		return this.OTHER_DISCOUNT;
	}

	public void setOTHER_DISCOUNT(BigDecimal OTHER_DISCOUNT) {
		this.OTHER_DISCOUNT = OTHER_DISCOUNT;
	}

	public String getCO_APPL_REQ() {
		return this.CO_APPL_REQ;
	}

	public void setCO_APPL_REQ(String CO_APPL_REQ) {
		this.CO_APPL_REQ = CO_APPL_REQ;
	}

	public String getGUARANTOR_REQ() {
		return this.GUARANTOR_REQ;
	}

	public void setGUARANTOR_REQ(String GUARANTOR_REQ) {
		this.GUARANTOR_REQ = GUARANTOR_REQ;
	}

	public String getSEC_DEPOSIT_REQ() {
		return this.SEC_DEPOSIT_REQ;
	}

	public void setSEC_DEPOSIT_REQ(String SEC_DEPOSIT_REQ) {
		this.SEC_DEPOSIT_REQ = SEC_DEPOSIT_REQ;
	}

	public String getFORECLOSE_ALLOWED() {
		return this.FORECLOSE_ALLOWED;
	}

	public void setFORECLOSE_ALLOWED(String FORECLOSE_ALLOWED) {
		this.FORECLOSE_ALLOWED = FORECLOSE_ALLOWED;
	}

	public BigDecimal getFORECLOSE_PENALTY() {
		return this.FORECLOSE_PENALTY;
	}

	public void setFORECLOSE_PENALTY(BigDecimal FORECLOSE_PENALTY) {
		this.FORECLOSE_PENALTY = FORECLOSE_PENALTY;
	}

	public Short getFORECLOSE_LOCK_PERIOD() {
		return this.FORECLOSE_LOCK_PERIOD;
	}

	public void setFORECLOSE_LOCK_PERIOD(Short FORECLOSE_LOCK_PERIOD) {
		this.FORECLOSE_LOCK_PERIOD = FORECLOSE_LOCK_PERIOD;
	}

	public Long getATMCODE() {
		return this.ATMCODE;
	}

	public void setATMCODE(Long ATMCODE) {
		this.ATMCODE = ATMCODE;
	}

	public BigDecimal getRATE() {
		return this.RATE;
	}

	public void setRATE(BigDecimal RATE) {
		this.RATE = RATE;
	}

	public BigDecimal getFEERATE() {
		return this.FEERATE;
	}

	public void setFEERATE(BigDecimal FEERATE) {
		this.FEERATE = FEERATE;
	}

	public BigDecimal getCOSTOFFUNDS() {
		return this.COSTOFFUNDS;
	}

	public void setCOSTOFFUNDS(BigDecimal COSTOFFUNDS) {
		this.COSTOFFUNDS = COSTOFFUNDS;
	}

	public BigDecimal getLOSS() {
		return this.LOSS;
	}

	public void setLOSS(BigDecimal LOSS) {
		this.LOSS = LOSS;
	}

	public BigDecimal getEXPENSES() {
		return this.EXPENSES;
	}

	public void setEXPENSES(BigDecimal EXPENSES) {
		this.EXPENSES = EXPENSES;
	}

	public BigDecimal getCUSTOMERYIELD() {
		return this.CUSTOMERYIELD;
	}

	public void setCUSTOMERYIELD(BigDecimal CUSTOMERYIELD) {
		this.CUSTOMERYIELD = CUSTOMERYIELD;
	}

	public BigDecimal getPRETAXROI() {
		return this.PRETAXROI;
	}

	public void setPRETAXROI(BigDecimal PRETAXROI) {
		this.PRETAXROI = PRETAXROI;
	}

	public BigDecimal getROI() {
		return this.ROI;
	}

	public void setROI(BigDecimal ROI) {
		this.ROI = ROI;
	}

	public BigDecimal getTAX() {
		return this.TAX;
	}

	public void setTAX(BigDecimal TAX) {
		this.TAX = TAX;
	}

	public BigDecimal getTAX_PERCENTAGE() {
		return this.TAX_PERCENTAGE;
	}

	public void setTAX_PERCENTAGE(BigDecimal TAX_PERCENTAGE) {
		this.TAX_PERCENTAGE = TAX_PERCENTAGE;
	}

	public BigDecimal getSECURITYCOVER() {
		return this.SECURITYCOVER;
	}

	public void setSECURITYCOVER(BigDecimal SECURITYCOVER) {
		this.SECURITYCOVER = SECURITYCOVER;
	}

	public BigDecimal getSECURITYTAKEN() {
		return this.SECURITYTAKEN;
	}

	public void setSECURITYTAKEN(BigDecimal SECURITYTAKEN) {
		this.SECURITYTAKEN = SECURITYTAKEN;
	}

	public String getCROSS_COLLATERAL() {
		return this.CROSS_COLLATERAL;
	}

	public void setCROSS_COLLATERAL(String CROSS_COLLATERAL) {
		this.CROSS_COLLATERAL = CROSS_COLLATERAL;
	}

	public Integer getBILLNO() {
		return this.BILLNO;
	}

	public void setBILLNO(Integer BILLNO) {
		this.BILLNO = BILLNO;
	}

	public String getRELATIONSHIP_DISC() {
		return this.RELATIONSHIP_DISC;
	}

	public void setRELATIONSHIP_DISC(String RELATIONSHIP_DISC) {
		this.RELATIONSHIP_DISC = RELATIONSHIP_DISC;
	}

	public String getPROFESSIONAL_DISC() {
		return this.PROFESSIONAL_DISC;
	}

	public void setPROFESSIONAL_DISC(String PROFESSIONAL_DISC) {
		this.PROFESSIONAL_DISC = PROFESSIONAL_DISC;
	}

	public String getPREPAY_ALLOWED() {
		return this.PREPAY_ALLOWED;
	}

	public void setPREPAY_ALLOWED(String PREPAY_ALLOWED) {
		this.PREPAY_ALLOWED = PREPAY_ALLOWED;
	}

	public String getPREPAY_PENALTY() {
		return this.PREPAY_PENALTY;
	}

	public void setPREPAY_PENALTY(String PREPAY_PENALTY) {
		this.PREPAY_PENALTY = PREPAY_PENALTY;
	}

	public Short getPREPAY_LOCK_PERIOD() {
		return this.PREPAY_LOCK_PERIOD;
	}

	public void setPREPAY_LOCK_PERIOD(Short PREPAY_LOCK_PERIOD) {
		this.PREPAY_LOCK_PERIOD = PREPAY_LOCK_PERIOD;
	}

	public String getFORECLOSURE_PENALTY() {
		return this.FORECLOSURE_PENALTY;
	}

	public void setFORECLOSURE_PENALTY(String FORECLOSURE_PENALTY) {
		this.FORECLOSURE_PENALTY = FORECLOSURE_PENALTY;
	}

	public Integer getDSSNO() {
		return this.DSSNO;
	}

	public void setDSSNO(Integer DSSNO) {
		this.DSSNO = DSSNO;
	}

	public Date getMATURITYDATE() {
		return this.MATURITYDATE;
	}

	public void setMATURITYDATE(Date MATURITYDATE) {
		this.MATURITYDATE = MATURITYDATE;
	}

	public String getDEL_MONTHLY_STRING() {
		return this.DEL_MONTHLY_STRING;
	}

	public void setDEL_MONTHLY_STRING(String DEL_MONTHLY_STRING) {
		this.DEL_MONTHLY_STRING = DEL_MONTHLY_STRING;
	}

	public BigDecimal getMATURITYAMT() {
		return this.MATURITYAMT;
	}

	public void setMATURITYAMT(BigDecimal MATURITYAMT) {
		this.MATURITYAMT = MATURITYAMT;
	}

	public String getTENURETYPE() {
		return this.TENURETYPE;
	}

	public void setTENURETYPE(String TENURETYPE) {
		this.TENURETYPE = TENURETYPE;
	}

	public String getLPITYPE() {
		return this.LPITYPE;
	}

	public void setLPITYPE(String LPITYPE) {
		this.LPITYPE = LPITYPE;
	}

	public Short getACTUAL_MONTHS() {
		return this.ACTUAL_MONTHS;
	}

	public void setACTUAL_MONTHS(Short ACTUAL_MONTHS) {
		this.ACTUAL_MONTHS = ACTUAL_MONTHS;
	}

	public Short getACTUAL_DAYS() {
		return this.ACTUAL_DAYS;
	}

	public void setACTUAL_DAYS(Short ACTUAL_DAYS) {
		this.ACTUAL_DAYS = ACTUAL_DAYS;
	}

	public String getMATCH_FOUND() {
		return this.MATCH_FOUND;
	}

	public void setMATCH_FOUND(String MATCH_FOUND) {
		this.MATCH_FOUND = MATCH_FOUND;
	}

	public String getDEDUPE_RESULT() {
		return this.DEDUPE_RESULT;
	}

	public void setDEDUPE_RESULT(String DEDUPE_RESULT) {
		this.DEDUPE_RESULT = DEDUPE_RESULT;
	}

	public Integer getEMPLOYERID() {
		return this.EMPLOYERID;
	}

	public void setEMPLOYERID(Integer EMPLOYERID) {
		this.EMPLOYERID = EMPLOYERID;
	}

	public Date getREPAYMENT_EFFECTIVE_DATE() {
		return this.REPAYMENT_EFFECTIVE_DATE;
	}

	public void setREPAYMENT_EFFECTIVE_DATE(Date REPAYMENT_EFFECTIVE_DATE) {
		this.REPAYMENT_EFFECTIVE_DATE = REPAYMENT_EFFECTIVE_DATE;
	}

	public BigDecimal getOUTSTANDINGPRINPRECENT() {
		return this.OUTSTANDINGPRINPRECENT;
	}

	public void setOUTSTANDINGPRINPRECENT(BigDecimal OUTSTANDINGPRINPRECENT) {
		this.OUTSTANDINGPRINPRECENT = OUTSTANDINGPRINPRECENT;
	}

	public BigDecimal getMIN_PENALAMOUNT() {
		return this.MIN_PENALAMOUNT;
	}

	public void setMIN_PENALAMOUNT(BigDecimal MIN_PENALAMOUNT) {
		this.MIN_PENALAMOUNT = MIN_PENALAMOUNT;
	}

	public String getEMP_FLAG() {
		return this.EMP_FLAG;
	}

	public void setEMP_FLAG(String EMP_FLAG) {
		this.EMP_FLAG = EMP_FLAG;
	}

	public BigDecimal getPLRRATE() {
		return this.PLRRATE;
	}

	public void setPLRRATE(BigDecimal PLRRATE) {
		this.PLRRATE = PLRRATE;
	}

	public Integer getINSURCOID() {
		return this.INSURCOID;
	}

	public void setINSURCOID(Integer INSURCOID) {
		this.INSURCOID = INSURCOID;
	}

	public Integer getINSUR_PRODUCTID() {
		return this.INSUR_PRODUCTID;
	}

	public void setINSUR_PRODUCTID(Integer INSUR_PRODUCTID) {
		this.INSUR_PRODUCTID = INSUR_PRODUCTID;
	}

	public String getINSURANCE_FLAG() {
		return this.INSURANCE_FLAG;
	}

	public void setINSURANCE_FLAG(String INSURANCE_FLAG) {
		this.INSURANCE_FLAG = INSURANCE_FLAG;
	}

	public Date getINSURED_TILL() {
		return this.INSURED_TILL;
	}

	public void setINSURED_TILL(Date INSURED_TILL) {
		this.INSURED_TILL = INSURED_TILL;
	}

	public String getDEPOSIT_ACCOUNT() {
		return this.DEPOSIT_ACCOUNT;
	}

	public void setDEPOSIT_ACCOUNT(String DEPOSIT_ACCOUNT) {
		this.DEPOSIT_ACCOUNT = DEPOSIT_ACCOUNT;
	}

	public BigDecimal getSPREAD2() {
		return this.SPREAD2;
	}

	public void setSPREAD2(BigDecimal SPREAD2) {
		this.SPREAD2 = SPREAD2;
	}

	public Short getFLOATING_FREQUENCY() {
		return this.FLOATING_FREQUENCY;
	}

	public void setFLOATING_FREQUENCY(Short FLOATING_FREQUENCY) {
		this.FLOATING_FREQUENCY = FLOATING_FREQUENCY;
	}

	public Date getLAST_FLOAT_SPREAD_DATE() {
		return this.LAST_FLOAT_SPREAD_DATE;
	}

	public void setLAST_FLOAT_SPREAD_DATE(Date LAST_FLOAT_SPREAD_DATE) {
		this.LAST_FLOAT_SPREAD_DATE = LAST_FLOAT_SPREAD_DATE;
	}

	public BigDecimal getLTV_MULTIPLIER() {
		return this.LTV_MULTIPLIER;
	}

	public void setLTV_MULTIPLIER(BigDecimal LTV_MULTIPLIER) {
		this.LTV_MULTIPLIER = LTV_MULTIPLIER;
	}

	public String getDISBURSEMENT_DIRECT_CREDIT() {
		return this.DISBURSEMENT_DIRECT_CREDIT;
	}

	public void setDISBURSEMENT_DIRECT_CREDIT(String DISBURSEMENT_DIRECT_CREDIT) {
		this.DISBURSEMENT_DIRECT_CREDIT = DISBURSEMENT_DIRECT_CREDIT;
	}

	public Short getSTAT_ACC_FREQUENCY() {
		return this.STAT_ACC_FREQUENCY;
	}

	public void setSTAT_ACC_FREQUENCY(Short STAT_ACC_FREQUENCY) {
		this.STAT_ACC_FREQUENCY = STAT_ACC_FREQUENCY;
	}

	public String getSYSTEM() {
		return this.SYSTEM;
	}

	public void setSYSTEM(String SYSTEM) {
		this.SYSTEM = SYSTEM;
	}

	public BigDecimal getAMTFIN_REGULAR() {
		return this.AMTFIN_REGULAR;
	}

	public void setAMTFIN_REGULAR(BigDecimal AMTFIN_REGULAR) {
		this.AMTFIN_REGULAR = AMTFIN_REGULAR;
	}

	public BigDecimal getAMTFIN_BONUS() {
		return this.AMTFIN_BONUS;
	}

	public void setAMTFIN_BONUS(BigDecimal AMTFIN_BONUS) {
		this.AMTFIN_BONUS = AMTFIN_BONUS;
	}

	public String getFREQ_BONUS() {
		return this.FREQ_BONUS;
	}

	public void setFREQ_BONUS(String FREQ_BONUS) {
		this.FREQ_BONUS = FREQ_BONUS;
	}

	public String getINSTLMODE_BONUS() {
		return this.INSTLMODE_BONUS;
	}

	public void setINSTLMODE_BONUS(String INSTLMODE_BONUS) {
		this.INSTLMODE_BONUS = INSTLMODE_BONUS;
	}

	public Short getADVANCEINSTL_BONUS() {
		return this.ADVANCEINSTL_BONUS;
	}

	public void setADVANCEINSTL_BONUS(Short ADVANCEINSTL_BONUS) {
		this.ADVANCEINSTL_BONUS = ADVANCEINSTL_BONUS;
	}

	public Date getDISBURSALDATE_BONUS() {
		return this.DISBURSALDATE_BONUS;
	}

	public void setDISBURSALDATE_BONUS(Date DISBURSALDATE_BONUS) {
		this.DISBURSALDATE_BONUS = DISBURSALDATE_BONUS;
	}

	public String getINT_ROUNDOFF_PARA() {
		return this.INT_ROUNDOFF_PARA;
	}

	public void setINT_ROUNDOFF_PARA(String INT_ROUNDOFF_PARA) {
		this.INT_ROUNDOFF_PARA = INT_ROUNDOFF_PARA;
	}

	public Integer getINT_ROUNDTILL() {
		return this.INT_ROUNDTILL;
	}

	public void setINT_ROUNDTILL(Integer INT_ROUNDTILL) {
		this.INT_ROUNDTILL = INT_ROUNDTILL;
	}

	public String getINSTLAMT_ROUNDOFF_PARA() {
		return this.INSTLAMT_ROUNDOFF_PARA;
	}

	public void setINSTLAMT_ROUNDOFF_PARA(String INSTLAMT_ROUNDOFF_PARA) {
		this.INSTLAMT_ROUNDOFF_PARA = INSTLAMT_ROUNDOFF_PARA;
	}

	public Integer getINSTLAMT_ROUNDTILL() {
		return this.INSTLAMT_ROUNDTILL;
	}

	public void setINSTLAMT_ROUNDTILL(Integer INSTLAMT_ROUNDTILL) {
		this.INSTLAMT_ROUNDTILL = INSTLAMT_ROUNDTILL;
	}

	public Short getPRIN_BASE_UNIT() {
		return this.PRIN_BASE_UNIT;
	}

	public void setPRIN_BASE_UNIT(Short PRIN_BASE_UNIT) {
		this.PRIN_BASE_UNIT = PRIN_BASE_UNIT;
	}

	public Integer getFIXED_TERM() {
		return this.FIXED_TERM;
	}

	public void setFIXED_TERM(Integer FIXED_TERM) {
		this.FIXED_TERM = FIXED_TERM;
	}

	public Date getINTSTART_DATE_BONUS() {
		return this.INTSTART_DATE_BONUS;
	}

	public void setINTSTART_DATE_BONUS(Date INTSTART_DATE_BONUS) {
		this.INTSTART_DATE_BONUS = INTSTART_DATE_BONUS;
	}

	public String getINSTALTYPE_BONUS() {
		return this.INSTALTYPE_BONUS;
	}

	public void setINSTALTYPE_BONUS(String INSTALTYPE_BONUS) {
		this.INSTALTYPE_BONUS = INSTALTYPE_BONUS;
	}

	public String getINS_BILL_FLAG() {
		return this.INS_BILL_FLAG;
	}

	public void setINS_BILL_FLAG(String INS_BILL_FLAG) {
		this.INS_BILL_FLAG = INS_BILL_FLAG;
	}

	public BigDecimal getSPECIAL_SPREAD() {
		return this.SPECIAL_SPREAD;
	}

	public void setSPECIAL_SPREAD(BigDecimal SPECIAL_SPREAD) {
		this.SPECIAL_SPREAD = SPECIAL_SPREAD;
	}

	public BigDecimal getEMI_BONUS() {
		return this.EMI_BONUS;
	}

	public void setEMI_BONUS(BigDecimal EMI_BONUS) {
		this.EMI_BONUS = EMI_BONUS;
	}

	public Date getNEXT_FLOAT_PRIME_DATE() {
		return this.NEXT_FLOAT_PRIME_DATE;
	}

	public void setNEXT_FLOAT_PRIME_DATE(Date NEXT_FLOAT_PRIME_DATE) {
		this.NEXT_FLOAT_PRIME_DATE = NEXT_FLOAT_PRIME_DATE;
	}

	public Date getNEXT_FLOAT_SPREAD_DATE() {
		return this.NEXT_FLOAT_SPREAD_DATE;
	}

	public void setNEXT_FLOAT_SPREAD_DATE(Date NEXT_FLOAT_SPREAD_DATE) {
		this.NEXT_FLOAT_SPREAD_DATE = NEXT_FLOAT_SPREAD_DATE;
	}

	public Integer getREFINANCE_RECEIPTID() {
		return this.REFINANCE_RECEIPTID;
	}

	public void setREFINANCE_RECEIPTID(Integer REFINANCE_RECEIPTID) {
		this.REFINANCE_RECEIPTID = REFINANCE_RECEIPTID;
	}

	public BigDecimal getSTEP_RATE() {
		return this.STEP_RATE;
	}

	public void setSTEP_RATE(BigDecimal STEP_RATE) {
		this.STEP_RATE = STEP_RATE;
	}

	public Short getAGE_PAST_AGR() {
		return this.AGE_PAST_AGR;
	}

	public void setAGE_PAST_AGR(Short AGE_PAST_AGR) {
		this.AGE_PAST_AGR = AGE_PAST_AGR;
	}

	public String getINVOICE_FLAG() {
		return this.INVOICE_FLAG;
	}

	public void setINVOICE_FLAG(String INVOICE_FLAG) {
		this.INVOICE_FLAG = INVOICE_FLAG;
	}

	public String getRC_FLAG() {
		return this.RC_FLAG;
	}

	public void setRC_FLAG(String RC_FLAG) {
		this.RC_FLAG = RC_FLAG;
	}

	public BigDecimal getSERVICETAXRATE() {
		return this.SERVICETAXRATE;
	}

	public void setSERVICETAXRATE(BigDecimal SERVICETAXRATE) {
		this.SERVICETAXRATE = SERVICETAXRATE;
	}

	public Integer getDME_ID() {
		return this.DME_ID;
	}

	public void setDME_ID(Integer DME_ID) {
		this.DME_ID = DME_ID;
	}

	public Integer getGROUPID() {
		return this.GROUPID;
	}

	public void setGROUPID(Integer GROUPID) {
		this.GROUPID = GROUPID;
	}

	public Integer getPROMOTIONID() {
		return this.PROMOTIONID;
	}

	public void setPROMOTIONID(Integer PROMOTIONID) {
		this.PROMOTIONID = PROMOTIONID;
	}

	public String getFILENO() {
		return this.FILENO;
	}

	public void setFILENO(String FILENO) {
		this.FILENO = FILENO;
	}

	public String getAPP_FORMNO() {
		return this.APP_FORMNO;
	}

	public void setAPP_FORMNO(String APP_FORMNO) {
		this.APP_FORMNO = APP_FORMNO;
	}

	public String getHFI_FLAG() {
		return this.HFI_FLAG;
	}

	public void setHFI_FLAG(String HFI_FLAG) {
		this.HFI_FLAG = HFI_FLAG;
	}

	public String getHFI() {
		return this.HFI;
	}

	public void setHFI(String HFI) {
		this.HFI = HFI;
	}

	public Integer getEMPLOYER_ADDRESSID() {
		return this.EMPLOYER_ADDRESSID;
	}

	public void setEMPLOYER_ADDRESSID(Integer EMPLOYER_ADDRESSID) {
		this.EMPLOYER_ADDRESSID = EMPLOYER_ADDRESSID;
	}

	public String getEMPCODE() {
		return this.EMPCODE;
	}

	public void setEMPCODE(String EMPCODE) {
		this.EMPCODE = EMPCODE;
	}

	public Integer getSPREADID() {
		return this.SPREADID;
	}

	public void setSPREADID(Integer SPREADID) {
		this.SPREADID = SPREADID;
	}

	public BigDecimal getINITIAL_EFFRATE() {
		return this.INITIAL_EFFRATE;
	}

	public void setINITIAL_EFFRATE(BigDecimal INITIAL_EFFRATE) {
		this.INITIAL_EFFRATE = INITIAL_EFFRATE;
	}

	public Date getINTSTART_DATE_REGULAR() {
		return this.INTSTART_DATE_REGULAR;
	}

	public void setINTSTART_DATE_REGULAR(Date INTSTART_DATE_REGULAR) {
		this.INTSTART_DATE_REGULAR = INTSTART_DATE_REGULAR;
	}

	public String getTRANCHING_FLAG() {
		return this.TRANCHING_FLAG;
	}

	public void setTRANCHING_FLAG(String TRANCHING_FLAG) {
		this.TRANCHING_FLAG = TRANCHING_FLAG;
	}

	public String getTRANCHING_TYPE() {
		return this.TRANCHING_TYPE;
	}

	public void setTRANCHING_TYPE(String TRANCHING_TYPE) {
		this.TRANCHING_TYPE = TRANCHING_TYPE;
	}

	public String getCOMPOUND_FREQ() {
		return this.COMPOUND_FREQ;
	}

	public void setCOMPOUND_FREQ(String COMPOUND_FREQ) {
		this.COMPOUND_FREQ = COMPOUND_FREQ;
	}

	public String getINT_REBATE_FLAG() {
		return this.INT_REBATE_FLAG;
	}

	public void setINT_REBATE_FLAG(String INT_REBATE_FLAG) {
		this.INT_REBATE_FLAG = INT_REBATE_FLAG;
	}

	public BigDecimal getACTUALIRR() {
		return this.ACTUALIRR;
	}

	public void setACTUALIRR(BigDecimal ACTUALIRR) {
		this.ACTUALIRR = ACTUALIRR;
	}

	public String getDISB_STATUS() {
		return this.DISB_STATUS;
	}

	public void setDISB_STATUS(String DISB_STATUS) {
		this.DISB_STATUS = DISB_STATUS;
	}

	public BigDecimal getGROSS_LTV() {
		return this.GROSS_LTV;
	}

	public void setGROSS_LTV(BigDecimal GROSS_LTV) {
		this.GROSS_LTV = GROSS_LTV;
	}

	public BigDecimal getNET_LTV() {
		return this.NET_LTV;
	}

	public void setNET_LTV(BigDecimal NET_LTV) {
		this.NET_LTV = NET_LTV;
	}

	public BigDecimal getAMT_REQUESTED() {
		return this.AMT_REQUESTED;
	}

	public void setAMT_REQUESTED(BigDecimal AMT_REQUESTED) {
		this.AMT_REQUESTED = AMT_REQUESTED;
	}

	public Short getTENURE_REQUESTED() {
		return this.TENURE_REQUESTED;
	}

	public void setTENURE_REQUESTED(Short TENURE_REQUESTED) {
		this.TENURE_REQUESTED = TENURE_REQUESTED;
	}

	public String getRATE_EMI_FLAG() {
		return this.RATE_EMI_FLAG;
	}

	public void setRATE_EMI_FLAG(String RATE_EMI_FLAG) {
		this.RATE_EMI_FLAG = RATE_EMI_FLAG;
	}

	public String getASSET_MARKED() {
		return this.ASSET_MARKED;
	}

	public void setASSET_MARKED(String ASSET_MARKED) {
		this.ASSET_MARKED = ASSET_MARKED;
	}

	public BigDecimal getDISBURSALAMOUNT() {
		return this.DISBURSALAMOUNT;
	}

	public void setDISBURSALAMOUNT(BigDecimal DISBURSALAMOUNT) {
		this.DISBURSALAMOUNT = DISBURSALAMOUNT;
	}

	public Integer getORG_SCHEMEID() {
		return this.ORG_SCHEMEID;
	}

	public void setORG_SCHEMEID(Integer ORG_SCHEMEID) {
		this.ORG_SCHEMEID = ORG_SCHEMEID;
	}

	public String getLSI_AGREEMENT_NO() {
		return this.LSI_AGREEMENT_NO;
	}

	public void setLSI_AGREEMENT_NO(String LSI_AGREEMENT_NO) {
		this.LSI_AGREEMENT_NO = LSI_AGREEMENT_NO;
	}

	public String getCHRG_FLG() {
		return this.CHRG_FLG;
	}

	public void setCHRG_FLG(String CHRG_FLG) {
		this.CHRG_FLG = CHRG_FLG;
	}

	public String getDISB_FLAG() {
		return this.DISB_FLAG;
	}

	public void setDISB_FLAG(String DISB_FLAG) {
		this.DISB_FLAG = DISB_FLAG;
	}

	public String getHL_FILE_NO() {
		return this.HL_FILE_NO;
	}

	public void setHL_FILE_NO(String HL_FILE_NO) {
		this.HL_FILE_NO = HL_FILE_NO;
	}

	public String getOLD_AGREEMENTNO() {
		return this.OLD_AGREEMENTNO;
	}

	public void setOLD_AGREEMENTNO(String OLD_AGREEMENTNO) {
		this.OLD_AGREEMENTNO = OLD_AGREEMENTNO;
	}

	public String getPEMI_BILLING() {
		return this.PEMI_BILLING;
	}

	public void setPEMI_BILLING(String PEMI_BILLING) {
		this.PEMI_BILLING = PEMI_BILLING;
	}

	public String getREPAY_FLG() {
		return this.REPAY_FLG;
	}

	public void setREPAY_FLG(String REPAY_FLG) {
		this.REPAY_FLG = REPAY_FLG;
	}

	public String getTEMPUPD_DUEDATE() {
		return this.TEMPUPD_DUEDATE;
	}

	public void setTEMPUPD_DUEDATE(String TEMPUPD_DUEDATE) {
		this.TEMPUPD_DUEDATE = TEMPUPD_DUEDATE;
	}

	public BigDecimal getMIN_FLOAT_RATE() {
		return this.MIN_FLOAT_RATE;
	}

	public void setMIN_FLOAT_RATE(BigDecimal MIN_FLOAT_RATE) {
		this.MIN_FLOAT_RATE = MIN_FLOAT_RATE;
	}

	public String getPUTCALL_FLAG() {
		return this.PUTCALL_FLAG;
	}

	public void setPUTCALL_FLAG(String PUTCALL_FLAG) {
		this.PUTCALL_FLAG = PUTCALL_FLAG;
	}

	public String getBILLTYPE() {
		return this.BILLTYPE;
	}

	public void setBILLTYPE(String BILLTYPE) {
		this.BILLTYPE = BILLTYPE;
	}

	public String getHUNDINO() {
		return this.HUNDINO;
	}

	public void setHUNDINO(String HUNDINO) {
		this.HUNDINO = HUNDINO;
	}

	public Date getHUNDIDATE() {
		return this.HUNDIDATE;
	}

	public void setHUNDIDATE(Date HUNDIDATE) {
		this.HUNDIDATE = HUNDIDATE;
	}

	public Date getHUNDIDUEDATE() {
		return this.HUNDIDUEDATE;
	}

	public void setHUNDIDUEDATE(Date HUNDIDUEDATE) {
		this.HUNDIDUEDATE = HUNDIDUEDATE;
	}

	public BigDecimal getHUNDIAMT() {
		return this.HUNDIAMT;
	}

	public void setHUNDIAMT(BigDecimal HUNDIAMT) {
		this.HUNDIAMT = HUNDIAMT;
	}

	public BigDecimal getSTAMPVALUE() {
		return this.STAMPVALUE;
	}

	public void setSTAMPVALUE(BigDecimal STAMPVALUE) {
		this.STAMPVALUE = STAMPVALUE;
	}

	public BigDecimal getSTAMPRATE() {
		return this.STAMPRATE;
	}

	public void setSTAMPRATE(BigDecimal STAMPRATE) {
		this.STAMPRATE = STAMPRATE;
	}

	public BigDecimal getINTTAX() {
		return this.INTTAX;
	}

	public void setINTTAX(BigDecimal INTTAX) {
		this.INTTAX = INTTAX;
	}

	public String getPROGRAM() {
		return this.PROGRAM;
	}

	public void setPROGRAM(String PROGRAM) {
		this.PROGRAM = PROGRAM;
	}

	public String getDIVISION() {
		return this.DIVISION;
	}

	public void setDIVISION(String DIVISION) {
		this.DIVISION = DIVISION;
	}

	public Integer getMARGINDAYS() {
		return this.MARGINDAYS;
	}

	public void setMARGINDAYS(Integer MARGINDAYS) {
		this.MARGINDAYS = MARGINDAYS;
	}

	public String getREMARKS() {
		return this.REMARKS;
	}

	public void setREMARKS(String REMARKS) {
		this.REMARKS = REMARKS;
	}

	public BigDecimal getTDS() {
		return this.TDS;
	}

	public void setTDS(BigDecimal TDS) {
		this.TDS = TDS;
	}

	public Integer getPARTYID() {
		return this.PARTYID;
	}

	public void setPARTYID(Integer PARTYID) {
		this.PARTYID = PARTYID;
	}

	public String getCUMULATIVE_INTEREST() {
		return this.CUMULATIVE_INTEREST;
	}

	public void setCUMULATIVE_INTEREST(String CUMULATIVE_INTEREST) {
		this.CUMULATIVE_INTEREST = CUMULATIVE_INTEREST;
	}

	public BigDecimal getFINANCIAL_QUANTUM() {
		return this.FINANCIAL_QUANTUM;
	}

	public void setFINANCIAL_QUANTUM(BigDecimal FINANCIAL_QUANTUM) {
		this.FINANCIAL_QUANTUM = FINANCIAL_QUANTUM;
	}

	public String getCPF_FIRST_CHARGE_FLAG() {
		return this.CPF_FIRST_CHARGE_FLAG;
	}

	public void setCPF_FIRST_CHARGE_FLAG(String CPF_FIRST_CHARGE_FLAG) {
		this.CPF_FIRST_CHARGE_FLAG = CPF_FIRST_CHARGE_FLAG;
	}

	public String getCPF_ARPS_NUMBER() {
		return this.CPF_ARPS_NUMBER;
	}

	public void setCPF_ARPS_NUMBER(String CPF_ARPS_NUMBER) {
		this.CPF_ARPS_NUMBER = CPF_ARPS_NUMBER;
	}

	public BigDecimal getCPF_APP_AMOUNT() {
		return this.CPF_APP_AMOUNT;
	}

	public void setCPF_APP_AMOUNT(BigDecimal CPF_APP_AMOUNT) {
		this.CPF_APP_AMOUNT = CPF_APP_AMOUNT;
	}

	public BigDecimal getCPF_MAXIMUM_MONTHLY() {
		return this.CPF_MAXIMUM_MONTHLY;
	}

	public void setCPF_MAXIMUM_MONTHLY(BigDecimal CPF_MAXIMUM_MONTHLY) {
		this.CPF_MAXIMUM_MONTHLY = CPF_MAXIMUM_MONTHLY;
	}

	public BigDecimal getDEALER_PARTICIPATION_RATE() {
		return this.DEALER_PARTICIPATION_RATE;
	}

	public void setDEALER_PARTICIPATION_RATE(
			BigDecimal DEALER_PARTICIPATION_RATE) {
		this.DEALER_PARTICIPATION_RATE = DEALER_PARTICIPATION_RATE;
	}

	public String getOVERDUE_PLRTYPE() {
		return this.OVERDUE_PLRTYPE;
	}

	public void setOVERDUE_PLRTYPE(String OVERDUE_PLRTYPE) {
		this.OVERDUE_PLRTYPE = OVERDUE_PLRTYPE;
	}

	public BigDecimal getOVERDUE_MARKUP() {
		return this.OVERDUE_MARKUP;
	}

	public void setOVERDUE_MARKUP(BigDecimal OVERDUE_MARKUP) {
		this.OVERDUE_MARKUP = OVERDUE_MARKUP;
	}

	public BigDecimal getAPP_LOAN_LIMIT() {
		return this.APP_LOAN_LIMIT;
	}

	public void setAPP_LOAN_LIMIT(BigDecimal APP_LOAN_LIMIT) {
		this.APP_LOAN_LIMIT = APP_LOAN_LIMIT;
	}

	public String getPSB_APPL_NO() {
		return this.PSB_APPL_NO;
	}

	public void setPSB_APPL_NO(String PSB_APPL_NO) {
		this.PSB_APPL_NO = PSB_APPL_NO;
	}

	public BigDecimal getSUB_ACCT() {
		return this.SUB_ACCT;
	}

	public void setSUB_ACCT(BigDecimal SUB_ACCT) {
		this.SUB_ACCT = SUB_ACCT;
	}

	public BigDecimal getCOLLATERAL_ACCT() {
		return this.COLLATERAL_ACCT;
	}

	public void setCOLLATERAL_ACCT(BigDecimal COLLATERAL_ACCT) {
		this.COLLATERAL_ACCT = COLLATERAL_ACCT;
	}

	public BigDecimal getFLAT_SPREAD() {
		return this.FLAT_SPREAD;
	}

	public void setFLAT_SPREAD(BigDecimal FLAT_SPREAD) {
		this.FLAT_SPREAD = FLAT_SPREAD;
	}

	public byte getGRACE_DAYS() {
		return this.GRACE_DAYS;
	}

	public void setGRACE_DAYS(byte GRACE_DAYS) {
		this.GRACE_DAYS = GRACE_DAYS;
	}

	public BigDecimal getGRACE_AMT() {
		return this.GRACE_AMT;
	}

	public void setGRACE_AMT(BigDecimal GRACE_AMT) {
		this.GRACE_AMT = GRACE_AMT;
	}

	public Integer getPREV_LOAN_NO() {
		return this.PREV_LOAN_NO;
	}

	public void setPREV_LOAN_NO(Integer PREV_LOAN_NO) {
		this.PREV_LOAN_NO = PREV_LOAN_NO;
	}

	public Integer getLINECODEID() {
		return this.LINECODEID;
	}

	public void setLINECODEID(Integer LINECODEID) {
		this.LINECODEID = LINECODEID;
	}

	public Integer getSECURITY_CODE() {
		return this.SECURITY_CODE;
	}

	public void setSECURITY_CODE(Integer SECURITY_CODE) {
		this.SECURITY_CODE = SECURITY_CODE;
	}

	public String getINSTL_FLAG() {
		return this.INSTL_FLAG;
	}

	public void setINSTL_FLAG(String INSTL_FLAG) {
		this.INSTL_FLAG = INSTL_FLAG;
	}

	public String getADMINFEE_CALC_FLAG() {
		return this.ADMINFEE_CALC_FLAG;
	}

	public void setADMINFEE_CALC_FLAG(String ADMINFEE_CALC_FLAG) {
		this.ADMINFEE_CALC_FLAG = ADMINFEE_CALC_FLAG;
	}

	public String getLPP_STOP_FLAG() {
		return this.LPP_STOP_FLAG;
	}

	public void setLPP_STOP_FLAG(String LPP_STOP_FLAG) {
		this.LPP_STOP_FLAG = LPP_STOP_FLAG;
	}

	public String getDISBURSEMENT_STOP_FLAG() {
		return this.DISBURSEMENT_STOP_FLAG;
	}

	public void setDISBURSEMENT_STOP_FLAG(String DISBURSEMENT_STOP_FLAG) {
		this.DISBURSEMENT_STOP_FLAG = DISBURSEMENT_STOP_FLAG;
	}

	public Integer getGST_RATE() {
		return this.GST_RATE;
	}

	public void setGST_RATE(Integer GST_RATE) {
		this.GST_RATE = GST_RATE;
	}

	public String getGST_CONSTANT() {
		return this.GST_CONSTANT;
	}

	public void setGST_CONSTANT(String GST_CONSTANT) {
		this.GST_CONSTANT = GST_CONSTANT;
	}

	public String getRULE_OF_78() {
		return this.RULE_OF_78;
	}

	public void setRULE_OF_78(String RULE_OF_78) {
		this.RULE_OF_78 = RULE_OF_78;
	}

	public BigDecimal getCPF_INITIAL_WITHDRAWN() {
		return this.CPF_INITIAL_WITHDRAWN;
	}

	public void setCPF_INITIAL_WITHDRAWN(BigDecimal CPF_INITIAL_WITHDRAWN) {
		this.CPF_INITIAL_WITHDRAWN = CPF_INITIAL_WITHDRAWN;
	}

	public String getREVOLVING_FLAG() {
		return this.REVOLVING_FLAG;
	}

	public void setREVOLVING_FLAG(String REVOLVING_FLAG) {
		this.REVOLVING_FLAG = REVOLVING_FLAG;
	}

	public String getREDEMPTION_FLAG() {
		return this.REDEMPTION_FLAG;
	}

	public void setREDEMPTION_FLAG(String REDEMPTION_FLAG) {
		this.REDEMPTION_FLAG = REDEMPTION_FLAG;
	}

	public String getINTEREST_UPFRONT_FLAG() {
		return this.INTEREST_UPFRONT_FLAG;
	}

	public void setINTEREST_UPFRONT_FLAG(String INTEREST_UPFRONT_FLAG) {
		this.INTEREST_UPFRONT_FLAG = INTEREST_UPFRONT_FLAG;
	}

	public BigDecimal getINTEREST_UPFRONT_AMT() {
		return this.INTEREST_UPFRONT_AMT;
	}

	public void setINTEREST_UPFRONT_AMT(BigDecimal INTEREST_UPFRONT_AMT) {
		this.INTEREST_UPFRONT_AMT = INTEREST_UPFRONT_AMT;
	}

	public String getINTEREST_STARTMONTH() {
		return this.INTEREST_STARTMONTH;
	}

	public void setINTEREST_STARTMONTH(String INTEREST_STARTMONTH) {
		this.INTEREST_STARTMONTH = INTEREST_STARTMONTH;
	}

	public Date getREPAYMENT_STARTDATE() {
		return this.REPAYMENT_STARTDATE;
	}

	public void setREPAYMENT_STARTDATE(Date REPAYMENT_STARTDATE) {
		this.REPAYMENT_STARTDATE = REPAYMENT_STARTDATE;
	}

	public String getTAX_STOP() {
		return this.TAX_STOP;
	}

	public void setTAX_STOP(String TAX_STOP) {
		this.TAX_STOP = TAX_STOP;
	}

	public String getNPA_PRO_FLAG() {
		return this.NPA_PRO_FLAG;
	}

	public void setNPA_PRO_FLAG(String NPA_PRO_FLAG) {
		this.NPA_PRO_FLAG = NPA_PRO_FLAG;
	}

	public String getNPA_PRO_REMARKS() {
		return this.NPA_PRO_REMARKS;
	}

	public void setNPA_PRO_REMARKS(String NPA_PRO_REMARKS) {
		this.NPA_PRO_REMARKS = NPA_PRO_REMARKS;
	}

	public String getFINAL_NPA_STAGEID() {
		return this.FINAL_NPA_STAGEID;
	}

	public void setFINAL_NPA_STAGEID(String FINAL_NPA_STAGEID) {
		this.FINAL_NPA_STAGEID = FINAL_NPA_STAGEID;
	}

	public String getNPA_MANUAL_FLAG() {
		return this.NPA_MANUAL_FLAG;
	}

	public void setNPA_MANUAL_FLAG(String NPA_MANUAL_FLAG) {
		this.NPA_MANUAL_FLAG = NPA_MANUAL_FLAG;
	}

	public Integer getNPA_REASON() {
		return this.NPA_REASON;
	}

	public void setNPA_REASON(Integer NPA_REASON) {
		this.NPA_REASON = NPA_REASON;
	}

	public Date getNPA_STAMP_DATE() {
		return this.NPA_STAMP_DATE;
	}

	public void setNPA_STAMP_DATE(Date NPA_STAMP_DATE) {
		this.NPA_STAMP_DATE = NPA_STAMP_DATE;
	}

	public Date getREREGULAR_DATE() {
		return this.REREGULAR_DATE;
	}

	public void setREREGULAR_DATE(Date REREGULAR_DATE) {
		this.REREGULAR_DATE = REREGULAR_DATE;
	}

	public String getRESCHEDULE_STOP() {
		return this.RESCHEDULE_STOP;
	}

	public void setRESCHEDULE_STOP(String RESCHEDULE_STOP) {
		this.RESCHEDULE_STOP = RESCHEDULE_STOP;
	}

	public String getNPA_MANUAL_REMARKS() {
		return this.NPA_MANUAL_REMARKS;
	}

	public void setNPA_MANUAL_REMARKS(String NPA_MANUAL_REMARKS) {
		this.NPA_MANUAL_REMARKS = NPA_MANUAL_REMARKS;
	}

	public Integer getFT_BATCHNUMBER() {
		return this.FT_BATCHNUMBER;
	}

	public void setFT_BATCHNUMBER(Integer FT_BATCHNUMBER) {
		this.FT_BATCHNUMBER = FT_BATCHNUMBER;
	}

	public String getLOS_AGREEMENT() {
		return this.LOS_AGREEMENT;
	}

	public void setLOS_AGREEMENT(String LOS_AGREEMENT) {
		this.LOS_AGREEMENT = LOS_AGREEMENT;
	}

	public Set getLEA_REPAYSCH_DTLs() {
		return this.LEA_REPAYSCH_DTLs;
	}

	public void setLEA_REPAYSCH_DTLs(Set LEA_REPAYSCH_DTLs) {
		this.LEA_REPAYSCH_DTLs = LEA_REPAYSCH_DTLs;
	}

}
