package com.pruvn.tools.common.hibernate.finnone.lending;

// Generated Sep 16, 2010 2:42:01 PM by Hibernate Tools 3.2.4.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * NBFC_TXN_CHARGE_DTL generated by hbm2java
 */
public class NBFC_TXN_CHARGE_DTL implements java.io.Serializable {

	private int TXNCHARGEID;
	private String MODULEID;
	private String TXNTYPE;
	private String TXNID;
	private int CHARGEID;
	private int BPID;
	private String BPTYPE;
	private BigDecimal DEFCHARGERATE;
	private BigDecimal DEFCHARGEAMT;
	private BigDecimal CHARGERATE;
	private BigDecimal CHARGEAMT;
	private String ADVICEGENFLG;
	private String ADVICEFLG;
	private String STATUS;
	private Integer CHARGECODEID;
	private BigDecimal CONTENT;
	private String RCPTPMNTFLG;
	private String CHARGEDESC;
	private String CURRENCYID;
	private String PRODUCTID;
	private Integer BRANCHID;
	private Date ADVICEDATE;
	private Integer CASEID;
	private Date DATELASTUPDT;
	private Integer CREDIT_PERIOD;
	private Long RLS_LAOD_SR_NO;
	private String GST_REQUIRED;
	private BigDecimal TAXAMOUNT;
	private String TAX_APPLICABLE;
	private BigDecimal EFFCHGAMT;

	public NBFC_TXN_CHARGE_DTL() {
	}

	public NBFC_TXN_CHARGE_DTL(int TXNCHARGEID, String MODULEID,
			String TXNTYPE, int CHARGEID, int BPID, String BPTYPE,
			String GST_REQUIRED) {
		this.TXNCHARGEID = TXNCHARGEID;
		this.MODULEID = MODULEID;
		this.TXNTYPE = TXNTYPE;
		this.CHARGEID = CHARGEID;
		this.BPID = BPID;
		this.BPTYPE = BPTYPE;
		this.GST_REQUIRED = GST_REQUIRED;
	}

	public NBFC_TXN_CHARGE_DTL(int TXNCHARGEID, String MODULEID,
			String TXNTYPE, String TXNID, int CHARGEID, int BPID,
			String BPTYPE, BigDecimal DEFCHARGERATE, BigDecimal DEFCHARGEAMT,
			BigDecimal CHARGERATE, BigDecimal CHARGEAMT, String ADVICEGENFLG,
			String ADVICEFLG, String STATUS, Integer CHARGECODEID,
			BigDecimal CONTENT, String RCPTPMNTFLG, String CHARGEDESC,
			String CURRENCYID, String PRODUCTID, Integer BRANCHID,
			Date ADVICEDATE, Integer CASEID, Date DATELASTUPDT,
			Integer CREDIT_PERIOD, Long RLS_LAOD_SR_NO, String GST_REQUIRED,
			BigDecimal TAXAMOUNT, String TAX_APPLICABLE, BigDecimal EFFCHGAMT) {
		this.TXNCHARGEID = TXNCHARGEID;
		this.MODULEID = MODULEID;
		this.TXNTYPE = TXNTYPE;
		this.TXNID = TXNID;
		this.CHARGEID = CHARGEID;
		this.BPID = BPID;
		this.BPTYPE = BPTYPE;
		this.DEFCHARGERATE = DEFCHARGERATE;
		this.DEFCHARGEAMT = DEFCHARGEAMT;
		this.CHARGERATE = CHARGERATE;
		this.CHARGEAMT = CHARGEAMT;
		this.ADVICEGENFLG = ADVICEGENFLG;
		this.ADVICEFLG = ADVICEFLG;
		this.STATUS = STATUS;
		this.CHARGECODEID = CHARGECODEID;
		this.CONTENT = CONTENT;
		this.RCPTPMNTFLG = RCPTPMNTFLG;
		this.CHARGEDESC = CHARGEDESC;
		this.CURRENCYID = CURRENCYID;
		this.PRODUCTID = PRODUCTID;
		this.BRANCHID = BRANCHID;
		this.ADVICEDATE = ADVICEDATE;
		this.CASEID = CASEID;
		this.DATELASTUPDT = DATELASTUPDT;
		this.CREDIT_PERIOD = CREDIT_PERIOD;
		this.RLS_LAOD_SR_NO = RLS_LAOD_SR_NO;
		this.GST_REQUIRED = GST_REQUIRED;
		this.TAXAMOUNT = TAXAMOUNT;
		this.TAX_APPLICABLE = TAX_APPLICABLE;
		this.EFFCHGAMT = EFFCHGAMT;
	}

	public int getTXNCHARGEID() {
		return this.TXNCHARGEID;
	}

	public void setTXNCHARGEID(int TXNCHARGEID) {
		this.TXNCHARGEID = TXNCHARGEID;
	}

	public String getMODULEID() {
		return this.MODULEID;
	}

	public void setMODULEID(String MODULEID) {
		this.MODULEID = MODULEID;
	}

	public String getTXNTYPE() {
		return this.TXNTYPE;
	}

	public void setTXNTYPE(String TXNTYPE) {
		this.TXNTYPE = TXNTYPE;
	}

	public String getTXNID() {
		return this.TXNID;
	}

	public void setTXNID(String TXNID) {
		this.TXNID = TXNID;
	}

	public int getCHARGEID() {
		return this.CHARGEID;
	}

	public void setCHARGEID(int CHARGEID) {
		this.CHARGEID = CHARGEID;
	}

	public int getBPID() {
		return this.BPID;
	}

	public void setBPID(int BPID) {
		this.BPID = BPID;
	}

	public String getBPTYPE() {
		return this.BPTYPE;
	}

	public void setBPTYPE(String BPTYPE) {
		this.BPTYPE = BPTYPE;
	}

	public BigDecimal getDEFCHARGERATE() {
		return this.DEFCHARGERATE;
	}

	public void setDEFCHARGERATE(BigDecimal DEFCHARGERATE) {
		this.DEFCHARGERATE = DEFCHARGERATE;
	}

	public BigDecimal getDEFCHARGEAMT() {
		return this.DEFCHARGEAMT;
	}

	public void setDEFCHARGEAMT(BigDecimal DEFCHARGEAMT) {
		this.DEFCHARGEAMT = DEFCHARGEAMT;
	}

	public BigDecimal getCHARGERATE() {
		return this.CHARGERATE;
	}

	public void setCHARGERATE(BigDecimal CHARGERATE) {
		this.CHARGERATE = CHARGERATE;
	}

	public BigDecimal getCHARGEAMT() {
		return this.CHARGEAMT;
	}

	public void setCHARGEAMT(BigDecimal CHARGEAMT) {
		this.CHARGEAMT = CHARGEAMT;
	}

	public String getADVICEGENFLG() {
		return this.ADVICEGENFLG;
	}

	public void setADVICEGENFLG(String ADVICEGENFLG) {
		this.ADVICEGENFLG = ADVICEGENFLG;
	}

	public String getADVICEFLG() {
		return this.ADVICEFLG;
	}

	public void setADVICEFLG(String ADVICEFLG) {
		this.ADVICEFLG = ADVICEFLG;
	}

	public String getSTATUS() {
		return this.STATUS;
	}

	public void setSTATUS(String STATUS) {
		this.STATUS = STATUS;
	}

	public Integer getCHARGECODEID() {
		return this.CHARGECODEID;
	}

	public void setCHARGECODEID(Integer CHARGECODEID) {
		this.CHARGECODEID = CHARGECODEID;
	}

	public BigDecimal getCONTENT() {
		return this.CONTENT;
	}

	public void setCONTENT(BigDecimal CONTENT) {
		this.CONTENT = CONTENT;
	}

	public String getRCPTPMNTFLG() {
		return this.RCPTPMNTFLG;
	}

	public void setRCPTPMNTFLG(String RCPTPMNTFLG) {
		this.RCPTPMNTFLG = RCPTPMNTFLG;
	}

	public String getCHARGEDESC() {
		return this.CHARGEDESC;
	}

	public void setCHARGEDESC(String CHARGEDESC) {
		this.CHARGEDESC = CHARGEDESC;
	}

	public String getCURRENCYID() {
		return this.CURRENCYID;
	}

	public void setCURRENCYID(String CURRENCYID) {
		this.CURRENCYID = CURRENCYID;
	}

	public String getPRODUCTID() {
		return this.PRODUCTID;
	}

	public void setPRODUCTID(String PRODUCTID) {
		this.PRODUCTID = PRODUCTID;
	}

	public Integer getBRANCHID() {
		return this.BRANCHID;
	}

	public void setBRANCHID(Integer BRANCHID) {
		this.BRANCHID = BRANCHID;
	}

	public Date getADVICEDATE() {
		return this.ADVICEDATE;
	}

	public void setADVICEDATE(Date ADVICEDATE) {
		this.ADVICEDATE = ADVICEDATE;
	}

	public Integer getCASEID() {
		return this.CASEID;
	}

	public void setCASEID(Integer CASEID) {
		this.CASEID = CASEID;
	}

	public Date getDATELASTUPDT() {
		return this.DATELASTUPDT;
	}

	public void setDATELASTUPDT(Date DATELASTUPDT) {
		this.DATELASTUPDT = DATELASTUPDT;
	}

	public Integer getCREDIT_PERIOD() {
		return this.CREDIT_PERIOD;
	}

	public void setCREDIT_PERIOD(Integer CREDIT_PERIOD) {
		this.CREDIT_PERIOD = CREDIT_PERIOD;
	}

	public Long getRLS_LAOD_SR_NO() {
		return this.RLS_LAOD_SR_NO;
	}

	public void setRLS_LAOD_SR_NO(Long RLS_LAOD_SR_NO) {
		this.RLS_LAOD_SR_NO = RLS_LAOD_SR_NO;
	}

	public String getGST_REQUIRED() {
		return this.GST_REQUIRED;
	}

	public void setGST_REQUIRED(String GST_REQUIRED) {
		this.GST_REQUIRED = GST_REQUIRED;
	}

	public BigDecimal getTAXAMOUNT() {
		return this.TAXAMOUNT;
	}

	public void setTAXAMOUNT(BigDecimal TAXAMOUNT) {
		this.TAXAMOUNT = TAXAMOUNT;
	}

	public String getTAX_APPLICABLE() {
		return this.TAX_APPLICABLE;
	}

	public void setTAX_APPLICABLE(String TAX_APPLICABLE) {
		this.TAX_APPLICABLE = TAX_APPLICABLE;
	}

	public BigDecimal getEFFCHGAMT() {
		return this.EFFCHGAMT;
	}

	public void setEFFCHGAMT(BigDecimal EFFCHGAMT) {
		this.EFFCHGAMT = EFFCHGAMT;
	}

}
