package com.pruvn.tools.common.hibernate.finnone.lending;

// Generated May 31, 2011 2:37:34 PM by Hibernate Tools 3.2.4.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * NBFC_CHEQUE_DTL generated by hbm2java
 */
public class NBFC_CHEQUE_DTL implements java.io.Serializable {

	private int CHEQUEID;
	private String CHEQUETYPE;
	private Integer DEALINGBANKID;
	private String PAYMENTMODE;
	private String CHEQUENUM;
	private Date CHEQUEDATE;
	private BigDecimal CHEQUEAMT;
	private String DRAWNON;
	private String INFAVOUROF;
	private String TOWARDS;
	private String CITY;
	private String PDCFLAG;
	private Long CRNNUM;
	private String MODULEID;
	private String ORIGMODULEID;
	private String STATUS;
	private Date CHEQUESENTDATE;
	private Date DEPOSITDATE;
	private Date REALIZATIONDATE;
	private BigDecimal CLEAREDAMT;
	private Integer OLDCHEQUEID;
	private String BPTYPE;
	private Integer BPID;
	private String FILENUM;
	private String REMARKS;
	private String ALLOCATEFLAG;
	private String TXNREVERSEFLAG;
	private Date FORWARDDATE;
	private Date INTRADIVRECDATE;
	private Date TXNDATE;
	private Date CREATIONDATE;
	private Date HOLDDATE;
	private Date UNHOLDDATE;
	private String CURRENCYID;
	private String STAGE;
	private String REFERENCE;
	private String FA_ENTRIES_GENERATED;
	private String CREATEDBY;
	private String AUTHORIZEDBY;
	private Date AUTHORIZATIONDATE;
	private Integer BRANCHID;
	private Integer PRODUCTID;
	private Integer PDCBBRANCHID;
	private String MC_STATUS;
	private Date MC_DATE;
	private String MC_REMARKS;
	private String REF_NO;
	private String STAGEID;
	private Integer TXNID;
	private String AUTOALLOC;
	private String FINALALLOCFLAG;
	private Integer REASONID;
	private String ACTIONID;
	private String BOUNCECHARGE;
	private String MULTI_LOAN;
	private Date PRESENTATIONDATE;
	private Long BATCHNO;
	private Integer RECEIPT_NO;
	private String BATCHID;
	private Date BATCHDATE;
	private String INSTRUMENT;
	private String FINWARE_ACNO;
	private Date DATELASTUPDT;
	private Byte DEST_BANK_ACCTYPE;
	private String DEST_ACC_HOLDER;
	private String MICR_CODE;
	private String PDC_TYPE;
	private String PDC_BY;
	private String PDC_BY_NAME;
	private String PDC_RETURNED_FLAG;
	private Integer SERVICE_BRANCH;
	private String INBATCH_NO;
	private String OLD_INBATCH_NO;
	private Integer DISBURSAL_NO;
	private String RECEIPTNO;
	private String RECEIPT_CHANNEL;
	private Integer AGENCYID;
	private String MICR_FLAG;
	private String PAYSLIPNO;
	private String CITYID;
	private String BANKID;
	private String BANKBRANCHID;
	private String RLS_HISTORY_FLAG;
	private String RECEIPT_FOR;
	private String KO_LOGIC;

	public NBFC_CHEQUE_DTL() {
	}

	public NBFC_CHEQUE_DTL(int CHEQUEID, String CHEQUETYPE, String PAYMENTMODE,
			BigDecimal CHEQUEAMT, String PDCFLAG, String MODULEID,
			String ORIGMODULEID, String STATUS, String BPTYPE,
			String ALLOCATEFLAG, String TXNREVERSEFLAG, Date DATELASTUPDT) {
		this.CHEQUEID = CHEQUEID;
		this.CHEQUETYPE = CHEQUETYPE;
		this.PAYMENTMODE = PAYMENTMODE;
		this.CHEQUEAMT = CHEQUEAMT;
		this.PDCFLAG = PDCFLAG;
		this.MODULEID = MODULEID;
		this.ORIGMODULEID = ORIGMODULEID;
		this.STATUS = STATUS;
		this.BPTYPE = BPTYPE;
		this.ALLOCATEFLAG = ALLOCATEFLAG;
		this.TXNREVERSEFLAG = TXNREVERSEFLAG;
		this.DATELASTUPDT = DATELASTUPDT;
	}

	public NBFC_CHEQUE_DTL(int CHEQUEID, String CHEQUETYPE,
			Integer DEALINGBANKID, String PAYMENTMODE, String CHEQUENUM,
			Date CHEQUEDATE, BigDecimal CHEQUEAMT, String DRAWNON,
			String INFAVOUROF, String TOWARDS, String CITY, String PDCFLAG,
			Long CRNNUM, String MODULEID, String ORIGMODULEID, String STATUS,
			Date CHEQUESENTDATE, Date DEPOSITDATE, Date REALIZATIONDATE,
			BigDecimal CLEAREDAMT, Integer OLDCHEQUEID, String BPTYPE,
			Integer BPID, String FILENUM, String REMARKS, String ALLOCATEFLAG,
			String TXNREVERSEFLAG, Date FORWARDDATE, Date INTRADIVRECDATE,
			Date TXNDATE, Date CREATIONDATE, Date HOLDDATE, Date UNHOLDDATE,
			String CURRENCYID, String STAGE, String REFERENCE,
			String FA_ENTRIES_GENERATED, String CREATEDBY, String AUTHORIZEDBY,
			Date AUTHORIZATIONDATE, Integer BRANCHID, Integer PRODUCTID,
			Integer PDCBBRANCHID, String MC_STATUS, Date MC_DATE,
			String MC_REMARKS, String REF_NO, String STAGEID, Integer TXNID,
			String AUTOALLOC, String FINALALLOCFLAG, Integer REASONID,
			String ACTIONID, String BOUNCECHARGE, String MULTI_LOAN,
			Date PRESENTATIONDATE, Long BATCHNO, Integer RECEIPT_NO,
			String BATCHID, Date BATCHDATE, String INSTRUMENT,
			String FINWARE_ACNO, Date DATELASTUPDT, Byte DEST_BANK_ACCTYPE,
			String DEST_ACC_HOLDER, String MICR_CODE, String PDC_TYPE,
			String PDC_BY, String PDC_BY_NAME, String PDC_RETURNED_FLAG,
			Integer SERVICE_BRANCH, String INBATCH_NO, String OLD_INBATCH_NO,
			Integer DISBURSAL_NO, String RECEIPTNO, String RECEIPT_CHANNEL,
			Integer AGENCYID, String MICR_FLAG, String PAYSLIPNO,
			String CITYID, String BANKID, String BANKBRANCHID,
			String RLS_HISTORY_FLAG, String RECEIPT_FOR, String KO_LOGIC) {
		this.CHEQUEID = CHEQUEID;
		this.CHEQUETYPE = CHEQUETYPE;
		this.DEALINGBANKID = DEALINGBANKID;
		this.PAYMENTMODE = PAYMENTMODE;
		this.CHEQUENUM = CHEQUENUM;
		this.CHEQUEDATE = CHEQUEDATE;
		this.CHEQUEAMT = CHEQUEAMT;
		this.DRAWNON = DRAWNON;
		this.INFAVOUROF = INFAVOUROF;
		this.TOWARDS = TOWARDS;
		this.CITY = CITY;
		this.PDCFLAG = PDCFLAG;
		this.CRNNUM = CRNNUM;
		this.MODULEID = MODULEID;
		this.ORIGMODULEID = ORIGMODULEID;
		this.STATUS = STATUS;
		this.CHEQUESENTDATE = CHEQUESENTDATE;
		this.DEPOSITDATE = DEPOSITDATE;
		this.REALIZATIONDATE = REALIZATIONDATE;
		this.CLEAREDAMT = CLEAREDAMT;
		this.OLDCHEQUEID = OLDCHEQUEID;
		this.BPTYPE = BPTYPE;
		this.BPID = BPID;
		this.FILENUM = FILENUM;
		this.REMARKS = REMARKS;
		this.ALLOCATEFLAG = ALLOCATEFLAG;
		this.TXNREVERSEFLAG = TXNREVERSEFLAG;
		this.FORWARDDATE = FORWARDDATE;
		this.INTRADIVRECDATE = INTRADIVRECDATE;
		this.TXNDATE = TXNDATE;
		this.CREATIONDATE = CREATIONDATE;
		this.HOLDDATE = HOLDDATE;
		this.UNHOLDDATE = UNHOLDDATE;
		this.CURRENCYID = CURRENCYID;
		this.STAGE = STAGE;
		this.REFERENCE = REFERENCE;
		this.FA_ENTRIES_GENERATED = FA_ENTRIES_GENERATED;
		this.CREATEDBY = CREATEDBY;
		this.AUTHORIZEDBY = AUTHORIZEDBY;
		this.AUTHORIZATIONDATE = AUTHORIZATIONDATE;
		this.BRANCHID = BRANCHID;
		this.PRODUCTID = PRODUCTID;
		this.PDCBBRANCHID = PDCBBRANCHID;
		this.MC_STATUS = MC_STATUS;
		this.MC_DATE = MC_DATE;
		this.MC_REMARKS = MC_REMARKS;
		this.REF_NO = REF_NO;
		this.STAGEID = STAGEID;
		this.TXNID = TXNID;
		this.AUTOALLOC = AUTOALLOC;
		this.FINALALLOCFLAG = FINALALLOCFLAG;
		this.REASONID = REASONID;
		this.ACTIONID = ACTIONID;
		this.BOUNCECHARGE = BOUNCECHARGE;
		this.MULTI_LOAN = MULTI_LOAN;
		this.PRESENTATIONDATE = PRESENTATIONDATE;
		this.BATCHNO = BATCHNO;
		this.RECEIPT_NO = RECEIPT_NO;
		this.BATCHID = BATCHID;
		this.BATCHDATE = BATCHDATE;
		this.INSTRUMENT = INSTRUMENT;
		this.FINWARE_ACNO = FINWARE_ACNO;
		this.DATELASTUPDT = DATELASTUPDT;
		this.DEST_BANK_ACCTYPE = DEST_BANK_ACCTYPE;
		this.DEST_ACC_HOLDER = DEST_ACC_HOLDER;
		this.MICR_CODE = MICR_CODE;
		this.PDC_TYPE = PDC_TYPE;
		this.PDC_BY = PDC_BY;
		this.PDC_BY_NAME = PDC_BY_NAME;
		this.PDC_RETURNED_FLAG = PDC_RETURNED_FLAG;
		this.SERVICE_BRANCH = SERVICE_BRANCH;
		this.INBATCH_NO = INBATCH_NO;
		this.OLD_INBATCH_NO = OLD_INBATCH_NO;
		this.DISBURSAL_NO = DISBURSAL_NO;
		this.RECEIPTNO = RECEIPTNO;
		this.RECEIPT_CHANNEL = RECEIPT_CHANNEL;
		this.AGENCYID = AGENCYID;
		this.MICR_FLAG = MICR_FLAG;
		this.PAYSLIPNO = PAYSLIPNO;
		this.CITYID = CITYID;
		this.BANKID = BANKID;
		this.BANKBRANCHID = BANKBRANCHID;
		this.RLS_HISTORY_FLAG = RLS_HISTORY_FLAG;
		this.RECEIPT_FOR = RECEIPT_FOR;
		this.KO_LOGIC = KO_LOGIC;
	}

	public int getCHEQUEID() {
		return this.CHEQUEID;
	}

	public void setCHEQUEID(int CHEQUEID) {
		this.CHEQUEID = CHEQUEID;
	}

	public String getCHEQUETYPE() {
		return this.CHEQUETYPE;
	}

	public void setCHEQUETYPE(String CHEQUETYPE) {
		this.CHEQUETYPE = CHEQUETYPE;
	}

	public Integer getDEALINGBANKID() {
		return this.DEALINGBANKID;
	}

	public void setDEALINGBANKID(Integer DEALINGBANKID) {
		this.DEALINGBANKID = DEALINGBANKID;
	}

	public String getPAYMENTMODE() {
		return this.PAYMENTMODE;
	}

	public void setPAYMENTMODE(String PAYMENTMODE) {
		this.PAYMENTMODE = PAYMENTMODE;
	}

	public String getCHEQUENUM() {
		return this.CHEQUENUM;
	}

	public void setCHEQUENUM(String CHEQUENUM) {
		this.CHEQUENUM = CHEQUENUM;
	}

	public Date getCHEQUEDATE() {
		return this.CHEQUEDATE;
	}

	public void setCHEQUEDATE(Date CHEQUEDATE) {
		this.CHEQUEDATE = CHEQUEDATE;
	}

	public BigDecimal getCHEQUEAMT() {
		return this.CHEQUEAMT;
	}

	public void setCHEQUEAMT(BigDecimal CHEQUEAMT) {
		this.CHEQUEAMT = CHEQUEAMT;
	}

	public String getDRAWNON() {
		return this.DRAWNON;
	}

	public void setDRAWNON(String DRAWNON) {
		this.DRAWNON = DRAWNON;
	}

	public String getINFAVOUROF() {
		return this.INFAVOUROF;
	}

	public void setINFAVOUROF(String INFAVOUROF) {
		this.INFAVOUROF = INFAVOUROF;
	}

	public String getTOWARDS() {
		return this.TOWARDS;
	}

	public void setTOWARDS(String TOWARDS) {
		this.TOWARDS = TOWARDS;
	}

	public String getCITY() {
		return this.CITY;
	}

	public void setCITY(String CITY) {
		this.CITY = CITY;
	}

	public String getPDCFLAG() {
		return this.PDCFLAG;
	}

	public void setPDCFLAG(String PDCFLAG) {
		this.PDCFLAG = PDCFLAG;
	}

	public Long getCRNNUM() {
		return this.CRNNUM;
	}

	public void setCRNNUM(Long CRNNUM) {
		this.CRNNUM = CRNNUM;
	}

	public String getMODULEID() {
		return this.MODULEID;
	}

	public void setMODULEID(String MODULEID) {
		this.MODULEID = MODULEID;
	}

	public String getORIGMODULEID() {
		return this.ORIGMODULEID;
	}

	public void setORIGMODULEID(String ORIGMODULEID) {
		this.ORIGMODULEID = ORIGMODULEID;
	}

	public String getSTATUS() {
		return this.STATUS;
	}

	public void setSTATUS(String STATUS) {
		this.STATUS = STATUS;
	}

	public Date getCHEQUESENTDATE() {
		return this.CHEQUESENTDATE;
	}

	public void setCHEQUESENTDATE(Date CHEQUESENTDATE) {
		this.CHEQUESENTDATE = CHEQUESENTDATE;
	}

	public Date getDEPOSITDATE() {
		return this.DEPOSITDATE;
	}

	public void setDEPOSITDATE(Date DEPOSITDATE) {
		this.DEPOSITDATE = DEPOSITDATE;
	}

	public Date getREALIZATIONDATE() {
		return this.REALIZATIONDATE;
	}

	public void setREALIZATIONDATE(Date REALIZATIONDATE) {
		this.REALIZATIONDATE = REALIZATIONDATE;
	}

	public BigDecimal getCLEAREDAMT() {
		return this.CLEAREDAMT;
	}

	public void setCLEAREDAMT(BigDecimal CLEAREDAMT) {
		this.CLEAREDAMT = CLEAREDAMT;
	}

	public Integer getOLDCHEQUEID() {
		return this.OLDCHEQUEID;
	}

	public void setOLDCHEQUEID(Integer OLDCHEQUEID) {
		this.OLDCHEQUEID = OLDCHEQUEID;
	}

	public String getBPTYPE() {
		return this.BPTYPE;
	}

	public void setBPTYPE(String BPTYPE) {
		this.BPTYPE = BPTYPE;
	}

	public Integer getBPID() {
		return this.BPID;
	}

	public void setBPID(Integer BPID) {
		this.BPID = BPID;
	}

	public String getFILENUM() {
		return this.FILENUM;
	}

	public void setFILENUM(String FILENUM) {
		this.FILENUM = FILENUM;
	}

	public String getREMARKS() {
		return this.REMARKS;
	}

	public void setREMARKS(String REMARKS) {
		this.REMARKS = REMARKS;
	}

	public String getALLOCATEFLAG() {
		return this.ALLOCATEFLAG;
	}

	public void setALLOCATEFLAG(String ALLOCATEFLAG) {
		this.ALLOCATEFLAG = ALLOCATEFLAG;
	}

	public String getTXNREVERSEFLAG() {
		return this.TXNREVERSEFLAG;
	}

	public void setTXNREVERSEFLAG(String TXNREVERSEFLAG) {
		this.TXNREVERSEFLAG = TXNREVERSEFLAG;
	}

	public Date getFORWARDDATE() {
		return this.FORWARDDATE;
	}

	public void setFORWARDDATE(Date FORWARDDATE) {
		this.FORWARDDATE = FORWARDDATE;
	}

	public Date getINTRADIVRECDATE() {
		return this.INTRADIVRECDATE;
	}

	public void setINTRADIVRECDATE(Date INTRADIVRECDATE) {
		this.INTRADIVRECDATE = INTRADIVRECDATE;
	}

	public Date getTXNDATE() {
		return this.TXNDATE;
	}

	public void setTXNDATE(Date TXNDATE) {
		this.TXNDATE = TXNDATE;
	}

	public Date getCREATIONDATE() {
		return this.CREATIONDATE;
	}

	public void setCREATIONDATE(Date CREATIONDATE) {
		this.CREATIONDATE = CREATIONDATE;
	}

	public Date getHOLDDATE() {
		return this.HOLDDATE;
	}

	public void setHOLDDATE(Date HOLDDATE) {
		this.HOLDDATE = HOLDDATE;
	}

	public Date getUNHOLDDATE() {
		return this.UNHOLDDATE;
	}

	public void setUNHOLDDATE(Date UNHOLDDATE) {
		this.UNHOLDDATE = UNHOLDDATE;
	}

	public String getCURRENCYID() {
		return this.CURRENCYID;
	}

	public void setCURRENCYID(String CURRENCYID) {
		this.CURRENCYID = CURRENCYID;
	}

	public String getSTAGE() {
		return this.STAGE;
	}

	public void setSTAGE(String STAGE) {
		this.STAGE = STAGE;
	}

	public String getREFERENCE() {
		return this.REFERENCE;
	}

	public void setREFERENCE(String REFERENCE) {
		this.REFERENCE = REFERENCE;
	}

	public String getFA_ENTRIES_GENERATED() {
		return this.FA_ENTRIES_GENERATED;
	}

	public void setFA_ENTRIES_GENERATED(String FA_ENTRIES_GENERATED) {
		this.FA_ENTRIES_GENERATED = FA_ENTRIES_GENERATED;
	}

	public String getCREATEDBY() {
		return this.CREATEDBY;
	}

	public void setCREATEDBY(String CREATEDBY) {
		this.CREATEDBY = CREATEDBY;
	}

	public String getAUTHORIZEDBY() {
		return this.AUTHORIZEDBY;
	}

	public void setAUTHORIZEDBY(String AUTHORIZEDBY) {
		this.AUTHORIZEDBY = AUTHORIZEDBY;
	}

	public Date getAUTHORIZATIONDATE() {
		return this.AUTHORIZATIONDATE;
	}

	public void setAUTHORIZATIONDATE(Date AUTHORIZATIONDATE) {
		this.AUTHORIZATIONDATE = AUTHORIZATIONDATE;
	}

	public Integer getBRANCHID() {
		return this.BRANCHID;
	}

	public void setBRANCHID(Integer BRANCHID) {
		this.BRANCHID = BRANCHID;
	}

	public Integer getPRODUCTID() {
		return this.PRODUCTID;
	}

	public void setPRODUCTID(Integer PRODUCTID) {
		this.PRODUCTID = PRODUCTID;
	}

	public Integer getPDCBBRANCHID() {
		return this.PDCBBRANCHID;
	}

	public void setPDCBBRANCHID(Integer PDCBBRANCHID) {
		this.PDCBBRANCHID = PDCBBRANCHID;
	}

	public String getMC_STATUS() {
		return this.MC_STATUS;
	}

	public void setMC_STATUS(String MC_STATUS) {
		this.MC_STATUS = MC_STATUS;
	}

	public Date getMC_DATE() {
		return this.MC_DATE;
	}

	public void setMC_DATE(Date MC_DATE) {
		this.MC_DATE = MC_DATE;
	}

	public String getMC_REMARKS() {
		return this.MC_REMARKS;
	}

	public void setMC_REMARKS(String MC_REMARKS) {
		this.MC_REMARKS = MC_REMARKS;
	}

	public String getREF_NO() {
		return this.REF_NO;
	}

	public void setREF_NO(String REF_NO) {
		this.REF_NO = REF_NO;
	}

	public String getSTAGEID() {
		return this.STAGEID;
	}

	public void setSTAGEID(String STAGEID) {
		this.STAGEID = STAGEID;
	}

	public Integer getTXNID() {
		return this.TXNID;
	}

	public void setTXNID(Integer TXNID) {
		this.TXNID = TXNID;
	}

	public String getAUTOALLOC() {
		return this.AUTOALLOC;
	}

	public void setAUTOALLOC(String AUTOALLOC) {
		this.AUTOALLOC = AUTOALLOC;
	}

	public String getFINALALLOCFLAG() {
		return this.FINALALLOCFLAG;
	}

	public void setFINALALLOCFLAG(String FINALALLOCFLAG) {
		this.FINALALLOCFLAG = FINALALLOCFLAG;
	}

	public Integer getREASONID() {
		return this.REASONID;
	}

	public void setREASONID(Integer REASONID) {
		this.REASONID = REASONID;
	}

	public String getACTIONID() {
		return this.ACTIONID;
	}

	public void setACTIONID(String ACTIONID) {
		this.ACTIONID = ACTIONID;
	}

	public String getBOUNCECHARGE() {
		return this.BOUNCECHARGE;
	}

	public void setBOUNCECHARGE(String BOUNCECHARGE) {
		this.BOUNCECHARGE = BOUNCECHARGE;
	}

	public String getMULTI_LOAN() {
		return this.MULTI_LOAN;
	}

	public void setMULTI_LOAN(String MULTI_LOAN) {
		this.MULTI_LOAN = MULTI_LOAN;
	}

	public Date getPRESENTATIONDATE() {
		return this.PRESENTATIONDATE;
	}

	public void setPRESENTATIONDATE(Date PRESENTATIONDATE) {
		this.PRESENTATIONDATE = PRESENTATIONDATE;
	}

	public Long getBATCHNO() {
		return this.BATCHNO;
	}

	public void setBATCHNO(Long BATCHNO) {
		this.BATCHNO = BATCHNO;
	}

	public Integer getRECEIPT_NO() {
		return this.RECEIPT_NO;
	}

	public void setRECEIPT_NO(Integer RECEIPT_NO) {
		this.RECEIPT_NO = RECEIPT_NO;
	}

	public String getBATCHID() {
		return this.BATCHID;
	}

	public void setBATCHID(String BATCHID) {
		this.BATCHID = BATCHID;
	}

	public Date getBATCHDATE() {
		return this.BATCHDATE;
	}

	public void setBATCHDATE(Date BATCHDATE) {
		this.BATCHDATE = BATCHDATE;
	}

	public String getINSTRUMENT() {
		return this.INSTRUMENT;
	}

	public void setINSTRUMENT(String INSTRUMENT) {
		this.INSTRUMENT = INSTRUMENT;
	}

	public String getFINWARE_ACNO() {
		return this.FINWARE_ACNO;
	}

	public void setFINWARE_ACNO(String FINWARE_ACNO) {
		this.FINWARE_ACNO = FINWARE_ACNO;
	}

	public Date getDATELASTUPDT() {
		return this.DATELASTUPDT;
	}

	public void setDATELASTUPDT(Date DATELASTUPDT) {
		this.DATELASTUPDT = DATELASTUPDT;
	}

	public Byte getDEST_BANK_ACCTYPE() {
		return this.DEST_BANK_ACCTYPE;
	}

	public void setDEST_BANK_ACCTYPE(Byte DEST_BANK_ACCTYPE) {
		this.DEST_BANK_ACCTYPE = DEST_BANK_ACCTYPE;
	}

	public String getDEST_ACC_HOLDER() {
		return this.DEST_ACC_HOLDER;
	}

	public void setDEST_ACC_HOLDER(String DEST_ACC_HOLDER) {
		this.DEST_ACC_HOLDER = DEST_ACC_HOLDER;
	}

	public String getMICR_CODE() {
		return this.MICR_CODE;
	}

	public void setMICR_CODE(String MICR_CODE) {
		this.MICR_CODE = MICR_CODE;
	}

	public String getPDC_TYPE() {
		return this.PDC_TYPE;
	}

	public void setPDC_TYPE(String PDC_TYPE) {
		this.PDC_TYPE = PDC_TYPE;
	}

	public String getPDC_BY() {
		return this.PDC_BY;
	}

	public void setPDC_BY(String PDC_BY) {
		this.PDC_BY = PDC_BY;
	}

	public String getPDC_BY_NAME() {
		return this.PDC_BY_NAME;
	}

	public void setPDC_BY_NAME(String PDC_BY_NAME) {
		this.PDC_BY_NAME = PDC_BY_NAME;
	}

	public String getPDC_RETURNED_FLAG() {
		return this.PDC_RETURNED_FLAG;
	}

	public void setPDC_RETURNED_FLAG(String PDC_RETURNED_FLAG) {
		this.PDC_RETURNED_FLAG = PDC_RETURNED_FLAG;
	}

	public Integer getSERVICE_BRANCH() {
		return this.SERVICE_BRANCH;
	}

	public void setSERVICE_BRANCH(Integer SERVICE_BRANCH) {
		this.SERVICE_BRANCH = SERVICE_BRANCH;
	}

	public String getINBATCH_NO() {
		return this.INBATCH_NO;
	}

	public void setINBATCH_NO(String INBATCH_NO) {
		this.INBATCH_NO = INBATCH_NO;
	}

	public String getOLD_INBATCH_NO() {
		return this.OLD_INBATCH_NO;
	}

	public void setOLD_INBATCH_NO(String OLD_INBATCH_NO) {
		this.OLD_INBATCH_NO = OLD_INBATCH_NO;
	}

	public Integer getDISBURSAL_NO() {
		return this.DISBURSAL_NO;
	}

	public void setDISBURSAL_NO(Integer DISBURSAL_NO) {
		this.DISBURSAL_NO = DISBURSAL_NO;
	}

	public String getRECEIPTNO() {
		return this.RECEIPTNO;
	}

	public void setRECEIPTNO(String RECEIPTNO) {
		this.RECEIPTNO = RECEIPTNO;
	}

	public String getRECEIPT_CHANNEL() {
		return this.RECEIPT_CHANNEL;
	}

	public void setRECEIPT_CHANNEL(String RECEIPT_CHANNEL) {
		this.RECEIPT_CHANNEL = RECEIPT_CHANNEL;
	}

	public Integer getAGENCYID() {
		return this.AGENCYID;
	}

	public void setAGENCYID(Integer AGENCYID) {
		this.AGENCYID = AGENCYID;
	}

	public String getMICR_FLAG() {
		return this.MICR_FLAG;
	}

	public void setMICR_FLAG(String MICR_FLAG) {
		this.MICR_FLAG = MICR_FLAG;
	}

	public String getPAYSLIPNO() {
		return this.PAYSLIPNO;
	}

	public void setPAYSLIPNO(String PAYSLIPNO) {
		this.PAYSLIPNO = PAYSLIPNO;
	}

	public String getCITYID() {
		return this.CITYID;
	}

	public void setCITYID(String CITYID) {
		this.CITYID = CITYID;
	}

	public String getBANKID() {
		return this.BANKID;
	}

	public void setBANKID(String BANKID) {
		this.BANKID = BANKID;
	}

	public String getBANKBRANCHID() {
		return this.BANKBRANCHID;
	}

	public void setBANKBRANCHID(String BANKBRANCHID) {
		this.BANKBRANCHID = BANKBRANCHID;
	}

	public String getRLS_HISTORY_FLAG() {
		return this.RLS_HISTORY_FLAG;
	}

	public void setRLS_HISTORY_FLAG(String RLS_HISTORY_FLAG) {
		this.RLS_HISTORY_FLAG = RLS_HISTORY_FLAG;
	}

	public String getRECEIPT_FOR() {
		return this.RECEIPT_FOR;
	}

	public void setRECEIPT_FOR(String RECEIPT_FOR) {
		this.RECEIPT_FOR = RECEIPT_FOR;
	}

	public String getKO_LOGIC() {
		return this.KO_LOGIC;
	}

	public void setKO_LOGIC(String KO_LOGIC) {
		this.KO_LOGIC = KO_LOGIC;
	}

}
