package com.pruvn.tools.common.hibernate.finnone.printsrv;

// Generated May 31, 2011 2:37:34 PM by Hibernate Tools 3.2.4.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ONT_SOA_M generated by hbm2java
 */
public class ONT_SOA_M implements java.io.Serializable {

	private BigDecimal APPLID;
	private String AGREEMENTNO;
	private String CUSTOMERNAME;
	private String ADDRL1;
	private String ADDRL2;
	private String ADDRL3;
	private Date DISBURSALDATE;
	private BigDecimal CUSTOMERID;
	private String PHONE;
	private String PRODUCT;
	private String PRODDESC;
	private BigDecimal TENURE;
	private Date REPAYMENTFIRST;
	private Date REPAYMENTLAST;
	private BigDecimal LOANAMOUNT;
	private BigDecimal FIRSTAMOUNT;
	private BigDecimal SEMIFINALAMT;
	private BigDecimal FINALAMT;
	private String DUEDATE;
	private BigDecimal ADVEMI;
	private String BRANCHDESC;

	public ONT_SOA_M() {
	}

	public ONT_SOA_M(BigDecimal APPLID) {
		this.APPLID = APPLID;
	}

	public ONT_SOA_M(BigDecimal APPLID, String AGREEMENTNO,
			String CUSTOMERNAME, String ADDRL1, String ADDRL2, String ADDRL3,
			Date DISBURSALDATE, BigDecimal CUSTOMERID, String PHONE,
			String PRODUCT, String PRODDESC, BigDecimal TENURE,
			Date REPAYMENTFIRST, Date REPAYMENTLAST, BigDecimal LOANAMOUNT,
			BigDecimal FIRSTAMOUNT, BigDecimal SEMIFINALAMT,
			BigDecimal FINALAMT, String DUEDATE, BigDecimal ADVEMI,
			String BRANCHDESC) {
		this.APPLID = APPLID;
		this.AGREEMENTNO = AGREEMENTNO;
		this.CUSTOMERNAME = CUSTOMERNAME;
		this.ADDRL1 = ADDRL1;
		this.ADDRL2 = ADDRL2;
		this.ADDRL3 = ADDRL3;
		this.DISBURSALDATE = DISBURSALDATE;
		this.CUSTOMERID = CUSTOMERID;
		this.PHONE = PHONE;
		this.PRODUCT = PRODUCT;
		this.PRODDESC = PRODDESC;
		this.TENURE = TENURE;
		this.REPAYMENTFIRST = REPAYMENTFIRST;
		this.REPAYMENTLAST = REPAYMENTLAST;
		this.LOANAMOUNT = LOANAMOUNT;
		this.FIRSTAMOUNT = FIRSTAMOUNT;
		this.SEMIFINALAMT = SEMIFINALAMT;
		this.FINALAMT = FINALAMT;
		this.DUEDATE = DUEDATE;
		this.ADVEMI = ADVEMI;
		this.BRANCHDESC = BRANCHDESC;
	}

	public BigDecimal getAPPLID() {
		return this.APPLID;
	}

	public void setAPPLID(BigDecimal APPLID) {
		this.APPLID = APPLID;
	}

	public String getAGREEMENTNO() {
		return this.AGREEMENTNO;
	}

	public void setAGREEMENTNO(String AGREEMENTNO) {
		this.AGREEMENTNO = AGREEMENTNO;
	}

	public String getCUSTOMERNAME() {
		return this.CUSTOMERNAME;
	}

	public void setCUSTOMERNAME(String CUSTOMERNAME) {
		this.CUSTOMERNAME = CUSTOMERNAME;
	}

	public String getADDRL1() {
		return this.ADDRL1;
	}

	public void setADDRL1(String ADDRL1) {
		this.ADDRL1 = ADDRL1;
	}

	public String getADDRL2() {
		return this.ADDRL2;
	}

	public void setADDRL2(String ADDRL2) {
		this.ADDRL2 = ADDRL2;
	}

	public String getADDRL3() {
		return this.ADDRL3;
	}

	public void setADDRL3(String ADDRL3) {
		this.ADDRL3 = ADDRL3;
	}

	public Date getDISBURSALDATE() {
		return this.DISBURSALDATE;
	}

	public void setDISBURSALDATE(Date DISBURSALDATE) {
		this.DISBURSALDATE = DISBURSALDATE;
	}

	public BigDecimal getCUSTOMERID() {
		return this.CUSTOMERID;
	}

	public void setCUSTOMERID(BigDecimal CUSTOMERID) {
		this.CUSTOMERID = CUSTOMERID;
	}

	public String getPHONE() {
		return this.PHONE;
	}

	public void setPHONE(String PHONE) {
		this.PHONE = PHONE;
	}

	public String getPRODUCT() {
		return this.PRODUCT;
	}

	public void setPRODUCT(String PRODUCT) {
		this.PRODUCT = PRODUCT;
	}

	public String getPRODDESC() {
		return this.PRODDESC;
	}

	public void setPRODDESC(String PRODDESC) {
		this.PRODDESC = PRODDESC;
	}

	public BigDecimal getTENURE() {
		return this.TENURE;
	}

	public void setTENURE(BigDecimal TENURE) {
		this.TENURE = TENURE;
	}

	public Date getREPAYMENTFIRST() {
		return this.REPAYMENTFIRST;
	}

	public void setREPAYMENTFIRST(Date REPAYMENTFIRST) {
		this.REPAYMENTFIRST = REPAYMENTFIRST;
	}

	public Date getREPAYMENTLAST() {
		return this.REPAYMENTLAST;
	}

	public void setREPAYMENTLAST(Date REPAYMENTLAST) {
		this.REPAYMENTLAST = REPAYMENTLAST;
	}

	public BigDecimal getLOANAMOUNT() {
		return this.LOANAMOUNT;
	}

	public void setLOANAMOUNT(BigDecimal LOANAMOUNT) {
		this.LOANAMOUNT = LOANAMOUNT;
	}

	public BigDecimal getFIRSTAMOUNT() {
		return this.FIRSTAMOUNT;
	}

	public void setFIRSTAMOUNT(BigDecimal FIRSTAMOUNT) {
		this.FIRSTAMOUNT = FIRSTAMOUNT;
	}

	public BigDecimal getSEMIFINALAMT() {
		return this.SEMIFINALAMT;
	}

	public void setSEMIFINALAMT(BigDecimal SEMIFINALAMT) {
		this.SEMIFINALAMT = SEMIFINALAMT;
	}

	public BigDecimal getFINALAMT() {
		return this.FINALAMT;
	}

	public void setFINALAMT(BigDecimal FINALAMT) {
		this.FINALAMT = FINALAMT;
	}

	public String getDUEDATE() {
		return this.DUEDATE;
	}

	public void setDUEDATE(String DUEDATE) {
		this.DUEDATE = DUEDATE;
	}

	public BigDecimal getADVEMI() {
		return this.ADVEMI;
	}

	public void setADVEMI(BigDecimal ADVEMI) {
		this.ADVEMI = ADVEMI;
	}

	public String getBRANCHDESC() {
		return this.BRANCHDESC;
	}

	public void setBRANCHDESC(String BRANCHDESC) {
		this.BRANCHDESC = BRANCHDESC;
	}

}
