package com.pruvn.tools.common.hibernate.finnone.printsrv;

// Generated May 31, 2011 2:37:34 PM by Hibernate Tools 3.2.4.CR1

import java.util.Date;

/**
 * V_WS_LOAN_STATUS generated by hbm2java
 */
public class PRINTSRV_PRINTED_LOAN_M implements java.io.Serializable {

	private Integer ID;
	private Integer APP_ID_C;
	private String DOC_NAME;
	private String PRINTED_USER;
	private Date PRINTED_DATE;

	/**
	 * @return the iD
	 */
	public Integer getID() {
		return ID;
	}
	/**
	 * @param iD the iD to set
	 */
	public void setID(Integer iD) {
		ID = iD;
	}
	/**
	 * @return the aPP_ID_C
	 */
	public Integer getAPP_ID_C() {
		return APP_ID_C;
	}
	/**
	 * @param aPP_ID_C the aPP_ID_C to set
	 */
	public void setAPP_ID_C(Integer aPP_ID_C) {
		APP_ID_C = aPP_ID_C;
	}
	/**
	 * @return the dOC_NAME
	 */
	public String getDOC_NAME() {
		return DOC_NAME;
	}
	/**
	 * @param dOC_NAME the dOC_NAME to set
	 */
	public void setDOC_NAME(String dOC_NAME) {
		DOC_NAME = dOC_NAME;
	}
	/**
	 * @return the pRINTED_USER
	 */
	public String getPRINTED_USER() {
		return PRINTED_USER;
	}
	/**
	 * @param pRINTED_USER the pRINTED_USER to set
	 */
	public void setPRINTED_USER(String pRINTED_USER) {
		PRINTED_USER = pRINTED_USER;
	}
	/**
	 * @return the pRINTED_DATE
	 */
	public Date getPRINTED_DATE() {
		return PRINTED_DATE;
	}
	/**
	 * @param pRINTED_DATE the pRINTED_DATE to set
	 */
	public void setPRINTED_DATE(Date pRINTED_DATE) {
		PRINTED_DATE = pRINTED_DATE;
	}

	

}
