package com.pruvn.tools.common.hibernate.finnone.printsrv;

// Generated May 31, 2011 2:37:34 PM by Hibernate Tools 3.2.4.CR1

import java.math.BigDecimal;

/**
 * V_WS_LOAN_STATUS generated by hbm2java
 */
@SuppressWarnings("serial")
public class V_WS_LOAN_STATUS implements java.io.Serializable {

	private String APPLID;
	private String WSSTATUS;
	private BigDecimal PRINT_STATUS;
	private BigDecimal OLD_PRINT_STATUS;
	private String NPM_LPP_PRODCAT_C;
	private String RO_NAME;
	private BigDecimal EXCESS_AMOUNT;
	private String AGREEMENTNO;

	public V_WS_LOAN_STATUS() {
	}

	public V_WS_LOAN_STATUS(String APPLID) {
		this.APPLID = APPLID;
	}

	public V_WS_LOAN_STATUS(String APPLID, String WSSTATUS,
			BigDecimal PRINT_STATUS, BigDecimal OLD_PRINT_STATUS,
			String NPM_LPP_PRODCAT_C, String RO_NAME, BigDecimal EXCESS_AMOUNT,
			String AGREEMENTNO) {
		this.APPLID = APPLID;
		this.WSSTATUS = WSSTATUS;
		this.PRINT_STATUS = PRINT_STATUS;
		this.OLD_PRINT_STATUS = OLD_PRINT_STATUS;
		this.NPM_LPP_PRODCAT_C = NPM_LPP_PRODCAT_C;
		this.RO_NAME = RO_NAME;
		this.EXCESS_AMOUNT = EXCESS_AMOUNT;
		this.AGREEMENTNO = AGREEMENTNO;
	}

	public String getAPPLID() {
		return this.APPLID;
	}

	public void setAPPLID(String APPLID) {
		this.APPLID = APPLID;
	}

	public String getWSSTATUS() {
		return this.WSSTATUS;
	}

	public void setWSSTATUS(String WSSTATUS) {
		this.WSSTATUS = WSSTATUS;
	}

	public BigDecimal getPRINT_STATUS() {
		return this.PRINT_STATUS;
	}

	public void setPRINT_STATUS(BigDecimal PRINT_STATUS) {
		this.PRINT_STATUS = PRINT_STATUS;
	}

	public BigDecimal getOLD_PRINT_STATUS() {
		return this.OLD_PRINT_STATUS;
	}

	public void setOLD_PRINT_STATUS(BigDecimal OLD_PRINT_STATUS) {
		this.OLD_PRINT_STATUS = OLD_PRINT_STATUS;
	}

	public String getNPM_LPP_PRODCAT_C() {
		return this.NPM_LPP_PRODCAT_C;
	}

	public void setNPM_LPP_PRODCAT_C(String NPM_LPP_PRODCAT_C) {
		this.NPM_LPP_PRODCAT_C = NPM_LPP_PRODCAT_C;
	}

	public String getRO_NAME() {
		return this.RO_NAME;
	}

	public void setRO_NAME(String RO_NAME) {
		this.RO_NAME = RO_NAME;
	}

	public BigDecimal getEXCESS_AMOUNT() {
		return this.EXCESS_AMOUNT;
	}

	public void setEXCESS_AMOUNT(BigDecimal EXCESS_AMOUNT) {
		this.EXCESS_AMOUNT = EXCESS_AMOUNT;
	}

	public String getAGREEMENTNO() {
		return this.AGREEMENTNO;
	}

	public void setAGREEMENTNO(String AGREEMENTNO) {
		this.AGREEMENTNO = AGREEMENTNO;
	}

}
