/*
 * Java bean class for entity table RM_BRANCH 
 * Created on 3 Oct 2013 ( Time 12:18:02 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.service.impl;

import java.util.ArrayList;
import java.util.List;

import org.apache.log4j.Logger;
import org.springframework.stereotype.Service;

import com.pruvn.rms.dao.BranchDao;
import com.pruvn.rms.domain.Branch;
import com.pruvn.rms.domain.GroupM;
import com.pruvn.rms.service.BranchService;
import com.pruvn.rms.service.abstracts.GenericServiceImpl;


/**
 * Service implementation for table "RM_BRANCH"
 * 
 * @author Telosys Tools Generator
 *
 */


@Service("rmBranchService")
public class BranchServiceImpl extends GenericServiceImpl<BranchDao, Branch,Integer>  implements BranchService
{
   private static final Logger logger = Logger.getLogger(BranchServiceImpl.class);
	
	/**
	 * Find RmBranch by code
	 */
	@Override
	public Branch findBycode(String code) {
		/*logger.debug("Begin executing findBycode method...");
		List<Branch> lstRet = new ArrayList<Branch>();
		List<Branch> bos = dao.findBycode(code);
		for (Branch item : bos) {
			lstRet.add(mapper.map(item, Branch.class));
		}
		
		logger.debug("End executing findBycode method, returning value...");
		return lstRet.get(0);*/
		List<Branch> list = dao.findBycode(code);
		return list != null && list.size() > 0 ? list.get(0) : null;
	}
	
	/**
	 * Find RmBranch by name
	 */
	@Override
	public List<Branch> findByname(String name) {
		/*logger.debug("Begin executing findByname method...");
		List<Branch> lstRet = new ArrayList<Branch>();
		List<Branch> bos = dao.findByname(name);
		for (Branch item : bos) {
			lstRet.add(mapper.map(item, Branch.class));
		}
		
		logger.debug("End executing findByname method, returning value...");
		return lstRet;*/
		return dao.findByname(name);
	}
}