/*
 * Java bean class for entity table RM_SCREEN 
 * Created on 3 Oct 2013 ( Time 12:18:02 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.service.impl;

import java.util.List;

import org.apache.log4j.Logger;
import org.springframework.stereotype.Service;

import com.pruvn.rms.dao.ScreenDao;
import com.pruvn.rms.domain.Screen;
import com.pruvn.rms.service.ScreenService;
import com.pruvn.rms.service.abstracts.GenericServiceImpl;


/**
 * Service implementation for table "RM_SCREEN"
 * 
 * @author Telosys Tools Generator
 *
 */


@Service("rmScreenService")
public class ScreenServiceImpl extends GenericServiceImpl<ScreenDao, Screen,Integer>  implements ScreenService
{
   private static final Logger logger = Logger.getLogger(ScreenServiceImpl.class);
	
	/**
	 * Find RmScreen by code
	 */
	@Override
	public Screen findByStage(String stage) {
		List<Screen> list = dao.findByStage(stage);
		return list != null && list.size() > 0 ? list.get(0) : null;
	}
	
	/**
	 * Find RmScreen by name
	 */
	@Override
	public List<Screen> findByname(String name) {
		return dao.findByname(name);
	}
}