/*
 * Java bean class for entity table user_level_a 
 * Created on 17 May 2013 ( Time 17:03:25 )
 * Generated by Telosys Tools Generator ( version 2.0.0 )
 */

package com.pruvn.rms.service.impl;

import java.util.ArrayList;
import java.util.List;

import org.apache.log4j.Logger;

import com.pruvn.rms.dao.UserLevelADao;
import com.pruvn.rms.domain.UserLevelA;
import com.pruvn.rms.domain.UserLevelM;
import com.pruvn.rms.domain.UserM;
import com.pruvn.rms.dto.UserLevelADto;
import com.pruvn.rms.service.UserLevelAService;
import com.pruvn.rms.service.abstracts.GenericServiceImpl;


/**
 * Service implementation for table "user_level_a"
 * 
 * @author Telosys Tools Generator
 *
 */
public class UserLevelAServiceImpl extends GenericServiceImpl<UserLevelADao, UserLevelA,Integer>  implements UserLevelAService
{
   private static final Logger logger = Logger.getLogger(UserLevelAServiceImpl.class);
	
	/**
	 * Find UserLevelA by userid
	 */
	@Override
	public UserLevelADto findByuserid(UserM userid) {
		logger.debug("Begin executing findByuserid method...");
		UserLevelA bos = dao.findByuserid(userid);
		if(bos == null) return null;
		logger.debug("End executing findByuserid method, returning value...");
		return mapper.map(bos, UserLevelADto.class);
	}
	
	/**
	 * Find UserLevelA by levelid
	 */
	@Override
	public List<UserLevelADto> findBylevelid(UserLevelM levelid) {
		logger.debug("Begin executing findBylevelid method...");
		List<UserLevelADto> lstRet = new ArrayList<UserLevelADto>();
		UserLevelA bos = dao.findBylevelid(levelid);
		lstRet.add(mapper.map(bos, UserLevelADto.class));
		
		logger.debug("End executing findBylevelid method, returning value...");
		return lstRet;
	}
	
}