package com.pruvn.tools.common.hibernate.finnone.cas;

// Generated May 31, 2011 2:37:34 PM by Hibernate Tools 3.2.4.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * LEA_SUPPLIER_M generated by hbm2java
 */
public class LEA_SUPPLIER_M implements java.io.Serializable {

	private int SUPPLIERID;
	private String SUPPLIERDESC;
	private String SSTNUM;
	private String CSTNUM;
	private String ITNUM;
	private String SUPPLIER_DEALER_FLAG;
	private String INTERNAL_FLAG;
	private BigDecimal DEALERCOMM;
	private String MC_STATUS;
	private String MAKERID;
	private Date MAKEDATE;
	private String AUTHID;
	private Date AUTHDATE;
	private Date DATELASTUPDT;
	private String BANKACNUM;
	private String VATACNUM;
	private BigDecimal AGGREGATELIMIT;
	private BigDecimal OS_RC_AMT;
	private String ACTIVE_STATUS;
	private Date VALID_FROM;
	private Date VALID_TO;
	private String PAN_NO;

	public LEA_SUPPLIER_M() {
	}

	public LEA_SUPPLIER_M(int SUPPLIERID, String SUPPLIERDESC,
			String MC_STATUS, String MAKERID, Date MAKEDATE, String AUTHID,
			Date AUTHDATE) {
		this.SUPPLIERID = SUPPLIERID;
		this.SUPPLIERDESC = SUPPLIERDESC;
		this.MC_STATUS = MC_STATUS;
		this.MAKERID = MAKERID;
		this.MAKEDATE = MAKEDATE;
		this.AUTHID = AUTHID;
		this.AUTHDATE = AUTHDATE;
	}

	public LEA_SUPPLIER_M(int SUPPLIERID, String SUPPLIERDESC, String SSTNUM,
			String CSTNUM, String ITNUM, String SUPPLIER_DEALER_FLAG,
			String INTERNAL_FLAG, BigDecimal DEALERCOMM, String MC_STATUS,
			String MAKERID, Date MAKEDATE, String AUTHID, Date AUTHDATE,
			Date DATELASTUPDT, String BANKACNUM, String VATACNUM,
			BigDecimal AGGREGATELIMIT, BigDecimal OS_RC_AMT,
			String ACTIVE_STATUS, Date VALID_FROM, Date VALID_TO, String PAN_NO) {
		this.SUPPLIERID = SUPPLIERID;
		this.SUPPLIERDESC = SUPPLIERDESC;
		this.SSTNUM = SSTNUM;
		this.CSTNUM = CSTNUM;
		this.ITNUM = ITNUM;
		this.SUPPLIER_DEALER_FLAG = SUPPLIER_DEALER_FLAG;
		this.INTERNAL_FLAG = INTERNAL_FLAG;
		this.DEALERCOMM = DEALERCOMM;
		this.MC_STATUS = MC_STATUS;
		this.MAKERID = MAKERID;
		this.MAKEDATE = MAKEDATE;
		this.AUTHID = AUTHID;
		this.AUTHDATE = AUTHDATE;
		this.DATELASTUPDT = DATELASTUPDT;
		this.BANKACNUM = BANKACNUM;
		this.VATACNUM = VATACNUM;
		this.AGGREGATELIMIT = AGGREGATELIMIT;
		this.OS_RC_AMT = OS_RC_AMT;
		this.ACTIVE_STATUS = ACTIVE_STATUS;
		this.VALID_FROM = VALID_FROM;
		this.VALID_TO = VALID_TO;
		this.PAN_NO = PAN_NO;
	}

	public int getSUPPLIERID() {
		return this.SUPPLIERID;
	}

	public void setSUPPLIERID(int SUPPLIERID) {
		this.SUPPLIERID = SUPPLIERID;
	}

	public String getSUPPLIERDESC() {
		return this.SUPPLIERDESC;
	}

	public void setSUPPLIERDESC(String SUPPLIERDESC) {
		this.SUPPLIERDESC = SUPPLIERDESC;
	}

	public String getSSTNUM() {
		return this.SSTNUM;
	}

	public void setSSTNUM(String SSTNUM) {
		this.SSTNUM = SSTNUM;
	}

	public String getCSTNUM() {
		return this.CSTNUM;
	}

	public void setCSTNUM(String CSTNUM) {
		this.CSTNUM = CSTNUM;
	}

	public String getITNUM() {
		return this.ITNUM;
	}

	public void setITNUM(String ITNUM) {
		this.ITNUM = ITNUM;
	}

	public String getSUPPLIER_DEALER_FLAG() {
		return this.SUPPLIER_DEALER_FLAG;
	}

	public void setSUPPLIER_DEALER_FLAG(String SUPPLIER_DEALER_FLAG) {
		this.SUPPLIER_DEALER_FLAG = SUPPLIER_DEALER_FLAG;
	}

	public String getINTERNAL_FLAG() {
		return this.INTERNAL_FLAG;
	}

	public void setINTERNAL_FLAG(String INTERNAL_FLAG) {
		this.INTERNAL_FLAG = INTERNAL_FLAG;
	}

	public BigDecimal getDEALERCOMM() {
		return this.DEALERCOMM;
	}

	public void setDEALERCOMM(BigDecimal DEALERCOMM) {
		this.DEALERCOMM = DEALERCOMM;
	}

	public String getMC_STATUS() {
		return this.MC_STATUS;
	}

	public void setMC_STATUS(String MC_STATUS) {
		this.MC_STATUS = MC_STATUS;
	}

	public String getMAKERID() {
		return this.MAKERID;
	}

	public void setMAKERID(String MAKERID) {
		this.MAKERID = MAKERID;
	}

	public Date getMAKEDATE() {
		return this.MAKEDATE;
	}

	public void setMAKEDATE(Date MAKEDATE) {
		this.MAKEDATE = MAKEDATE;
	}

	public String getAUTHID() {
		return this.AUTHID;
	}

	public void setAUTHID(String AUTHID) {
		this.AUTHID = AUTHID;
	}

	public Date getAUTHDATE() {
		return this.AUTHDATE;
	}

	public void setAUTHDATE(Date AUTHDATE) {
		this.AUTHDATE = AUTHDATE;
	}

	public Date getDATELASTUPDT() {
		return this.DATELASTUPDT;
	}

	public void setDATELASTUPDT(Date DATELASTUPDT) {
		this.DATELASTUPDT = DATELASTUPDT;
	}

	public String getBANKACNUM() {
		return this.BANKACNUM;
	}

	public void setBANKACNUM(String BANKACNUM) {
		this.BANKACNUM = BANKACNUM;
	}

	public String getVATACNUM() {
		return this.VATACNUM;
	}

	public void setVATACNUM(String VATACNUM) {
		this.VATACNUM = VATACNUM;
	}

	public BigDecimal getAGGREGATELIMIT() {
		return this.AGGREGATELIMIT;
	}

	public void setAGGREGATELIMIT(BigDecimal AGGREGATELIMIT) {
		this.AGGREGATELIMIT = AGGREGATELIMIT;
	}

	public BigDecimal getOS_RC_AMT() {
		return this.OS_RC_AMT;
	}

	public void setOS_RC_AMT(BigDecimal OS_RC_AMT) {
		this.OS_RC_AMT = OS_RC_AMT;
	}

	public String getACTIVE_STATUS() {
		return this.ACTIVE_STATUS;
	}

	public void setACTIVE_STATUS(String ACTIVE_STATUS) {
		this.ACTIVE_STATUS = ACTIVE_STATUS;
	}

	public Date getVALID_FROM() {
		return this.VALID_FROM;
	}

	public void setVALID_FROM(Date VALID_FROM) {
		this.VALID_FROM = VALID_FROM;
	}

	public Date getVALID_TO() {
		return this.VALID_TO;
	}

	public void setVALID_TO(Date VALID_TO) {
		this.VALID_TO = VALID_TO;
	}

	public String getPAN_NO() {
		return this.PAN_NO;
	}

	public void setPAN_NO(String PAN_NO) {
		this.PAN_NO = PAN_NO;
	}

}
