package com.pruvn.tools.common.hibernate.finnone.cas;

// Generated May 31, 2011 2:37:34 PM by Hibernate Tools 3.2.4.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * LOS_APP_STATUS generated by hbm2java
 */
public class LOS_APP_STATUS implements java.io.Serializable {

	private BigDecimal LAS_ID_N;
	private LOS_APP_APPLICATIONS LOS_APP_APPLICATIONS;
	private String LAS_USER_ID_C;
	private String LAS_ACTIVITY_ID;
	private String LAS_STATUS_C;
	private Date LAS_EDIT_D;

	public LOS_APP_STATUS() {
	}

	public LOS_APP_STATUS(BigDecimal LAS_ID_N) {
		this.LAS_ID_N = LAS_ID_N;
	}

	public LOS_APP_STATUS(BigDecimal LAS_ID_N,
			LOS_APP_APPLICATIONS LOS_APP_APPLICATIONS, String LAS_USER_ID_C,
			String LAS_ACTIVITY_ID, String LAS_STATUS_C, Date LAS_EDIT_D) {
		this.LAS_ID_N = LAS_ID_N;
		this.LOS_APP_APPLICATIONS = LOS_APP_APPLICATIONS;
		this.LAS_USER_ID_C = LAS_USER_ID_C;
		this.LAS_ACTIVITY_ID = LAS_ACTIVITY_ID;
		this.LAS_STATUS_C = LAS_STATUS_C;
		this.LAS_EDIT_D = LAS_EDIT_D;
	}

	public BigDecimal getLAS_ID_N() {
		return this.LAS_ID_N;
	}

	public void setLAS_ID_N(BigDecimal LAS_ID_N) {
		this.LAS_ID_N = LAS_ID_N;
	}

	public LOS_APP_APPLICATIONS getLOS_APP_APPLICATIONS() {
		return this.LOS_APP_APPLICATIONS;
	}

	public void setLOS_APP_APPLICATIONS(
			LOS_APP_APPLICATIONS LOS_APP_APPLICATIONS) {
		this.LOS_APP_APPLICATIONS = LOS_APP_APPLICATIONS;
	}

	public String getLAS_USER_ID_C() {
		return this.LAS_USER_ID_C;
	}

	public void setLAS_USER_ID_C(String LAS_USER_ID_C) {
		this.LAS_USER_ID_C = LAS_USER_ID_C;
	}

	public String getLAS_ACTIVITY_ID() {
		return this.LAS_ACTIVITY_ID;
	}

	public void setLAS_ACTIVITY_ID(String LAS_ACTIVITY_ID) {
		this.LAS_ACTIVITY_ID = LAS_ACTIVITY_ID;
	}

	public String getLAS_STATUS_C() {
		return this.LAS_STATUS_C;
	}

	public void setLAS_STATUS_C(String LAS_STATUS_C) {
		this.LAS_STATUS_C = LAS_STATUS_C;
	}

	public Date getLAS_EDIT_D() {
		return this.LAS_EDIT_D;
	}

	public void setLAS_EDIT_D(Date LAS_EDIT_D) {
		this.LAS_EDIT_D = LAS_EDIT_D;
	}

}
