package com.pruvn.tools.common.hibernate.finnone.cas;

// Generated May 31, 2011 2:37:34 PM by Hibernate Tools 3.2.4.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LOS_APP_APPLICATIONS generated by hbm2java
 */
public class LOS_APP_APPLICATIONS implements java.io.Serializable {

	private String APP_ID_C;
	private NBFC_PRODUCT_M NBFC_PRODUCT_M;
	private NBFC_STATE_M NBFC_STATE_M;
	private String LAA_APP_TITLE_C;
	private String LAA_APP_STATUS_C;
	private String LAA_APP_SUBSTATUS;
	private String LAA_APP_ACCOUNTNO_C;
	private Date LAA_APP_SIGNED_DATE_D;
	private BigDecimal LAA_APP_REQ_AMTFIN_N;
	private BigDecimal LAA_APP_REQ_MARGINMONEY_N;
	private BigDecimal LAA_APP_REQ_MARGINRATE_N;
	private String LAA_APP_REQ_INTTYPE_C;
	private BigDecimal LAA_APP_REQ_INTRATE_N;
	private BigDecimal LAA_APP_REQ_MARKUP_N;
	private BigDecimal LAA_APP_REQ_TERM_N;
	private String LAA_APP_REQ_PMNTTYPE_C;
	private BigDecimal LAA_APP_APPRAMT_BASE_N;
	private BigDecimal LAA_APP_CONRATE_N;
	private String LAA_CURRENCYID;
	private BigDecimal LAA_APP_APPR_AMTFIN_N;
	private BigDecimal LAA_APP_APPR_MARGINMONEY_N;
	private BigDecimal LAA_APP_APPR_MARGINRATE_N;
	private String LAA_APP_APPR_INTTYPE_C;
	private BigDecimal LAA_APP_APPR_INTRATE_N;
	private BigDecimal LAA_APP_APPR_MARKUP_N;
	private BigDecimal LAA_APP_APPR_IRR_N;
	private Short LAA_APP_APPR_TERM_N;
	private String LAA_APP_APPR_FREQ_C;
	private String LAA_APP_APPR_PMNTTYPE_C;
	private String LAA_APP_PMNTMODE_C;
	private BigDecimal LAA_APP_FINANCECHARGE_N;
	private Date LAA_APP_CONTRACTDATE_D;
	private Date LAA_APP_DISBURSALDATE_D;
	private Date LAA_APP_FIRSTPAYDATE_D;
	private Date LAA_APP_MATURITYDATE_D;
	private Date LAA_APP_CONTRACT_RECDDATE_D;
	private Date LAA_APP_CONTRACT_VERIFYDATE_D;
	private String LAA_APP_CONTRACT_VERIFYBY_C;
	private String LAA_APP_DUEDAY_C;
	private BigDecimal LAA_APP_PREPAYPENALTY_N;
	private Integer LSM_SCHEMEID;
	private String LAA_APP_INIT_SOURCETYPE_C;
	private String LAA_APP_INIT_SOURCE_ID_C;
	private String LAA_APP_FINAL_SOURCETYPE_C;
	private String LAA_APP_FINAL_SOURCE_ID_C;
	private Integer LAA_APP_GRACEPERIOD_N;
	private Integer LAA_APP_CRSCORE_N;
	private String LAA_APP_POL_APPL_STRING_C;
	private String LAA_APP_POL_MATCH_STRING_C;
	private String LAA_APP_POLICY_TABLE_C;
	private String LAA_APP_LOANAMT_PAYTO_C;
	private String LAA_PROMOTIONSCHEME;
	private Integer LAA_MKTGID;
	private Integer LAA_BRANCHID;
	private Integer LAA_SUPPLIERID;
	private String LAA_EMP_FLAG;
	private String LAA_PLRTYPE;
	private BigDecimal LAA_PLRRATE;
	private String LAA_DISBURSALTO;
	private String LAA_DISB_TYPE;
	private Short LAA_NO_DISBURSAL;
	private BigDecimal LAA_DISBURSEDAMOUNT;
	private String LAA_DISB_STATUS;
	private BigDecimal LAA_PEMI_RATE;
	private BigDecimal LAA_ADVDISBINTRATE;
	private Integer LAA_EMPLOYERID;
	private Date LAA_REPAYMENT_EFFECTIVE_DATE;
	private String LAA_PREPAY_ALLOWED;
	private String LAA_PREPAY_PENALTY;
	private Short LAA_PREPAY_LOCK_PERIOD;
	private String LAA_FORECLOSURE_PENALTY;
	private String LAA_FORECLOSE_ALLOWED;
	private BigDecimal LAA_FORECLOSE_PENALTY;
	private Short LAA_FORECLOSE_LOCK_PERIOD;
	private String LAA_FLOATINGFLG;
	private Short LAA_FLOATING_FREQUENCY;
	private Date LAA_LAST_FLOAT_SPREAD_DATE;
	private String LAA_PDCFLAG;
	private BigDecimal LAA_INTTAXRATE;
	private BigDecimal LAA_TDSRATE;
	private BigDecimal LAA_LPIRATE;
	private String LAA_TAXAPPLICABLE;
	private String LAA_BALANCE_TRANSFER;
	private BigDecimal LAA_RELATIONAL_DISCOUNT;
	private BigDecimal LAA_OTHER_DISCOUNT;
	private String LAA_CO_APPL_REQ;
	private String LAA_GUARANTOR_REQ;
	private String LAA_SEC_DEPOSIT_REQ;
	private BigDecimal LAA_FEERATE;
	private BigDecimal LAA_PRETAXROI;
	private BigDecimal LAA_ROI;
	private BigDecimal LAA_TAX;
	private BigDecimal LAA_TAX_PERCENTAGE;
	private BigDecimal LAA_SECURITYCOVER;
	private BigDecimal LAA_SECURITYTAKEN;
	private String LAA_CROSS_COLLATERAL;
	private Integer LAA_BILLNO;
	private String LAA_RELATIONSHIP_DISC;
	private String LAA_PROFESSIONAL_DISC;
	private Integer LAA_DSSNO;
	private String LAA_LPITYPE;
	private BigDecimal LAA_MIN_PENALAMOUNT;
	private Integer LAA_INSURCOID;
	private Integer LAA_INSUR_PRODUCTID;
	private String LAA_INSURANCE_FLAG;
	private Date LAA_INSURED_TILL;
	private String LAA_DEPOSIT_ACCOUNT;
	private BigDecimal LAA_SPREAD2;
	private BigDecimal LAA_LTV_MULTIPLIER;
	private String LAA_DISBURSEMENT_DIRECT_CREDIT;
	private Short LAA_PRIN_BASE_UNIT;
	private Integer LAA_FIXED_TERM;
	private BigDecimal LAA_STEP_RATE;
	private String LAA_INVOICE_FLAG;
	private String LAA_RC_FLAG;
	private BigDecimal LAA_SERVICETAXRATE;
	private Integer LAA_DME_ID;
	private String LAA_FILENO;
	private String LAA_APP_FORMNO;
	private String LAA_HFI_FLAG;
	private String LAA_HFI;
	private Integer LAA_EMPLOYER_ADDRESSID;
	private String LAA_EMPCODE;
	private Integer LAA_SPREADID;
	private BigDecimal LAA_INITIAL_EFFRATE;
	private Date LAA_INTSTART_DATE_REGULAR;
	private String LAA_TRANCHING_FLAG;
	private String LAA_TRANCHING_TYPE;
	private String LAA_COMPOUND_FREQ;
	private String LAA_INT_REBATE_FLAG;
	private BigDecimal LAA_ACTUALIRR;
	private BigDecimal LAA_GROSS_LTV;
	private BigDecimal LAA_NET_LTV;
	private String CREATED_BY;
	private Date CREATED_ON;
	private String MODIFIED_BY;
	private Date MODIFIED_ON;
	private BigDecimal LAA_APP_REQ_IRR_N;
	private BigDecimal LAA_APP_REQ_EFFRATE_N;
	private BigDecimal LAA_APP_APPR_EFFRATE_N;
	private Integer LAA_SOURCE_ASSET_MODELID_N;
	private String LAA_SOURCE_ASSET_MAKE_C;
	private String LAA_SOURCE_CHANNEL_PARTNER_C;
	private String LAA_APP_FIRST_SOURCETYPE_C;
	private String LAA_APP_FIRST_SOURCE_ID_C;
	private Short LAA_SOURCE_ASSET_AGE_N;
	private Integer LAA_SOURCE_MARKETINGID_N;
	private Integer LAA_SOURCE_BROKERID_N;
	private Integer LAA_SOURCE_INSPECTORID_N;
	private String LAA_EXISTING_CUSTOMER_C;
	private Short LAA_ADVANCEINSTL_N;
	private Long LAA_APP_NUMINSTL_N;
	private String LAA_APP_REQ_FREQ_C;
	private String LAA_APP_TYPE_C;
	private String LAA_LOAN_PURPOSE_C;
	private String LAA_LOAN_PURPOSE_DTL_C;
	private String LAA_LOAN_PURPOSE_DESC_C;
	private Integer LAA_LCM_CATGID_N;
	private BigDecimal LAA_FOIR_N;
	private BigDecimal LAA_EXPOSURE_CAP_N;
	private BigDecimal LAA_AVG_BAL_N;
	private BigDecimal LAA_APPR_FOIR_N;
	private BigDecimal LAA_APPR_INSR_N;
	private BigDecimal LAA_APPR_LTV_N;
	private BigDecimal LAA_APPR_IIR_N;
	private BigDecimal LAA_BENEFIT_AMOUNT_N;
	private String LAA_APP_SIGN_TYPE_C;
	private String LAA_GRACE_INTEREST_CHARGE_C;
	private String LAA_GRACE_ADJUST_SCHEDULE_C;
	private BigDecimal LAA_VAT_PRIN_RATE_N;
	private BigDecimal LAA_VAT_INT_RATE_N;
	private BigDecimal LAA_VAT_INSTL_RATE_N;
	private String LAA_INT_ROUNDOFF_PARA_C;
	private Integer LAA_INT_ROUNDTILL_N;
	private Integer LAA_INSTLAMT_ROUNDTILL_N;
	private String LAA_INSTLAMT_ROUNDOFF_PARA_C;
	private String LAA_APP_SOURCE_TYPE_C;
	private BigDecimal LAA_EMI_N;
	private String LAA_RATE_EMI_FLAG_C;
	private String LAA_LPP_PRODCAT_C;
	private Boolean LAA_DECIMALS_N;
	private Short LAA_DPERYR_N;
	private Byte LAA_FORECLOSELOCKLN_N;
	private String LAA_AGREEMENTTYPE_C;
	private Integer LAA_LSM_SCHEMEGROUP_N;
	private Integer CUST_ID_N;
	private String LAA_DEANNUALIZE_C;
	private BigDecimal LAA_AMTOTHERS_N;
	private BigDecimal LAA_TAXRATE_N;
	private Date COMMENCEDATE;
	private Short LAA_PRIN_BASE_UNIT_N;
	private Date INTSTART_DATE_REGULAR;
	private BigDecimal LAA_REQ_IIR_N;
	private BigDecimal LAA_APP_ASSETCOST_N;
	private BigDecimal LAA_APPRAISED_INC_N;
	private BigDecimal LAA_APPRAISED_OBL_N;
	private BigDecimal LAA_APPLICABLE_FOIR_N;
	private BigDecimal LAA_APPLICABLE_LTV_N;
	private BigDecimal LAA_EMI_FACTOR_N;
	private BigDecimal LAA_TOTAL_ELIGIBILITY_N;
	private String LAA_RISK_C;
	private String LAA_STRENGTH_C;
	private Integer LAA_CPAID_N;
	private Date LAA_APPROVAL_DATE_D;
	private BigDecimal LAA_VATINPUT_N;
	private String LAA_CUST_PROFILE_TYPE_C;
	private String LAA_CUST_PROFILE_C;
	private BigDecimal LAA_OFFLINE_APP_ID_N;
	private String LAA_RCU_FLAG_C;
	private String LOS_APP_POLICY_RESULT;
	private String LOS_APP_SCORING_RESULT;
	private String LOS_APP_FUZZY_MATCH;
	private Integer LOS_APP_POS_DEDUPE_COUNT;
	private Integer LOS_APP_NEG_DEDUPE_COUNT;
	private String LAA_FII_STATUS;
	private Character LAA_APP_CHARGES_FLAG;
	private BigDecimal LAA_APP_CALCULATION1;
	private BigDecimal LAA_APP_CALCULATION2;
	private BigDecimal LAA_APP_CALCULATION3;
	private BigDecimal LAA_APP_REQ_PTPM_N;
	private String CRS_APP_ID_C;
	private Date PRN_ON;
	private String LAA_LMS_STATUS;
	private String LAA_LMS_DISB_STATUS;
	private Date CREATION_DATE;
	private String LAA_FIELD_1;
	private String LAA_FIELD_2;
	private Date RCU_INITIATION_DATE_D;
	private Date RCU_COMPLETION_DATE_D;
	private String NEGBASE_DEDUPE_INITIATED_C;
	private String CPV_INITIATED_C;
	private String DEVIATION_INITIATED_C;
	private BigDecimal CUSTOMER_EXPOSURE_N;
	private BigDecimal TOTAL_CUST_EXPOSURE_N;
	private String SPECIAL_CONDITION_FOR_C;
	private String SUB_CATEGORY;
	private String LAA_FIELD_3;
	private String LAA_FIELD_4;
	private String LAA_FIELD_5;
	private String LAA_FIELD_6;
	private String LAA_FIELD_7;
	private String LAA_FIELD_8;
	private String LAA_FIELD_9;
	private String LAA_FIELD_10;
	private String LAA_FIELD_11;
	private String LAA_FIELD_12;
	private String LAA_FIELD_13;
	private String LAA_FIELD_14;
	private String LAA_DEALER_FUNDING;
	private String RMS_FLAG_C;
	private String RMS_STATUS_C;
	private String RMS_FORWARD_C;
	private String REJECT_REVIEW__STATUS_C;
	private Date REJECT_REVIEW__DATE_D;
	private Integer LOS_APP_POS_MINI_COUNT;
	private Character LAA_APP_CALPRINCIPAL_C;
	private String INTERESTINADVANCE;
	private String C_UNDESIRABLE_LOC_FLAG;
	private Short C_PCT_TABLE_NO;
	private String VC_SOURCE_CD;
	private String VC_REFINANCED_FROM;
	private String VC_REFERRAL_GRP;
	private String VC_REFERRAL_CD;
	private String VC_REFERRAL_NAME;
	private String VC_BRANCH_NAME;
	private String VC_ACCOUNT_OFF_CD;
	private String VC_ACCTOUNT_OFF_CD;
	private String VC_ACCOUNT_OFFICER;
	private String VC_REQ_FREQUENCY;
	private String VC_POLICY_TYPE;
	private String VC_LOANTYPE;
	private BigDecimal N_ADD_RATE;
	private BigDecimal N_EFFECTIVE_YIELD;
	private BigDecimal N_NET_EFFECTIVE;
	private String VC_BRANCH;
	private String N_BILLING_CYCLE_ID;
	private BigDecimal LAA_CALCULATED_INCOME;
	private BigDecimal LAA_DBR;
	private BigDecimal LAA_APPRAISED_NET_LTV;
	private String NCM_DRAFTSAVE;
	private String VC_PRE_COMPANY;
	private String VC_PLAN_TYPE;
	private String VC_PLAN_CLASS;
	private String VC_POL_NO;
	private BigDecimal N_PRE_PRICE;
	private Date D_POLICYISSUEDATE;
	private Date DATED_POLICYMATURITY;
	private String VC_RELATION_AIF;
	private BigDecimal N_CONSTRUCTION_COST;
	private String VC_RATE_FIXING;
	private String VC_REPRICING_FORMULA;
	private Short N_INTEREST_RATE;
	private Short N_EQUITY_PERCNT;
	private String VC_AIF;
	private BigDecimal LAA_GROSS_MONTHLY_PAY;
	private BigDecimal LAA_CREDIT_LIMIT;
	private String CPV_INITIATED_AGENCY_TYPE;
	private Short DEALER_PARTIC_RATE;
	private BigDecimal FINANCIAL_QUANTUM;
	private String DUEMONTH_C;
	private BigDecimal LAA_RATE_N;
	private BigDecimal LAA_COST_OF_FUNDS_N;
	private BigDecimal LAA_LOSS_N;
	private BigDecimal LAA_EXPENSES_N;
	private BigDecimal LAA_CUSTOMER_YIELD_N;
	private String LAA_SALESPERSON_C;
	private String DEALID_C;
	private String BD_TYPE_C;
	private Short LAA_APP_LOANDTL_TERM_N;
	private String LAA_QUOTE_FLAG_C;
	private String LAA_TOPUP_FLAG;
	private Set LOS_APP_STATUSs = new HashSet(0);

	public LOS_APP_APPLICATIONS() {
	}

	public LOS_APP_APPLICATIONS(String APP_ID_C) {
		this.APP_ID_C = APP_ID_C;
	}	

	public String getAPP_ID_C() {
		return this.APP_ID_C;
	}

	public void setAPP_ID_C(String APP_ID_C) {
		this.APP_ID_C = APP_ID_C;
	}

	public NBFC_PRODUCT_M getNBFC_PRODUCT_M() {
		return this.NBFC_PRODUCT_M;
	}

	public void setNBFC_PRODUCT_M(NBFC_PRODUCT_M NBFC_PRODUCT_M) {
		this.NBFC_PRODUCT_M = NBFC_PRODUCT_M;
	}

	public NBFC_STATE_M getNBFC_STATE_M() {
		return this.NBFC_STATE_M;
	}

	public void setNBFC_STATE_M(NBFC_STATE_M NBFC_STATE_M) {
		this.NBFC_STATE_M = NBFC_STATE_M;
	}

	public String getLAA_APP_TITLE_C() {
		return this.LAA_APP_TITLE_C;
	}

	public void setLAA_APP_TITLE_C(String LAA_APP_TITLE_C) {
		this.LAA_APP_TITLE_C = LAA_APP_TITLE_C;
	}

	public String getLAA_APP_STATUS_C() {
		return this.LAA_APP_STATUS_C;
	}

	public void setLAA_APP_STATUS_C(String LAA_APP_STATUS_C) {
		this.LAA_APP_STATUS_C = LAA_APP_STATUS_C;
	}

	public String getLAA_APP_SUBSTATUS() {
		return this.LAA_APP_SUBSTATUS;
	}

	public void setLAA_APP_SUBSTATUS(String LAA_APP_SUBSTATUS) {
		this.LAA_APP_SUBSTATUS = LAA_APP_SUBSTATUS;
	}

	public String getLAA_APP_ACCOUNTNO_C() {
		return this.LAA_APP_ACCOUNTNO_C;
	}

	public void setLAA_APP_ACCOUNTNO_C(String LAA_APP_ACCOUNTNO_C) {
		this.LAA_APP_ACCOUNTNO_C = LAA_APP_ACCOUNTNO_C;
	}

	public Date getLAA_APP_SIGNED_DATE_D() {
		return this.LAA_APP_SIGNED_DATE_D;
	}

	public void setLAA_APP_SIGNED_DATE_D(Date LAA_APP_SIGNED_DATE_D) {
		this.LAA_APP_SIGNED_DATE_D = LAA_APP_SIGNED_DATE_D;
	}

	public BigDecimal getLAA_APP_REQ_AMTFIN_N() {
		return this.LAA_APP_REQ_AMTFIN_N;
	}

	public void setLAA_APP_REQ_AMTFIN_N(BigDecimal LAA_APP_REQ_AMTFIN_N) {
		this.LAA_APP_REQ_AMTFIN_N = LAA_APP_REQ_AMTFIN_N;
	}

	public BigDecimal getLAA_APP_REQ_MARGINMONEY_N() {
		return this.LAA_APP_REQ_MARGINMONEY_N;
	}

	public void setLAA_APP_REQ_MARGINMONEY_N(
			BigDecimal LAA_APP_REQ_MARGINMONEY_N) {
		this.LAA_APP_REQ_MARGINMONEY_N = LAA_APP_REQ_MARGINMONEY_N;
	}

	public BigDecimal getLAA_APP_REQ_MARGINRATE_N() {
		return this.LAA_APP_REQ_MARGINRATE_N;
	}

	public void setLAA_APP_REQ_MARGINRATE_N(BigDecimal LAA_APP_REQ_MARGINRATE_N) {
		this.LAA_APP_REQ_MARGINRATE_N = LAA_APP_REQ_MARGINRATE_N;
	}

	public String getLAA_APP_REQ_INTTYPE_C() {
		return this.LAA_APP_REQ_INTTYPE_C;
	}

	public void setLAA_APP_REQ_INTTYPE_C(String LAA_APP_REQ_INTTYPE_C) {
		this.LAA_APP_REQ_INTTYPE_C = LAA_APP_REQ_INTTYPE_C;
	}

	public BigDecimal getLAA_APP_REQ_INTRATE_N() {
		return this.LAA_APP_REQ_INTRATE_N;
	}

	public void setLAA_APP_REQ_INTRATE_N(BigDecimal LAA_APP_REQ_INTRATE_N) {
		this.LAA_APP_REQ_INTRATE_N = LAA_APP_REQ_INTRATE_N;
	}

	public BigDecimal getLAA_APP_REQ_MARKUP_N() {
		return this.LAA_APP_REQ_MARKUP_N;
	}

	public void setLAA_APP_REQ_MARKUP_N(BigDecimal LAA_APP_REQ_MARKUP_N) {
		this.LAA_APP_REQ_MARKUP_N = LAA_APP_REQ_MARKUP_N;
	}

	public BigDecimal getLAA_APP_REQ_TERM_N() {
		return this.LAA_APP_REQ_TERM_N;
	}

	public void setLAA_APP_REQ_TERM_N(BigDecimal LAA_APP_REQ_TERM_N) {
		this.LAA_APP_REQ_TERM_N = LAA_APP_REQ_TERM_N;
	}

	public String getLAA_APP_REQ_PMNTTYPE_C() {
		return this.LAA_APP_REQ_PMNTTYPE_C;
	}

	public void setLAA_APP_REQ_PMNTTYPE_C(String LAA_APP_REQ_PMNTTYPE_C) {
		this.LAA_APP_REQ_PMNTTYPE_C = LAA_APP_REQ_PMNTTYPE_C;
	}

	public BigDecimal getLAA_APP_APPRAMT_BASE_N() {
		return this.LAA_APP_APPRAMT_BASE_N;
	}

	public void setLAA_APP_APPRAMT_BASE_N(BigDecimal LAA_APP_APPRAMT_BASE_N) {
		this.LAA_APP_APPRAMT_BASE_N = LAA_APP_APPRAMT_BASE_N;
	}

	public BigDecimal getLAA_APP_CONRATE_N() {
		return this.LAA_APP_CONRATE_N;
	}

	public void setLAA_APP_CONRATE_N(BigDecimal LAA_APP_CONRATE_N) {
		this.LAA_APP_CONRATE_N = LAA_APP_CONRATE_N;
	}

	public String getLAA_CURRENCYID() {
		return this.LAA_CURRENCYID;
	}

	public void setLAA_CURRENCYID(String LAA_CURRENCYID) {
		this.LAA_CURRENCYID = LAA_CURRENCYID;
	}

	public BigDecimal getLAA_APP_APPR_AMTFIN_N() {
		return this.LAA_APP_APPR_AMTFIN_N;
	}

	public void setLAA_APP_APPR_AMTFIN_N(BigDecimal LAA_APP_APPR_AMTFIN_N) {
		this.LAA_APP_APPR_AMTFIN_N = LAA_APP_APPR_AMTFIN_N;
	}

	public BigDecimal getLAA_APP_APPR_MARGINMONEY_N() {
		return this.LAA_APP_APPR_MARGINMONEY_N;
	}

	public void setLAA_APP_APPR_MARGINMONEY_N(
			BigDecimal LAA_APP_APPR_MARGINMONEY_N) {
		this.LAA_APP_APPR_MARGINMONEY_N = LAA_APP_APPR_MARGINMONEY_N;
	}

	public BigDecimal getLAA_APP_APPR_MARGINRATE_N() {
		return this.LAA_APP_APPR_MARGINRATE_N;
	}

	public void setLAA_APP_APPR_MARGINRATE_N(
			BigDecimal LAA_APP_APPR_MARGINRATE_N) {
		this.LAA_APP_APPR_MARGINRATE_N = LAA_APP_APPR_MARGINRATE_N;
	}

	public String getLAA_APP_APPR_INTTYPE_C() {
		return this.LAA_APP_APPR_INTTYPE_C;
	}

	public void setLAA_APP_APPR_INTTYPE_C(String LAA_APP_APPR_INTTYPE_C) {
		this.LAA_APP_APPR_INTTYPE_C = LAA_APP_APPR_INTTYPE_C;
	}

	public BigDecimal getLAA_APP_APPR_INTRATE_N() {
		return this.LAA_APP_APPR_INTRATE_N;
	}

	public void setLAA_APP_APPR_INTRATE_N(BigDecimal LAA_APP_APPR_INTRATE_N) {
		this.LAA_APP_APPR_INTRATE_N = LAA_APP_APPR_INTRATE_N;
	}

	public BigDecimal getLAA_APP_APPR_MARKUP_N() {
		return this.LAA_APP_APPR_MARKUP_N;
	}

	public void setLAA_APP_APPR_MARKUP_N(BigDecimal LAA_APP_APPR_MARKUP_N) {
		this.LAA_APP_APPR_MARKUP_N = LAA_APP_APPR_MARKUP_N;
	}

	public BigDecimal getLAA_APP_APPR_IRR_N() {
		return this.LAA_APP_APPR_IRR_N;
	}

	public void setLAA_APP_APPR_IRR_N(BigDecimal LAA_APP_APPR_IRR_N) {
		this.LAA_APP_APPR_IRR_N = LAA_APP_APPR_IRR_N;
	}

	public Short getLAA_APP_APPR_TERM_N() {
		return this.LAA_APP_APPR_TERM_N;
	}

	public void setLAA_APP_APPR_TERM_N(Short LAA_APP_APPR_TERM_N) {
		this.LAA_APP_APPR_TERM_N = LAA_APP_APPR_TERM_N;
	}

	public String getLAA_APP_APPR_FREQ_C() {
		return this.LAA_APP_APPR_FREQ_C;
	}

	public void setLAA_APP_APPR_FREQ_C(String LAA_APP_APPR_FREQ_C) {
		this.LAA_APP_APPR_FREQ_C = LAA_APP_APPR_FREQ_C;
	}

	public String getLAA_APP_APPR_PMNTTYPE_C() {
		return this.LAA_APP_APPR_PMNTTYPE_C;
	}

	public void setLAA_APP_APPR_PMNTTYPE_C(String LAA_APP_APPR_PMNTTYPE_C) {
		this.LAA_APP_APPR_PMNTTYPE_C = LAA_APP_APPR_PMNTTYPE_C;
	}

	public String getLAA_APP_PMNTMODE_C() {
		return this.LAA_APP_PMNTMODE_C;
	}

	public void setLAA_APP_PMNTMODE_C(String LAA_APP_PMNTMODE_C) {
		this.LAA_APP_PMNTMODE_C = LAA_APP_PMNTMODE_C;
	}

	public BigDecimal getLAA_APP_FINANCECHARGE_N() {
		return this.LAA_APP_FINANCECHARGE_N;
	}

	public void setLAA_APP_FINANCECHARGE_N(BigDecimal LAA_APP_FINANCECHARGE_N) {
		this.LAA_APP_FINANCECHARGE_N = LAA_APP_FINANCECHARGE_N;
	}

	public Date getLAA_APP_CONTRACTDATE_D() {
		return this.LAA_APP_CONTRACTDATE_D;
	}

	public void setLAA_APP_CONTRACTDATE_D(Date LAA_APP_CONTRACTDATE_D) {
		this.LAA_APP_CONTRACTDATE_D = LAA_APP_CONTRACTDATE_D;
	}

	public Date getLAA_APP_DISBURSALDATE_D() {
		return this.LAA_APP_DISBURSALDATE_D;
	}

	public void setLAA_APP_DISBURSALDATE_D(Date LAA_APP_DISBURSALDATE_D) {
		this.LAA_APP_DISBURSALDATE_D = LAA_APP_DISBURSALDATE_D;
	}

	public Date getLAA_APP_FIRSTPAYDATE_D() {
		return this.LAA_APP_FIRSTPAYDATE_D;
	}

	public void setLAA_APP_FIRSTPAYDATE_D(Date LAA_APP_FIRSTPAYDATE_D) {
		this.LAA_APP_FIRSTPAYDATE_D = LAA_APP_FIRSTPAYDATE_D;
	}

	public Date getLAA_APP_MATURITYDATE_D() {
		return this.LAA_APP_MATURITYDATE_D;
	}

	public void setLAA_APP_MATURITYDATE_D(Date LAA_APP_MATURITYDATE_D) {
		this.LAA_APP_MATURITYDATE_D = LAA_APP_MATURITYDATE_D;
	}

	public Date getLAA_APP_CONTRACT_RECDDATE_D() {
		return this.LAA_APP_CONTRACT_RECDDATE_D;
	}

	public void setLAA_APP_CONTRACT_RECDDATE_D(Date LAA_APP_CONTRACT_RECDDATE_D) {
		this.LAA_APP_CONTRACT_RECDDATE_D = LAA_APP_CONTRACT_RECDDATE_D;
	}

	public Date getLAA_APP_CONTRACT_VERIFYDATE_D() {
		return this.LAA_APP_CONTRACT_VERIFYDATE_D;
	}

	public void setLAA_APP_CONTRACT_VERIFYDATE_D(
			Date LAA_APP_CONTRACT_VERIFYDATE_D) {
		this.LAA_APP_CONTRACT_VERIFYDATE_D = LAA_APP_CONTRACT_VERIFYDATE_D;
	}

	public String getLAA_APP_CONTRACT_VERIFYBY_C() {
		return this.LAA_APP_CONTRACT_VERIFYBY_C;
	}

	public void setLAA_APP_CONTRACT_VERIFYBY_C(
			String LAA_APP_CONTRACT_VERIFYBY_C) {
		this.LAA_APP_CONTRACT_VERIFYBY_C = LAA_APP_CONTRACT_VERIFYBY_C;
	}

	public String getLAA_APP_DUEDAY_C() {
		return this.LAA_APP_DUEDAY_C;
	}

	public void setLAA_APP_DUEDAY_C(String LAA_APP_DUEDAY_C) {
		this.LAA_APP_DUEDAY_C = LAA_APP_DUEDAY_C;
	}

	public BigDecimal getLAA_APP_PREPAYPENALTY_N() {
		return this.LAA_APP_PREPAYPENALTY_N;
	}

	public void setLAA_APP_PREPAYPENALTY_N(BigDecimal LAA_APP_PREPAYPENALTY_N) {
		this.LAA_APP_PREPAYPENALTY_N = LAA_APP_PREPAYPENALTY_N;
	}

	public Integer getLSM_SCHEMEID() {
		return this.LSM_SCHEMEID;
	}

	public void setLSM_SCHEMEID(Integer LSM_SCHEMEID) {
		this.LSM_SCHEMEID = LSM_SCHEMEID;
	}

	public String getLAA_APP_INIT_SOURCETYPE_C() {
		return this.LAA_APP_INIT_SOURCETYPE_C;
	}

	public void setLAA_APP_INIT_SOURCETYPE_C(String LAA_APP_INIT_SOURCETYPE_C) {
		this.LAA_APP_INIT_SOURCETYPE_C = LAA_APP_INIT_SOURCETYPE_C;
	}

	public String getLAA_APP_INIT_SOURCE_ID_C() {
		return this.LAA_APP_INIT_SOURCE_ID_C;
	}

	public void setLAA_APP_INIT_SOURCE_ID_C(String LAA_APP_INIT_SOURCE_ID_C) {
		this.LAA_APP_INIT_SOURCE_ID_C = LAA_APP_INIT_SOURCE_ID_C;
	}

	public String getLAA_APP_FINAL_SOURCETYPE_C() {
		return this.LAA_APP_FINAL_SOURCETYPE_C;
	}

	public void setLAA_APP_FINAL_SOURCETYPE_C(String LAA_APP_FINAL_SOURCETYPE_C) {
		this.LAA_APP_FINAL_SOURCETYPE_C = LAA_APP_FINAL_SOURCETYPE_C;
	}

	public String getLAA_APP_FINAL_SOURCE_ID_C() {
		return this.LAA_APP_FINAL_SOURCE_ID_C;
	}

	public void setLAA_APP_FINAL_SOURCE_ID_C(String LAA_APP_FINAL_SOURCE_ID_C) {
		this.LAA_APP_FINAL_SOURCE_ID_C = LAA_APP_FINAL_SOURCE_ID_C;
	}

	public Integer getLAA_APP_GRACEPERIOD_N() {
		return this.LAA_APP_GRACEPERIOD_N;
	}

	public void setLAA_APP_GRACEPERIOD_N(Integer LAA_APP_GRACEPERIOD_N) {
		this.LAA_APP_GRACEPERIOD_N = LAA_APP_GRACEPERIOD_N;
	}

	public Integer getLAA_APP_CRSCORE_N() {
		return this.LAA_APP_CRSCORE_N;
	}

	public void setLAA_APP_CRSCORE_N(Integer LAA_APP_CRSCORE_N) {
		this.LAA_APP_CRSCORE_N = LAA_APP_CRSCORE_N;
	}

	public String getLAA_APP_POL_APPL_STRING_C() {
		return this.LAA_APP_POL_APPL_STRING_C;
	}

	public void setLAA_APP_POL_APPL_STRING_C(String LAA_APP_POL_APPL_STRING_C) {
		this.LAA_APP_POL_APPL_STRING_C = LAA_APP_POL_APPL_STRING_C;
	}

	public String getLAA_APP_POL_MATCH_STRING_C() {
		return this.LAA_APP_POL_MATCH_STRING_C;
	}

	public void setLAA_APP_POL_MATCH_STRING_C(String LAA_APP_POL_MATCH_STRING_C) {
		this.LAA_APP_POL_MATCH_STRING_C = LAA_APP_POL_MATCH_STRING_C;
	}

	public String getLAA_APP_POLICY_TABLE_C() {
		return this.LAA_APP_POLICY_TABLE_C;
	}

	public void setLAA_APP_POLICY_TABLE_C(String LAA_APP_POLICY_TABLE_C) {
		this.LAA_APP_POLICY_TABLE_C = LAA_APP_POLICY_TABLE_C;
	}

	public String getLAA_APP_LOANAMT_PAYTO_C() {
		return this.LAA_APP_LOANAMT_PAYTO_C;
	}

	public void setLAA_APP_LOANAMT_PAYTO_C(String LAA_APP_LOANAMT_PAYTO_C) {
		this.LAA_APP_LOANAMT_PAYTO_C = LAA_APP_LOANAMT_PAYTO_C;
	}

	public String getLAA_PROMOTIONSCHEME() {
		return this.LAA_PROMOTIONSCHEME;
	}

	public void setLAA_PROMOTIONSCHEME(String LAA_PROMOTIONSCHEME) {
		this.LAA_PROMOTIONSCHEME = LAA_PROMOTIONSCHEME;
	}

	public Integer getLAA_MKTGID() {
		return this.LAA_MKTGID;
	}

	public void setLAA_MKTGID(Integer LAA_MKTGID) {
		this.LAA_MKTGID = LAA_MKTGID;
	}

	public Integer getLAA_BRANCHID() {
		return this.LAA_BRANCHID;
	}

	public void setLAA_BRANCHID(Integer LAA_BRANCHID) {
		this.LAA_BRANCHID = LAA_BRANCHID;
	}

	public Integer getLAA_SUPPLIERID() {
		return this.LAA_SUPPLIERID;
	}

	public void setLAA_SUPPLIERID(Integer LAA_SUPPLIERID) {
		this.LAA_SUPPLIERID = LAA_SUPPLIERID;
	}

	public String getLAA_EMP_FLAG() {
		return this.LAA_EMP_FLAG;
	}

	public void setLAA_EMP_FLAG(String LAA_EMP_FLAG) {
		this.LAA_EMP_FLAG = LAA_EMP_FLAG;
	}

	public String getLAA_PLRTYPE() {
		return this.LAA_PLRTYPE;
	}

	public void setLAA_PLRTYPE(String LAA_PLRTYPE) {
		this.LAA_PLRTYPE = LAA_PLRTYPE;
	}

	public BigDecimal getLAA_PLRRATE() {
		return this.LAA_PLRRATE;
	}

	public void setLAA_PLRRATE(BigDecimal LAA_PLRRATE) {
		this.LAA_PLRRATE = LAA_PLRRATE;
	}

	public String getLAA_DISBURSALTO() {
		return this.LAA_DISBURSALTO;
	}

	public void setLAA_DISBURSALTO(String LAA_DISBURSALTO) {
		this.LAA_DISBURSALTO = LAA_DISBURSALTO;
	}

	public String getLAA_DISB_TYPE() {
		return this.LAA_DISB_TYPE;
	}

	public void setLAA_DISB_TYPE(String LAA_DISB_TYPE) {
		this.LAA_DISB_TYPE = LAA_DISB_TYPE;
	}

	public Short getLAA_NO_DISBURSAL() {
		return this.LAA_NO_DISBURSAL;
	}

	public void setLAA_NO_DISBURSAL(Short LAA_NO_DISBURSAL) {
		this.LAA_NO_DISBURSAL = LAA_NO_DISBURSAL;
	}

	public BigDecimal getLAA_DISBURSEDAMOUNT() {
		return this.LAA_DISBURSEDAMOUNT;
	}

	public void setLAA_DISBURSEDAMOUNT(BigDecimal LAA_DISBURSEDAMOUNT) {
		this.LAA_DISBURSEDAMOUNT = LAA_DISBURSEDAMOUNT;
	}

	public String getLAA_DISB_STATUS() {
		return this.LAA_DISB_STATUS;
	}

	public void setLAA_DISB_STATUS(String LAA_DISB_STATUS) {
		this.LAA_DISB_STATUS = LAA_DISB_STATUS;
	}

	public BigDecimal getLAA_PEMI_RATE() {
		return this.LAA_PEMI_RATE;
	}

	public void setLAA_PEMI_RATE(BigDecimal LAA_PEMI_RATE) {
		this.LAA_PEMI_RATE = LAA_PEMI_RATE;
	}

	public BigDecimal getLAA_ADVDISBINTRATE() {
		return this.LAA_ADVDISBINTRATE;
	}

	public void setLAA_ADVDISBINTRATE(BigDecimal LAA_ADVDISBINTRATE) {
		this.LAA_ADVDISBINTRATE = LAA_ADVDISBINTRATE;
	}

	public Integer getLAA_EMPLOYERID() {
		return this.LAA_EMPLOYERID;
	}

	public void setLAA_EMPLOYERID(Integer LAA_EMPLOYERID) {
		this.LAA_EMPLOYERID = LAA_EMPLOYERID;
	}

	public Date getLAA_REPAYMENT_EFFECTIVE_DATE() {
		return this.LAA_REPAYMENT_EFFECTIVE_DATE;
	}

	public void setLAA_REPAYMENT_EFFECTIVE_DATE(
			Date LAA_REPAYMENT_EFFECTIVE_DATE) {
		this.LAA_REPAYMENT_EFFECTIVE_DATE = LAA_REPAYMENT_EFFECTIVE_DATE;
	}

	public String getLAA_PREPAY_ALLOWED() {
		return this.LAA_PREPAY_ALLOWED;
	}

	public void setLAA_PREPAY_ALLOWED(String LAA_PREPAY_ALLOWED) {
		this.LAA_PREPAY_ALLOWED = LAA_PREPAY_ALLOWED;
	}

	public String getLAA_PREPAY_PENALTY() {
		return this.LAA_PREPAY_PENALTY;
	}

	public void setLAA_PREPAY_PENALTY(String LAA_PREPAY_PENALTY) {
		this.LAA_PREPAY_PENALTY = LAA_PREPAY_PENALTY;
	}

	public Short getLAA_PREPAY_LOCK_PERIOD() {
		return this.LAA_PREPAY_LOCK_PERIOD;
	}

	public void setLAA_PREPAY_LOCK_PERIOD(Short LAA_PREPAY_LOCK_PERIOD) {
		this.LAA_PREPAY_LOCK_PERIOD = LAA_PREPAY_LOCK_PERIOD;
	}

	public String getLAA_FORECLOSURE_PENALTY() {
		return this.LAA_FORECLOSURE_PENALTY;
	}

	public void setLAA_FORECLOSURE_PENALTY(String LAA_FORECLOSURE_PENALTY) {
		this.LAA_FORECLOSURE_PENALTY = LAA_FORECLOSURE_PENALTY;
	}

	public String getLAA_FORECLOSE_ALLOWED() {
		return this.LAA_FORECLOSE_ALLOWED;
	}

	public void setLAA_FORECLOSE_ALLOWED(String LAA_FORECLOSE_ALLOWED) {
		this.LAA_FORECLOSE_ALLOWED = LAA_FORECLOSE_ALLOWED;
	}

	public BigDecimal getLAA_FORECLOSE_PENALTY() {
		return this.LAA_FORECLOSE_PENALTY;
	}

	public void setLAA_FORECLOSE_PENALTY(BigDecimal LAA_FORECLOSE_PENALTY) {
		this.LAA_FORECLOSE_PENALTY = LAA_FORECLOSE_PENALTY;
	}

	public Short getLAA_FORECLOSE_LOCK_PERIOD() {
		return this.LAA_FORECLOSE_LOCK_PERIOD;
	}

	public void setLAA_FORECLOSE_LOCK_PERIOD(Short LAA_FORECLOSE_LOCK_PERIOD) {
		this.LAA_FORECLOSE_LOCK_PERIOD = LAA_FORECLOSE_LOCK_PERIOD;
	}

	public String getLAA_FLOATINGFLG() {
		return this.LAA_FLOATINGFLG;
	}

	public void setLAA_FLOATINGFLG(String LAA_FLOATINGFLG) {
		this.LAA_FLOATINGFLG = LAA_FLOATINGFLG;
	}

	public Short getLAA_FLOATING_FREQUENCY() {
		return this.LAA_FLOATING_FREQUENCY;
	}

	public void setLAA_FLOATING_FREQUENCY(Short LAA_FLOATING_FREQUENCY) {
		this.LAA_FLOATING_FREQUENCY = LAA_FLOATING_FREQUENCY;
	}

	public Date getLAA_LAST_FLOAT_SPREAD_DATE() {
		return this.LAA_LAST_FLOAT_SPREAD_DATE;
	}

	public void setLAA_LAST_FLOAT_SPREAD_DATE(Date LAA_LAST_FLOAT_SPREAD_DATE) {
		this.LAA_LAST_FLOAT_SPREAD_DATE = LAA_LAST_FLOAT_SPREAD_DATE;
	}

	public String getLAA_PDCFLAG() {
		return this.LAA_PDCFLAG;
	}

	public void setLAA_PDCFLAG(String LAA_PDCFLAG) {
		this.LAA_PDCFLAG = LAA_PDCFLAG;
	}

	public BigDecimal getLAA_INTTAXRATE() {
		return this.LAA_INTTAXRATE;
	}

	public void setLAA_INTTAXRATE(BigDecimal LAA_INTTAXRATE) {
		this.LAA_INTTAXRATE = LAA_INTTAXRATE;
	}

	public BigDecimal getLAA_TDSRATE() {
		return this.LAA_TDSRATE;
	}

	public void setLAA_TDSRATE(BigDecimal LAA_TDSRATE) {
		this.LAA_TDSRATE = LAA_TDSRATE;
	}

	public BigDecimal getLAA_LPIRATE() {
		return this.LAA_LPIRATE;
	}

	public void setLAA_LPIRATE(BigDecimal LAA_LPIRATE) {
		this.LAA_LPIRATE = LAA_LPIRATE;
	}

	public String getLAA_TAXAPPLICABLE() {
		return this.LAA_TAXAPPLICABLE;
	}

	public void setLAA_TAXAPPLICABLE(String LAA_TAXAPPLICABLE) {
		this.LAA_TAXAPPLICABLE = LAA_TAXAPPLICABLE;
	}

	public String getLAA_BALANCE_TRANSFER() {
		return this.LAA_BALANCE_TRANSFER;
	}

	public void setLAA_BALANCE_TRANSFER(String LAA_BALANCE_TRANSFER) {
		this.LAA_BALANCE_TRANSFER = LAA_BALANCE_TRANSFER;
	}

	public BigDecimal getLAA_RELATIONAL_DISCOUNT() {
		return this.LAA_RELATIONAL_DISCOUNT;
	}

	public void setLAA_RELATIONAL_DISCOUNT(BigDecimal LAA_RELATIONAL_DISCOUNT) {
		this.LAA_RELATIONAL_DISCOUNT = LAA_RELATIONAL_DISCOUNT;
	}

	public BigDecimal getLAA_OTHER_DISCOUNT() {
		return this.LAA_OTHER_DISCOUNT;
	}

	public void setLAA_OTHER_DISCOUNT(BigDecimal LAA_OTHER_DISCOUNT) {
		this.LAA_OTHER_DISCOUNT = LAA_OTHER_DISCOUNT;
	}

	public String getLAA_CO_APPL_REQ() {
		return this.LAA_CO_APPL_REQ;
	}

	public void setLAA_CO_APPL_REQ(String LAA_CO_APPL_REQ) {
		this.LAA_CO_APPL_REQ = LAA_CO_APPL_REQ;
	}

	public String getLAA_GUARANTOR_REQ() {
		return this.LAA_GUARANTOR_REQ;
	}

	public void setLAA_GUARANTOR_REQ(String LAA_GUARANTOR_REQ) {
		this.LAA_GUARANTOR_REQ = LAA_GUARANTOR_REQ;
	}

	public String getLAA_SEC_DEPOSIT_REQ() {
		return this.LAA_SEC_DEPOSIT_REQ;
	}

	public void setLAA_SEC_DEPOSIT_REQ(String LAA_SEC_DEPOSIT_REQ) {
		this.LAA_SEC_DEPOSIT_REQ = LAA_SEC_DEPOSIT_REQ;
	}

	public BigDecimal getLAA_FEERATE() {
		return this.LAA_FEERATE;
	}

	public void setLAA_FEERATE(BigDecimal LAA_FEERATE) {
		this.LAA_FEERATE = LAA_FEERATE;
	}

	public BigDecimal getLAA_PRETAXROI() {
		return this.LAA_PRETAXROI;
	}

	public void setLAA_PRETAXROI(BigDecimal LAA_PRETAXROI) {
		this.LAA_PRETAXROI = LAA_PRETAXROI;
	}

	public BigDecimal getLAA_ROI() {
		return this.LAA_ROI;
	}

	public void setLAA_ROI(BigDecimal LAA_ROI) {
		this.LAA_ROI = LAA_ROI;
	}

	public BigDecimal getLAA_TAX() {
		return this.LAA_TAX;
	}

	public void setLAA_TAX(BigDecimal LAA_TAX) {
		this.LAA_TAX = LAA_TAX;
	}

	public BigDecimal getLAA_TAX_PERCENTAGE() {
		return this.LAA_TAX_PERCENTAGE;
	}

	public void setLAA_TAX_PERCENTAGE(BigDecimal LAA_TAX_PERCENTAGE) {
		this.LAA_TAX_PERCENTAGE = LAA_TAX_PERCENTAGE;
	}

	public BigDecimal getLAA_SECURITYCOVER() {
		return this.LAA_SECURITYCOVER;
	}

	public void setLAA_SECURITYCOVER(BigDecimal LAA_SECURITYCOVER) {
		this.LAA_SECURITYCOVER = LAA_SECURITYCOVER;
	}

	public BigDecimal getLAA_SECURITYTAKEN() {
		return this.LAA_SECURITYTAKEN;
	}

	public void setLAA_SECURITYTAKEN(BigDecimal LAA_SECURITYTAKEN) {
		this.LAA_SECURITYTAKEN = LAA_SECURITYTAKEN;
	}

	public String getLAA_CROSS_COLLATERAL() {
		return this.LAA_CROSS_COLLATERAL;
	}

	public void setLAA_CROSS_COLLATERAL(String LAA_CROSS_COLLATERAL) {
		this.LAA_CROSS_COLLATERAL = LAA_CROSS_COLLATERAL;
	}

	public Integer getLAA_BILLNO() {
		return this.LAA_BILLNO;
	}

	public void setLAA_BILLNO(Integer LAA_BILLNO) {
		this.LAA_BILLNO = LAA_BILLNO;
	}

	public String getLAA_RELATIONSHIP_DISC() {
		return this.LAA_RELATIONSHIP_DISC;
	}

	public void setLAA_RELATIONSHIP_DISC(String LAA_RELATIONSHIP_DISC) {
		this.LAA_RELATIONSHIP_DISC = LAA_RELATIONSHIP_DISC;
	}

	public String getLAA_PROFESSIONAL_DISC() {
		return this.LAA_PROFESSIONAL_DISC;
	}

	public void setLAA_PROFESSIONAL_DISC(String LAA_PROFESSIONAL_DISC) {
		this.LAA_PROFESSIONAL_DISC = LAA_PROFESSIONAL_DISC;
	}

	public Integer getLAA_DSSNO() {
		return this.LAA_DSSNO;
	}

	public void setLAA_DSSNO(Integer LAA_DSSNO) {
		this.LAA_DSSNO = LAA_DSSNO;
	}

	public String getLAA_LPITYPE() {
		return this.LAA_LPITYPE;
	}

	public void setLAA_LPITYPE(String LAA_LPITYPE) {
		this.LAA_LPITYPE = LAA_LPITYPE;
	}

	public BigDecimal getLAA_MIN_PENALAMOUNT() {
		return this.LAA_MIN_PENALAMOUNT;
	}

	public void setLAA_MIN_PENALAMOUNT(BigDecimal LAA_MIN_PENALAMOUNT) {
		this.LAA_MIN_PENALAMOUNT = LAA_MIN_PENALAMOUNT;
	}

	public Integer getLAA_INSURCOID() {
		return this.LAA_INSURCOID;
	}

	public void setLAA_INSURCOID(Integer LAA_INSURCOID) {
		this.LAA_INSURCOID = LAA_INSURCOID;
	}

	public Integer getLAA_INSUR_PRODUCTID() {
		return this.LAA_INSUR_PRODUCTID;
	}

	public void setLAA_INSUR_PRODUCTID(Integer LAA_INSUR_PRODUCTID) {
		this.LAA_INSUR_PRODUCTID = LAA_INSUR_PRODUCTID;
	}

	public String getLAA_INSURANCE_FLAG() {
		return this.LAA_INSURANCE_FLAG;
	}

	public void setLAA_INSURANCE_FLAG(String LAA_INSURANCE_FLAG) {
		this.LAA_INSURANCE_FLAG = LAA_INSURANCE_FLAG;
	}

	public Date getLAA_INSURED_TILL() {
		return this.LAA_INSURED_TILL;
	}

	public void setLAA_INSURED_TILL(Date LAA_INSURED_TILL) {
		this.LAA_INSURED_TILL = LAA_INSURED_TILL;
	}

	public String getLAA_DEPOSIT_ACCOUNT() {
		return this.LAA_DEPOSIT_ACCOUNT;
	}

	public void setLAA_DEPOSIT_ACCOUNT(String LAA_DEPOSIT_ACCOUNT) {
		this.LAA_DEPOSIT_ACCOUNT = LAA_DEPOSIT_ACCOUNT;
	}

	public BigDecimal getLAA_SPREAD2() {
		return this.LAA_SPREAD2;
	}

	public void setLAA_SPREAD2(BigDecimal LAA_SPREAD2) {
		this.LAA_SPREAD2 = LAA_SPREAD2;
	}

	public BigDecimal getLAA_LTV_MULTIPLIER() {
		return this.LAA_LTV_MULTIPLIER;
	}

	public void setLAA_LTV_MULTIPLIER(BigDecimal LAA_LTV_MULTIPLIER) {
		this.LAA_LTV_MULTIPLIER = LAA_LTV_MULTIPLIER;
	}

	public String getLAA_DISBURSEMENT_DIRECT_CREDIT() {
		return this.LAA_DISBURSEMENT_DIRECT_CREDIT;
	}

	public void setLAA_DISBURSEMENT_DIRECT_CREDIT(
			String LAA_DISBURSEMENT_DIRECT_CREDIT) {
		this.LAA_DISBURSEMENT_DIRECT_CREDIT = LAA_DISBURSEMENT_DIRECT_CREDIT;
	}

	public Short getLAA_PRIN_BASE_UNIT() {
		return this.LAA_PRIN_BASE_UNIT;
	}

	public void setLAA_PRIN_BASE_UNIT(Short LAA_PRIN_BASE_UNIT) {
		this.LAA_PRIN_BASE_UNIT = LAA_PRIN_BASE_UNIT;
	}

	public Integer getLAA_FIXED_TERM() {
		return this.LAA_FIXED_TERM;
	}

	public void setLAA_FIXED_TERM(Integer LAA_FIXED_TERM) {
		this.LAA_FIXED_TERM = LAA_FIXED_TERM;
	}

	public BigDecimal getLAA_STEP_RATE() {
		return this.LAA_STEP_RATE;
	}

	public void setLAA_STEP_RATE(BigDecimal LAA_STEP_RATE) {
		this.LAA_STEP_RATE = LAA_STEP_RATE;
	}

	public String getLAA_INVOICE_FLAG() {
		return this.LAA_INVOICE_FLAG;
	}

	public void setLAA_INVOICE_FLAG(String LAA_INVOICE_FLAG) {
		this.LAA_INVOICE_FLAG = LAA_INVOICE_FLAG;
	}

	public String getLAA_RC_FLAG() {
		return this.LAA_RC_FLAG;
	}

	public void setLAA_RC_FLAG(String LAA_RC_FLAG) {
		this.LAA_RC_FLAG = LAA_RC_FLAG;
	}

	public BigDecimal getLAA_SERVICETAXRATE() {
		return this.LAA_SERVICETAXRATE;
	}

	public void setLAA_SERVICETAXRATE(BigDecimal LAA_SERVICETAXRATE) {
		this.LAA_SERVICETAXRATE = LAA_SERVICETAXRATE;
	}

	public Integer getLAA_DME_ID() {
		return this.LAA_DME_ID;
	}

	public void setLAA_DME_ID(Integer LAA_DME_ID) {
		this.LAA_DME_ID = LAA_DME_ID;
	}

	public String getLAA_FILENO() {
		return this.LAA_FILENO;
	}

	public void setLAA_FILENO(String LAA_FILENO) {
		this.LAA_FILENO = LAA_FILENO;
	}

	public String getLAA_APP_FORMNO() {
		return this.LAA_APP_FORMNO;
	}

	public void setLAA_APP_FORMNO(String LAA_APP_FORMNO) {
		this.LAA_APP_FORMNO = LAA_APP_FORMNO;
	}

	public String getLAA_HFI_FLAG() {
		return this.LAA_HFI_FLAG;
	}

	public void setLAA_HFI_FLAG(String LAA_HFI_FLAG) {
		this.LAA_HFI_FLAG = LAA_HFI_FLAG;
	}

	public String getLAA_HFI() {
		return this.LAA_HFI;
	}

	public void setLAA_HFI(String LAA_HFI) {
		this.LAA_HFI = LAA_HFI;
	}

	public Integer getLAA_EMPLOYER_ADDRESSID() {
		return this.LAA_EMPLOYER_ADDRESSID;
	}

	public void setLAA_EMPLOYER_ADDRESSID(Integer LAA_EMPLOYER_ADDRESSID) {
		this.LAA_EMPLOYER_ADDRESSID = LAA_EMPLOYER_ADDRESSID;
	}

	public String getLAA_EMPCODE() {
		return this.LAA_EMPCODE;
	}

	public void setLAA_EMPCODE(String LAA_EMPCODE) {
		this.LAA_EMPCODE = LAA_EMPCODE;
	}

	public Integer getLAA_SPREADID() {
		return this.LAA_SPREADID;
	}

	public void setLAA_SPREADID(Integer LAA_SPREADID) {
		this.LAA_SPREADID = LAA_SPREADID;
	}

	public BigDecimal getLAA_INITIAL_EFFRATE() {
		return this.LAA_INITIAL_EFFRATE;
	}

	public void setLAA_INITIAL_EFFRATE(BigDecimal LAA_INITIAL_EFFRATE) {
		this.LAA_INITIAL_EFFRATE = LAA_INITIAL_EFFRATE;
	}

	public Date getLAA_INTSTART_DATE_REGULAR() {
		return this.LAA_INTSTART_DATE_REGULAR;
	}

	public void setLAA_INTSTART_DATE_REGULAR(Date LAA_INTSTART_DATE_REGULAR) {
		this.LAA_INTSTART_DATE_REGULAR = LAA_INTSTART_DATE_REGULAR;
	}

	public String getLAA_TRANCHING_FLAG() {
		return this.LAA_TRANCHING_FLAG;
	}

	public void setLAA_TRANCHING_FLAG(String LAA_TRANCHING_FLAG) {
		this.LAA_TRANCHING_FLAG = LAA_TRANCHING_FLAG;
	}

	public String getLAA_TRANCHING_TYPE() {
		return this.LAA_TRANCHING_TYPE;
	}

	public void setLAA_TRANCHING_TYPE(String LAA_TRANCHING_TYPE) {
		this.LAA_TRANCHING_TYPE = LAA_TRANCHING_TYPE;
	}

	public String getLAA_COMPOUND_FREQ() {
		return this.LAA_COMPOUND_FREQ;
	}

	public void setLAA_COMPOUND_FREQ(String LAA_COMPOUND_FREQ) {
		this.LAA_COMPOUND_FREQ = LAA_COMPOUND_FREQ;
	}

	public String getLAA_INT_REBATE_FLAG() {
		return this.LAA_INT_REBATE_FLAG;
	}

	public void setLAA_INT_REBATE_FLAG(String LAA_INT_REBATE_FLAG) {
		this.LAA_INT_REBATE_FLAG = LAA_INT_REBATE_FLAG;
	}

	public BigDecimal getLAA_ACTUALIRR() {
		return this.LAA_ACTUALIRR;
	}

	public void setLAA_ACTUALIRR(BigDecimal LAA_ACTUALIRR) {
		this.LAA_ACTUALIRR = LAA_ACTUALIRR;
	}

	public BigDecimal getLAA_GROSS_LTV() {
		return this.LAA_GROSS_LTV;
	}

	public void setLAA_GROSS_LTV(BigDecimal LAA_GROSS_LTV) {
		this.LAA_GROSS_LTV = LAA_GROSS_LTV;
	}

	public BigDecimal getLAA_NET_LTV() {
		return this.LAA_NET_LTV;
	}

	public void setLAA_NET_LTV(BigDecimal LAA_NET_LTV) {
		this.LAA_NET_LTV = LAA_NET_LTV;
	}

	public String getCREATED_BY() {
		return this.CREATED_BY;
	}

	public void setCREATED_BY(String CREATED_BY) {
		this.CREATED_BY = CREATED_BY;
	}

	public Date getCREATED_ON() {
		return this.CREATED_ON;
	}

	public void setCREATED_ON(Date CREATED_ON) {
		this.CREATED_ON = CREATED_ON;
	}

	public String getMODIFIED_BY() {
		return this.MODIFIED_BY;
	}

	public void setMODIFIED_BY(String MODIFIED_BY) {
		this.MODIFIED_BY = MODIFIED_BY;
	}

	public Date getMODIFIED_ON() {
		return this.MODIFIED_ON;
	}

	public void setMODIFIED_ON(Date MODIFIED_ON) {
		this.MODIFIED_ON = MODIFIED_ON;
	}

	public BigDecimal getLAA_APP_REQ_IRR_N() {
		return this.LAA_APP_REQ_IRR_N;
	}

	public void setLAA_APP_REQ_IRR_N(BigDecimal LAA_APP_REQ_IRR_N) {
		this.LAA_APP_REQ_IRR_N = LAA_APP_REQ_IRR_N;
	}

	public BigDecimal getLAA_APP_REQ_EFFRATE_N() {
		return this.LAA_APP_REQ_EFFRATE_N;
	}

	public void setLAA_APP_REQ_EFFRATE_N(BigDecimal LAA_APP_REQ_EFFRATE_N) {
		this.LAA_APP_REQ_EFFRATE_N = LAA_APP_REQ_EFFRATE_N;
	}

	public BigDecimal getLAA_APP_APPR_EFFRATE_N() {
		return this.LAA_APP_APPR_EFFRATE_N;
	}

	public void setLAA_APP_APPR_EFFRATE_N(BigDecimal LAA_APP_APPR_EFFRATE_N) {
		this.LAA_APP_APPR_EFFRATE_N = LAA_APP_APPR_EFFRATE_N;
	}

	public Integer getLAA_SOURCE_ASSET_MODELID_N() {
		return this.LAA_SOURCE_ASSET_MODELID_N;
	}

	public void setLAA_SOURCE_ASSET_MODELID_N(Integer LAA_SOURCE_ASSET_MODELID_N) {
		this.LAA_SOURCE_ASSET_MODELID_N = LAA_SOURCE_ASSET_MODELID_N;
	}

	public String getLAA_SOURCE_ASSET_MAKE_C() {
		return this.LAA_SOURCE_ASSET_MAKE_C;
	}

	public void setLAA_SOURCE_ASSET_MAKE_C(String LAA_SOURCE_ASSET_MAKE_C) {
		this.LAA_SOURCE_ASSET_MAKE_C = LAA_SOURCE_ASSET_MAKE_C;
	}

	public String getLAA_SOURCE_CHANNEL_PARTNER_C() {
		return this.LAA_SOURCE_CHANNEL_PARTNER_C;
	}

	public void setLAA_SOURCE_CHANNEL_PARTNER_C(
			String LAA_SOURCE_CHANNEL_PARTNER_C) {
		this.LAA_SOURCE_CHANNEL_PARTNER_C = LAA_SOURCE_CHANNEL_PARTNER_C;
	}

	public String getLAA_APP_FIRST_SOURCETYPE_C() {
		return this.LAA_APP_FIRST_SOURCETYPE_C;
	}

	public void setLAA_APP_FIRST_SOURCETYPE_C(String LAA_APP_FIRST_SOURCETYPE_C) {
		this.LAA_APP_FIRST_SOURCETYPE_C = LAA_APP_FIRST_SOURCETYPE_C;
	}

	public String getLAA_APP_FIRST_SOURCE_ID_C() {
		return this.LAA_APP_FIRST_SOURCE_ID_C;
	}

	public void setLAA_APP_FIRST_SOURCE_ID_C(String LAA_APP_FIRST_SOURCE_ID_C) {
		this.LAA_APP_FIRST_SOURCE_ID_C = LAA_APP_FIRST_SOURCE_ID_C;
	}

	public Short getLAA_SOURCE_ASSET_AGE_N() {
		return this.LAA_SOURCE_ASSET_AGE_N;
	}

	public void setLAA_SOURCE_ASSET_AGE_N(Short LAA_SOURCE_ASSET_AGE_N) {
		this.LAA_SOURCE_ASSET_AGE_N = LAA_SOURCE_ASSET_AGE_N;
	}

	public Integer getLAA_SOURCE_MARKETINGID_N() {
		return this.LAA_SOURCE_MARKETINGID_N;
	}

	public void setLAA_SOURCE_MARKETINGID_N(Integer LAA_SOURCE_MARKETINGID_N) {
		this.LAA_SOURCE_MARKETINGID_N = LAA_SOURCE_MARKETINGID_N;
	}

	public Integer getLAA_SOURCE_BROKERID_N() {
		return this.LAA_SOURCE_BROKERID_N;
	}

	public void setLAA_SOURCE_BROKERID_N(Integer LAA_SOURCE_BROKERID_N) {
		this.LAA_SOURCE_BROKERID_N = LAA_SOURCE_BROKERID_N;
	}

	public Integer getLAA_SOURCE_INSPECTORID_N() {
		return this.LAA_SOURCE_INSPECTORID_N;
	}

	public void setLAA_SOURCE_INSPECTORID_N(Integer LAA_SOURCE_INSPECTORID_N) {
		this.LAA_SOURCE_INSPECTORID_N = LAA_SOURCE_INSPECTORID_N;
	}

	public String getLAA_EXISTING_CUSTOMER_C() {
		return this.LAA_EXISTING_CUSTOMER_C;
	}

	public void setLAA_EXISTING_CUSTOMER_C(String LAA_EXISTING_CUSTOMER_C) {
		this.LAA_EXISTING_CUSTOMER_C = LAA_EXISTING_CUSTOMER_C;
	}

	public Short getLAA_ADVANCEINSTL_N() {
		return this.LAA_ADVANCEINSTL_N;
	}

	public void setLAA_ADVANCEINSTL_N(Short LAA_ADVANCEINSTL_N) {
		this.LAA_ADVANCEINSTL_N = LAA_ADVANCEINSTL_N;
	}

	public Long getLAA_APP_NUMINSTL_N() {
		return this.LAA_APP_NUMINSTL_N;
	}

	public void setLAA_APP_NUMINSTL_N(Long LAA_APP_NUMINSTL_N) {
		this.LAA_APP_NUMINSTL_N = LAA_APP_NUMINSTL_N;
	}

	public String getLAA_APP_REQ_FREQ_C() {
		return this.LAA_APP_REQ_FREQ_C;
	}

	public void setLAA_APP_REQ_FREQ_C(String LAA_APP_REQ_FREQ_C) {
		this.LAA_APP_REQ_FREQ_C = LAA_APP_REQ_FREQ_C;
	}

	public String getLAA_APP_TYPE_C() {
		return this.LAA_APP_TYPE_C;
	}

	public void setLAA_APP_TYPE_C(String LAA_APP_TYPE_C) {
		this.LAA_APP_TYPE_C = LAA_APP_TYPE_C;
	}

	public String getLAA_LOAN_PURPOSE_C() {
		return this.LAA_LOAN_PURPOSE_C;
	}

	public void setLAA_LOAN_PURPOSE_C(String LAA_LOAN_PURPOSE_C) {
		this.LAA_LOAN_PURPOSE_C = LAA_LOAN_PURPOSE_C;
	}

	public String getLAA_LOAN_PURPOSE_DTL_C() {
		return this.LAA_LOAN_PURPOSE_DTL_C;
	}

	public void setLAA_LOAN_PURPOSE_DTL_C(String LAA_LOAN_PURPOSE_DTL_C) {
		this.LAA_LOAN_PURPOSE_DTL_C = LAA_LOAN_PURPOSE_DTL_C;
	}

	public String getLAA_LOAN_PURPOSE_DESC_C() {
		return this.LAA_LOAN_PURPOSE_DESC_C;
	}

	public void setLAA_LOAN_PURPOSE_DESC_C(String LAA_LOAN_PURPOSE_DESC_C) {
		this.LAA_LOAN_PURPOSE_DESC_C = LAA_LOAN_PURPOSE_DESC_C;
	}

	public Integer getLAA_LCM_CATGID_N() {
		return this.LAA_LCM_CATGID_N;
	}

	public void setLAA_LCM_CATGID_N(Integer LAA_LCM_CATGID_N) {
		this.LAA_LCM_CATGID_N = LAA_LCM_CATGID_N;
	}

	public BigDecimal getLAA_FOIR_N() {
		return this.LAA_FOIR_N;
	}

	public void setLAA_FOIR_N(BigDecimal LAA_FOIR_N) {
		this.LAA_FOIR_N = LAA_FOIR_N;
	}

	public BigDecimal getLAA_EXPOSURE_CAP_N() {
		return this.LAA_EXPOSURE_CAP_N;
	}

	public void setLAA_EXPOSURE_CAP_N(BigDecimal LAA_EXPOSURE_CAP_N) {
		this.LAA_EXPOSURE_CAP_N = LAA_EXPOSURE_CAP_N;
	}

	public BigDecimal getLAA_AVG_BAL_N() {
		return this.LAA_AVG_BAL_N;
	}

	public void setLAA_AVG_BAL_N(BigDecimal LAA_AVG_BAL_N) {
		this.LAA_AVG_BAL_N = LAA_AVG_BAL_N;
	}

	public BigDecimal getLAA_APPR_FOIR_N() {
		return this.LAA_APPR_FOIR_N;
	}

	public void setLAA_APPR_FOIR_N(BigDecimal LAA_APPR_FOIR_N) {
		this.LAA_APPR_FOIR_N = LAA_APPR_FOIR_N;
	}

	public BigDecimal getLAA_APPR_INSR_N() {
		return this.LAA_APPR_INSR_N;
	}

	public void setLAA_APPR_INSR_N(BigDecimal LAA_APPR_INSR_N) {
		this.LAA_APPR_INSR_N = LAA_APPR_INSR_N;
	}

	public BigDecimal getLAA_APPR_LTV_N() {
		return this.LAA_APPR_LTV_N;
	}

	public void setLAA_APPR_LTV_N(BigDecimal LAA_APPR_LTV_N) {
		this.LAA_APPR_LTV_N = LAA_APPR_LTV_N;
	}

	public BigDecimal getLAA_APPR_IIR_N() {
		return this.LAA_APPR_IIR_N;
	}

	public void setLAA_APPR_IIR_N(BigDecimal LAA_APPR_IIR_N) {
		this.LAA_APPR_IIR_N = LAA_APPR_IIR_N;
	}

	public BigDecimal getLAA_BENEFIT_AMOUNT_N() {
		return this.LAA_BENEFIT_AMOUNT_N;
	}

	public void setLAA_BENEFIT_AMOUNT_N(BigDecimal LAA_BENEFIT_AMOUNT_N) {
		this.LAA_BENEFIT_AMOUNT_N = LAA_BENEFIT_AMOUNT_N;
	}

	public String getLAA_APP_SIGN_TYPE_C() {
		return this.LAA_APP_SIGN_TYPE_C;
	}

	public void setLAA_APP_SIGN_TYPE_C(String LAA_APP_SIGN_TYPE_C) {
		this.LAA_APP_SIGN_TYPE_C = LAA_APP_SIGN_TYPE_C;
	}

	public String getLAA_GRACE_INTEREST_CHARGE_C() {
		return this.LAA_GRACE_INTEREST_CHARGE_C;
	}

	public void setLAA_GRACE_INTEREST_CHARGE_C(
			String LAA_GRACE_INTEREST_CHARGE_C) {
		this.LAA_GRACE_INTEREST_CHARGE_C = LAA_GRACE_INTEREST_CHARGE_C;
	}

	public String getLAA_GRACE_ADJUST_SCHEDULE_C() {
		return this.LAA_GRACE_ADJUST_SCHEDULE_C;
	}

	public void setLAA_GRACE_ADJUST_SCHEDULE_C(
			String LAA_GRACE_ADJUST_SCHEDULE_C) {
		this.LAA_GRACE_ADJUST_SCHEDULE_C = LAA_GRACE_ADJUST_SCHEDULE_C;
	}

	public BigDecimal getLAA_VAT_PRIN_RATE_N() {
		return this.LAA_VAT_PRIN_RATE_N;
	}

	public void setLAA_VAT_PRIN_RATE_N(BigDecimal LAA_VAT_PRIN_RATE_N) {
		this.LAA_VAT_PRIN_RATE_N = LAA_VAT_PRIN_RATE_N;
	}

	public BigDecimal getLAA_VAT_INT_RATE_N() {
		return this.LAA_VAT_INT_RATE_N;
	}

	public void setLAA_VAT_INT_RATE_N(BigDecimal LAA_VAT_INT_RATE_N) {
		this.LAA_VAT_INT_RATE_N = LAA_VAT_INT_RATE_N;
	}

	public BigDecimal getLAA_VAT_INSTL_RATE_N() {
		return this.LAA_VAT_INSTL_RATE_N;
	}

	public void setLAA_VAT_INSTL_RATE_N(BigDecimal LAA_VAT_INSTL_RATE_N) {
		this.LAA_VAT_INSTL_RATE_N = LAA_VAT_INSTL_RATE_N;
	}

	public String getLAA_INT_ROUNDOFF_PARA_C() {
		return this.LAA_INT_ROUNDOFF_PARA_C;
	}

	public void setLAA_INT_ROUNDOFF_PARA_C(String LAA_INT_ROUNDOFF_PARA_C) {
		this.LAA_INT_ROUNDOFF_PARA_C = LAA_INT_ROUNDOFF_PARA_C;
	}

	public Integer getLAA_INT_ROUNDTILL_N() {
		return this.LAA_INT_ROUNDTILL_N;
	}

	public void setLAA_INT_ROUNDTILL_N(Integer LAA_INT_ROUNDTILL_N) {
		this.LAA_INT_ROUNDTILL_N = LAA_INT_ROUNDTILL_N;
	}

	public Integer getLAA_INSTLAMT_ROUNDTILL_N() {
		return this.LAA_INSTLAMT_ROUNDTILL_N;
	}

	public void setLAA_INSTLAMT_ROUNDTILL_N(Integer LAA_INSTLAMT_ROUNDTILL_N) {
		this.LAA_INSTLAMT_ROUNDTILL_N = LAA_INSTLAMT_ROUNDTILL_N;
	}

	public String getLAA_INSTLAMT_ROUNDOFF_PARA_C() {
		return this.LAA_INSTLAMT_ROUNDOFF_PARA_C;
	}

	public void setLAA_INSTLAMT_ROUNDOFF_PARA_C(
			String LAA_INSTLAMT_ROUNDOFF_PARA_C) {
		this.LAA_INSTLAMT_ROUNDOFF_PARA_C = LAA_INSTLAMT_ROUNDOFF_PARA_C;
	}

	public String getLAA_APP_SOURCE_TYPE_C() {
		return this.LAA_APP_SOURCE_TYPE_C;
	}

	public void setLAA_APP_SOURCE_TYPE_C(String LAA_APP_SOURCE_TYPE_C) {
		this.LAA_APP_SOURCE_TYPE_C = LAA_APP_SOURCE_TYPE_C;
	}

	public BigDecimal getLAA_EMI_N() {
		return this.LAA_EMI_N;
	}

	public void setLAA_EMI_N(BigDecimal LAA_EMI_N) {
		this.LAA_EMI_N = LAA_EMI_N;
	}

	public String getLAA_RATE_EMI_FLAG_C() {
		return this.LAA_RATE_EMI_FLAG_C;
	}

	public void setLAA_RATE_EMI_FLAG_C(String LAA_RATE_EMI_FLAG_C) {
		this.LAA_RATE_EMI_FLAG_C = LAA_RATE_EMI_FLAG_C;
	}

	public String getLAA_LPP_PRODCAT_C() {
		return this.LAA_LPP_PRODCAT_C;
	}

	public void setLAA_LPP_PRODCAT_C(String LAA_LPP_PRODCAT_C) {
		this.LAA_LPP_PRODCAT_C = LAA_LPP_PRODCAT_C;
	}

	public Boolean getLAA_DECIMALS_N() {
		return this.LAA_DECIMALS_N;
	}

	public void setLAA_DECIMALS_N(Boolean LAA_DECIMALS_N) {
		this.LAA_DECIMALS_N = LAA_DECIMALS_N;
	}

	public Short getLAA_DPERYR_N() {
		return this.LAA_DPERYR_N;
	}

	public void setLAA_DPERYR_N(Short LAA_DPERYR_N) {
		this.LAA_DPERYR_N = LAA_DPERYR_N;
	}

	public Byte getLAA_FORECLOSELOCKLN_N() {
		return this.LAA_FORECLOSELOCKLN_N;
	}

	public void setLAA_FORECLOSELOCKLN_N(Byte LAA_FORECLOSELOCKLN_N) {
		this.LAA_FORECLOSELOCKLN_N = LAA_FORECLOSELOCKLN_N;
	}

	public String getLAA_AGREEMENTTYPE_C() {
		return this.LAA_AGREEMENTTYPE_C;
	}

	public void setLAA_AGREEMENTTYPE_C(String LAA_AGREEMENTTYPE_C) {
		this.LAA_AGREEMENTTYPE_C = LAA_AGREEMENTTYPE_C;
	}

	public Integer getLAA_LSM_SCHEMEGROUP_N() {
		return this.LAA_LSM_SCHEMEGROUP_N;
	}

	public void setLAA_LSM_SCHEMEGROUP_N(Integer LAA_LSM_SCHEMEGROUP_N) {
		this.LAA_LSM_SCHEMEGROUP_N = LAA_LSM_SCHEMEGROUP_N;
	}

	public Integer getCUST_ID_N() {
		return this.CUST_ID_N;
	}

	public void setCUST_ID_N(Integer CUST_ID_N) {
		this.CUST_ID_N = CUST_ID_N;
	}

	public String getLAA_DEANNUALIZE_C() {
		return this.LAA_DEANNUALIZE_C;
	}

	public void setLAA_DEANNUALIZE_C(String LAA_DEANNUALIZE_C) {
		this.LAA_DEANNUALIZE_C = LAA_DEANNUALIZE_C;
	}

	public BigDecimal getLAA_AMTOTHERS_N() {
		return this.LAA_AMTOTHERS_N;
	}

	public void setLAA_AMTOTHERS_N(BigDecimal LAA_AMTOTHERS_N) {
		this.LAA_AMTOTHERS_N = LAA_AMTOTHERS_N;
	}

	public BigDecimal getLAA_TAXRATE_N() {
		return this.LAA_TAXRATE_N;
	}

	public void setLAA_TAXRATE_N(BigDecimal LAA_TAXRATE_N) {
		this.LAA_TAXRATE_N = LAA_TAXRATE_N;
	}

	public Date getCOMMENCEDATE() {
		return this.COMMENCEDATE;
	}

	public void setCOMMENCEDATE(Date COMMENCEDATE) {
		this.COMMENCEDATE = COMMENCEDATE;
	}

	public Short getLAA_PRIN_BASE_UNIT_N() {
		return this.LAA_PRIN_BASE_UNIT_N;
	}

	public void setLAA_PRIN_BASE_UNIT_N(Short LAA_PRIN_BASE_UNIT_N) {
		this.LAA_PRIN_BASE_UNIT_N = LAA_PRIN_BASE_UNIT_N;
	}

	public Date getINTSTART_DATE_REGULAR() {
		return this.INTSTART_DATE_REGULAR;
	}

	public void setINTSTART_DATE_REGULAR(Date INTSTART_DATE_REGULAR) {
		this.INTSTART_DATE_REGULAR = INTSTART_DATE_REGULAR;
	}

	public BigDecimal getLAA_REQ_IIR_N() {
		return this.LAA_REQ_IIR_N;
	}

	public void setLAA_REQ_IIR_N(BigDecimal LAA_REQ_IIR_N) {
		this.LAA_REQ_IIR_N = LAA_REQ_IIR_N;
	}

	public BigDecimal getLAA_APP_ASSETCOST_N() {
		return this.LAA_APP_ASSETCOST_N;
	}

	public void setLAA_APP_ASSETCOST_N(BigDecimal LAA_APP_ASSETCOST_N) {
		this.LAA_APP_ASSETCOST_N = LAA_APP_ASSETCOST_N;
	}

	public BigDecimal getLAA_APPRAISED_INC_N() {
		return this.LAA_APPRAISED_INC_N;
	}

	public void setLAA_APPRAISED_INC_N(BigDecimal LAA_APPRAISED_INC_N) {
		this.LAA_APPRAISED_INC_N = LAA_APPRAISED_INC_N;
	}

	public BigDecimal getLAA_APPRAISED_OBL_N() {
		return this.LAA_APPRAISED_OBL_N;
	}

	public void setLAA_APPRAISED_OBL_N(BigDecimal LAA_APPRAISED_OBL_N) {
		this.LAA_APPRAISED_OBL_N = LAA_APPRAISED_OBL_N;
	}

	public BigDecimal getLAA_APPLICABLE_FOIR_N() {
		return this.LAA_APPLICABLE_FOIR_N;
	}

	public void setLAA_APPLICABLE_FOIR_N(BigDecimal LAA_APPLICABLE_FOIR_N) {
		this.LAA_APPLICABLE_FOIR_N = LAA_APPLICABLE_FOIR_N;
	}

	public BigDecimal getLAA_APPLICABLE_LTV_N() {
		return this.LAA_APPLICABLE_LTV_N;
	}

	public void setLAA_APPLICABLE_LTV_N(BigDecimal LAA_APPLICABLE_LTV_N) {
		this.LAA_APPLICABLE_LTV_N = LAA_APPLICABLE_LTV_N;
	}

	public BigDecimal getLAA_EMI_FACTOR_N() {
		return this.LAA_EMI_FACTOR_N;
	}

	public void setLAA_EMI_FACTOR_N(BigDecimal LAA_EMI_FACTOR_N) {
		this.LAA_EMI_FACTOR_N = LAA_EMI_FACTOR_N;
	}

	public BigDecimal getLAA_TOTAL_ELIGIBILITY_N() {
		return this.LAA_TOTAL_ELIGIBILITY_N;
	}

	public void setLAA_TOTAL_ELIGIBILITY_N(BigDecimal LAA_TOTAL_ELIGIBILITY_N) {
		this.LAA_TOTAL_ELIGIBILITY_N = LAA_TOTAL_ELIGIBILITY_N;
	}

	public String getLAA_RISK_C() {
		return this.LAA_RISK_C;
	}

	public void setLAA_RISK_C(String LAA_RISK_C) {
		this.LAA_RISK_C = LAA_RISK_C;
	}

	public String getLAA_STRENGTH_C() {
		return this.LAA_STRENGTH_C;
	}

	public void setLAA_STRENGTH_C(String LAA_STRENGTH_C) {
		this.LAA_STRENGTH_C = LAA_STRENGTH_C;
	}

	public Integer getLAA_CPAID_N() {
		return this.LAA_CPAID_N;
	}

	public void setLAA_CPAID_N(Integer LAA_CPAID_N) {
		this.LAA_CPAID_N = LAA_CPAID_N;
	}

	public Date getLAA_APPROVAL_DATE_D() {
		return this.LAA_APPROVAL_DATE_D;
	}

	public void setLAA_APPROVAL_DATE_D(Date LAA_APPROVAL_DATE_D) {
		this.LAA_APPROVAL_DATE_D = LAA_APPROVAL_DATE_D;
	}

	public BigDecimal getLAA_VATINPUT_N() {
		return this.LAA_VATINPUT_N;
	}

	public void setLAA_VATINPUT_N(BigDecimal LAA_VATINPUT_N) {
		this.LAA_VATINPUT_N = LAA_VATINPUT_N;
	}

	public String getLAA_CUST_PROFILE_TYPE_C() {
		return this.LAA_CUST_PROFILE_TYPE_C;
	}

	public void setLAA_CUST_PROFILE_TYPE_C(String LAA_CUST_PROFILE_TYPE_C) {
		this.LAA_CUST_PROFILE_TYPE_C = LAA_CUST_PROFILE_TYPE_C;
	}

	public String getLAA_CUST_PROFILE_C() {
		return this.LAA_CUST_PROFILE_C;
	}

	public void setLAA_CUST_PROFILE_C(String LAA_CUST_PROFILE_C) {
		this.LAA_CUST_PROFILE_C = LAA_CUST_PROFILE_C;
	}

	public BigDecimal getLAA_OFFLINE_APP_ID_N() {
		return this.LAA_OFFLINE_APP_ID_N;
	}

	public void setLAA_OFFLINE_APP_ID_N(BigDecimal LAA_OFFLINE_APP_ID_N) {
		this.LAA_OFFLINE_APP_ID_N = LAA_OFFLINE_APP_ID_N;
	}

	public String getLAA_RCU_FLAG_C() {
		return this.LAA_RCU_FLAG_C;
	}

	public void setLAA_RCU_FLAG_C(String LAA_RCU_FLAG_C) {
		this.LAA_RCU_FLAG_C = LAA_RCU_FLAG_C;
	}

	public String getLOS_APP_POLICY_RESULT() {
		return this.LOS_APP_POLICY_RESULT;
	}

	public void setLOS_APP_POLICY_RESULT(String LOS_APP_POLICY_RESULT) {
		this.LOS_APP_POLICY_RESULT = LOS_APP_POLICY_RESULT;
	}

	public String getLOS_APP_SCORING_RESULT() {
		return this.LOS_APP_SCORING_RESULT;
	}

	public void setLOS_APP_SCORING_RESULT(String LOS_APP_SCORING_RESULT) {
		this.LOS_APP_SCORING_RESULT = LOS_APP_SCORING_RESULT;
	}

	public String getLOS_APP_FUZZY_MATCH() {
		return this.LOS_APP_FUZZY_MATCH;
	}

	public void setLOS_APP_FUZZY_MATCH(String LOS_APP_FUZZY_MATCH) {
		this.LOS_APP_FUZZY_MATCH = LOS_APP_FUZZY_MATCH;
	}

	public Integer getLOS_APP_POS_DEDUPE_COUNT() {
		return this.LOS_APP_POS_DEDUPE_COUNT;
	}

	public void setLOS_APP_POS_DEDUPE_COUNT(Integer LOS_APP_POS_DEDUPE_COUNT) {
		this.LOS_APP_POS_DEDUPE_COUNT = LOS_APP_POS_DEDUPE_COUNT;
	}

	public Integer getLOS_APP_NEG_DEDUPE_COUNT() {
		return this.LOS_APP_NEG_DEDUPE_COUNT;
	}

	public void setLOS_APP_NEG_DEDUPE_COUNT(Integer LOS_APP_NEG_DEDUPE_COUNT) {
		this.LOS_APP_NEG_DEDUPE_COUNT = LOS_APP_NEG_DEDUPE_COUNT;
	}

	public String getLAA_FII_STATUS() {
		return this.LAA_FII_STATUS;
	}

	public void setLAA_FII_STATUS(String LAA_FII_STATUS) {
		this.LAA_FII_STATUS = LAA_FII_STATUS;
	}

	public Character getLAA_APP_CHARGES_FLAG() {
		return this.LAA_APP_CHARGES_FLAG;
	}

	public void setLAA_APP_CHARGES_FLAG(Character LAA_APP_CHARGES_FLAG) {
		this.LAA_APP_CHARGES_FLAG = LAA_APP_CHARGES_FLAG;
	}

	public BigDecimal getLAA_APP_CALCULATION1() {
		return this.LAA_APP_CALCULATION1;
	}

	public void setLAA_APP_CALCULATION1(BigDecimal LAA_APP_CALCULATION1) {
		this.LAA_APP_CALCULATION1 = LAA_APP_CALCULATION1;
	}

	public BigDecimal getLAA_APP_CALCULATION2() {
		return this.LAA_APP_CALCULATION2;
	}

	public void setLAA_APP_CALCULATION2(BigDecimal LAA_APP_CALCULATION2) {
		this.LAA_APP_CALCULATION2 = LAA_APP_CALCULATION2;
	}

	public BigDecimal getLAA_APP_CALCULATION3() {
		return this.LAA_APP_CALCULATION3;
	}

	public void setLAA_APP_CALCULATION3(BigDecimal LAA_APP_CALCULATION3) {
		this.LAA_APP_CALCULATION3 = LAA_APP_CALCULATION3;
	}

	public BigDecimal getLAA_APP_REQ_PTPM_N() {
		return this.LAA_APP_REQ_PTPM_N;
	}

	public void setLAA_APP_REQ_PTPM_N(BigDecimal LAA_APP_REQ_PTPM_N) {
		this.LAA_APP_REQ_PTPM_N = LAA_APP_REQ_PTPM_N;
	}

	public String getCRS_APP_ID_C() {
		return this.CRS_APP_ID_C;
	}

	public void setCRS_APP_ID_C(String CRS_APP_ID_C) {
		this.CRS_APP_ID_C = CRS_APP_ID_C;
	}

	public Date getPRN_ON() {
		return this.PRN_ON;
	}

	public void setPRN_ON(Date PRN_ON) {
		this.PRN_ON = PRN_ON;
	}

	public String getLAA_LMS_STATUS() {
		return this.LAA_LMS_STATUS;
	}

	public void setLAA_LMS_STATUS(String LAA_LMS_STATUS) {
		this.LAA_LMS_STATUS = LAA_LMS_STATUS;
	}

	public String getLAA_LMS_DISB_STATUS() {
		return this.LAA_LMS_DISB_STATUS;
	}

	public void setLAA_LMS_DISB_STATUS(String LAA_LMS_DISB_STATUS) {
		this.LAA_LMS_DISB_STATUS = LAA_LMS_DISB_STATUS;
	}

	public Date getCREATION_DATE() {
		return this.CREATION_DATE;
	}

	public void setCREATION_DATE(Date CREATION_DATE) {
		this.CREATION_DATE = CREATION_DATE;
	}

	public String getLAA_FIELD_1() {
		return this.LAA_FIELD_1;
	}

	public void setLAA_FIELD_1(String LAA_FIELD_1) {
		this.LAA_FIELD_1 = LAA_FIELD_1;
	}

	public String getLAA_FIELD_2() {
		return this.LAA_FIELD_2;
	}

	public void setLAA_FIELD_2(String LAA_FIELD_2) {
		this.LAA_FIELD_2 = LAA_FIELD_2;
	}

	public Date getRCU_INITIATION_DATE_D() {
		return this.RCU_INITIATION_DATE_D;
	}

	public void setRCU_INITIATION_DATE_D(Date RCU_INITIATION_DATE_D) {
		this.RCU_INITIATION_DATE_D = RCU_INITIATION_DATE_D;
	}

	public Date getRCU_COMPLETION_DATE_D() {
		return this.RCU_COMPLETION_DATE_D;
	}

	public void setRCU_COMPLETION_DATE_D(Date RCU_COMPLETION_DATE_D) {
		this.RCU_COMPLETION_DATE_D = RCU_COMPLETION_DATE_D;
	}

	public String getNEGBASE_DEDUPE_INITIATED_C() {
		return this.NEGBASE_DEDUPE_INITIATED_C;
	}

	public void setNEGBASE_DEDUPE_INITIATED_C(String NEGBASE_DEDUPE_INITIATED_C) {
		this.NEGBASE_DEDUPE_INITIATED_C = NEGBASE_DEDUPE_INITIATED_C;
	}

	public String getCPV_INITIATED_C() {
		return this.CPV_INITIATED_C;
	}

	public void setCPV_INITIATED_C(String CPV_INITIATED_C) {
		this.CPV_INITIATED_C = CPV_INITIATED_C;
	}

	public String getDEVIATION_INITIATED_C() {
		return this.DEVIATION_INITIATED_C;
	}

	public void setDEVIATION_INITIATED_C(String DEVIATION_INITIATED_C) {
		this.DEVIATION_INITIATED_C = DEVIATION_INITIATED_C;
	}

	public BigDecimal getCUSTOMER_EXPOSURE_N() {
		return this.CUSTOMER_EXPOSURE_N;
	}

	public void setCUSTOMER_EXPOSURE_N(BigDecimal CUSTOMER_EXPOSURE_N) {
		this.CUSTOMER_EXPOSURE_N = CUSTOMER_EXPOSURE_N;
	}

	public BigDecimal getTOTAL_CUST_EXPOSURE_N() {
		return this.TOTAL_CUST_EXPOSURE_N;
	}

	public void setTOTAL_CUST_EXPOSURE_N(BigDecimal TOTAL_CUST_EXPOSURE_N) {
		this.TOTAL_CUST_EXPOSURE_N = TOTAL_CUST_EXPOSURE_N;
	}

	public String getSPECIAL_CONDITION_FOR_C() {
		return this.SPECIAL_CONDITION_FOR_C;
	}

	public void setSPECIAL_CONDITION_FOR_C(String SPECIAL_CONDITION_FOR_C) {
		this.SPECIAL_CONDITION_FOR_C = SPECIAL_CONDITION_FOR_C;
	}

	public String getSUB_CATEGORY() {
		return this.SUB_CATEGORY;
	}

	public void setSUB_CATEGORY(String SUB_CATEGORY) {
		this.SUB_CATEGORY = SUB_CATEGORY;
	}

	public String getLAA_FIELD_3() {
		return this.LAA_FIELD_3;
	}

	public void setLAA_FIELD_3(String LAA_FIELD_3) {
		this.LAA_FIELD_3 = LAA_FIELD_3;
	}

	public String getLAA_FIELD_4() {
		return this.LAA_FIELD_4;
	}

	public void setLAA_FIELD_4(String LAA_FIELD_4) {
		this.LAA_FIELD_4 = LAA_FIELD_4;
	}

	public String getLAA_FIELD_5() {
		return this.LAA_FIELD_5;
	}

	public void setLAA_FIELD_5(String LAA_FIELD_5) {
		this.LAA_FIELD_5 = LAA_FIELD_5;
	}

	public String getLAA_FIELD_6() {
		return this.LAA_FIELD_6;
	}

	public void setLAA_FIELD_6(String LAA_FIELD_6) {
		this.LAA_FIELD_6 = LAA_FIELD_6;
	}

	public String getLAA_FIELD_7() {
		return this.LAA_FIELD_7;
	}

	public void setLAA_FIELD_7(String LAA_FIELD_7) {
		this.LAA_FIELD_7 = LAA_FIELD_7;
	}

	public String getLAA_FIELD_8() {
		return this.LAA_FIELD_8;
	}

	public void setLAA_FIELD_8(String LAA_FIELD_8) {
		this.LAA_FIELD_8 = LAA_FIELD_8;
	}

	public String getLAA_FIELD_9() {
		return this.LAA_FIELD_9;
	}

	public void setLAA_FIELD_9(String LAA_FIELD_9) {
		this.LAA_FIELD_9 = LAA_FIELD_9;
	}

	public String getLAA_FIELD_10() {
		return this.LAA_FIELD_10;
	}

	public void setLAA_FIELD_10(String LAA_FIELD_10) {
		this.LAA_FIELD_10 = LAA_FIELD_10;
	}

	public String getLAA_FIELD_11() {
		return this.LAA_FIELD_11;
	}

	public void setLAA_FIELD_11(String LAA_FIELD_11) {
		this.LAA_FIELD_11 = LAA_FIELD_11;
	}

	public String getLAA_FIELD_12() {
		return this.LAA_FIELD_12;
	}

	public void setLAA_FIELD_12(String LAA_FIELD_12) {
		this.LAA_FIELD_12 = LAA_FIELD_12;
	}

	public String getLAA_FIELD_13() {
		return this.LAA_FIELD_13;
	}

	public void setLAA_FIELD_13(String LAA_FIELD_13) {
		this.LAA_FIELD_13 = LAA_FIELD_13;
	}

	public String getLAA_FIELD_14() {
		return this.LAA_FIELD_14;
	}

	public void setLAA_FIELD_14(String LAA_FIELD_14) {
		this.LAA_FIELD_14 = LAA_FIELD_14;
	}

	public String getLAA_DEALER_FUNDING() {
		return this.LAA_DEALER_FUNDING;
	}

	public void setLAA_DEALER_FUNDING(String LAA_DEALER_FUNDING) {
		this.LAA_DEALER_FUNDING = LAA_DEALER_FUNDING;
	}

	public String getRMS_FLAG_C() {
		return this.RMS_FLAG_C;
	}

	public void setRMS_FLAG_C(String RMS_FLAG_C) {
		this.RMS_FLAG_C = RMS_FLAG_C;
	}

	public String getRMS_STATUS_C() {
		return this.RMS_STATUS_C;
	}

	public void setRMS_STATUS_C(String RMS_STATUS_C) {
		this.RMS_STATUS_C = RMS_STATUS_C;
	}

	public String getRMS_FORWARD_C() {
		return this.RMS_FORWARD_C;
	}

	public void setRMS_FORWARD_C(String RMS_FORWARD_C) {
		this.RMS_FORWARD_C = RMS_FORWARD_C;
	}

	public String getREJECT_REVIEW__STATUS_C() {
		return this.REJECT_REVIEW__STATUS_C;
	}

	public void setREJECT_REVIEW__STATUS_C(String REJECT_REVIEW__STATUS_C) {
		this.REJECT_REVIEW__STATUS_C = REJECT_REVIEW__STATUS_C;
	}

	public Date getREJECT_REVIEW__DATE_D() {
		return this.REJECT_REVIEW__DATE_D;
	}

	public void setREJECT_REVIEW__DATE_D(Date REJECT_REVIEW__DATE_D) {
		this.REJECT_REVIEW__DATE_D = REJECT_REVIEW__DATE_D;
	}

	public Integer getLOS_APP_POS_MINI_COUNT() {
		return this.LOS_APP_POS_MINI_COUNT;
	}

	public void setLOS_APP_POS_MINI_COUNT(Integer LOS_APP_POS_MINI_COUNT) {
		this.LOS_APP_POS_MINI_COUNT = LOS_APP_POS_MINI_COUNT;
	}

	public Character getLAA_APP_CALPRINCIPAL_C() {
		return this.LAA_APP_CALPRINCIPAL_C;
	}

	public void setLAA_APP_CALPRINCIPAL_C(Character LAA_APP_CALPRINCIPAL_C) {
		this.LAA_APP_CALPRINCIPAL_C = LAA_APP_CALPRINCIPAL_C;
	}

	public String getINTERESTINADVANCE() {
		return this.INTERESTINADVANCE;
	}

	public void setINTERESTINADVANCE(String INTERESTINADVANCE) {
		this.INTERESTINADVANCE = INTERESTINADVANCE;
	}

	public String getC_UNDESIRABLE_LOC_FLAG() {
		return this.C_UNDESIRABLE_LOC_FLAG;
	}

	public void setC_UNDESIRABLE_LOC_FLAG(String C_UNDESIRABLE_LOC_FLAG) {
		this.C_UNDESIRABLE_LOC_FLAG = C_UNDESIRABLE_LOC_FLAG;
	}

	public Short getC_PCT_TABLE_NO() {
		return this.C_PCT_TABLE_NO;
	}

	public void setC_PCT_TABLE_NO(Short C_PCT_TABLE_NO) {
		this.C_PCT_TABLE_NO = C_PCT_TABLE_NO;
	}

	public String getVC_SOURCE_CD() {
		return this.VC_SOURCE_CD;
	}

	public void setVC_SOURCE_CD(String VC_SOURCE_CD) {
		this.VC_SOURCE_CD = VC_SOURCE_CD;
	}

	public String getVC_REFINANCED_FROM() {
		return this.VC_REFINANCED_FROM;
	}

	public void setVC_REFINANCED_FROM(String VC_REFINANCED_FROM) {
		this.VC_REFINANCED_FROM = VC_REFINANCED_FROM;
	}

	public String getVC_REFERRAL_GRP() {
		return this.VC_REFERRAL_GRP;
	}

	public void setVC_REFERRAL_GRP(String VC_REFERRAL_GRP) {
		this.VC_REFERRAL_GRP = VC_REFERRAL_GRP;
	}

	public String getVC_REFERRAL_CD() {
		return this.VC_REFERRAL_CD;
	}

	public void setVC_REFERRAL_CD(String VC_REFERRAL_CD) {
		this.VC_REFERRAL_CD = VC_REFERRAL_CD;
	}

	public String getVC_REFERRAL_NAME() {
		return this.VC_REFERRAL_NAME;
	}

	public void setVC_REFERRAL_NAME(String VC_REFERRAL_NAME) {
		this.VC_REFERRAL_NAME = VC_REFERRAL_NAME;
	}

	public String getVC_BRANCH_NAME() {
		return this.VC_BRANCH_NAME;
	}

	public void setVC_BRANCH_NAME(String VC_BRANCH_NAME) {
		this.VC_BRANCH_NAME = VC_BRANCH_NAME;
	}

	public String getVC_ACCOUNT_OFF_CD() {
		return this.VC_ACCOUNT_OFF_CD;
	}

	public void setVC_ACCOUNT_OFF_CD(String VC_ACCOUNT_OFF_CD) {
		this.VC_ACCOUNT_OFF_CD = VC_ACCOUNT_OFF_CD;
	}

	public String getVC_ACCTOUNT_OFF_CD() {
		return this.VC_ACCTOUNT_OFF_CD;
	}

	public void setVC_ACCTOUNT_OFF_CD(String VC_ACCTOUNT_OFF_CD) {
		this.VC_ACCTOUNT_OFF_CD = VC_ACCTOUNT_OFF_CD;
	}

	public String getVC_ACCOUNT_OFFICER() {
		return this.VC_ACCOUNT_OFFICER;
	}

	public void setVC_ACCOUNT_OFFICER(String VC_ACCOUNT_OFFICER) {
		this.VC_ACCOUNT_OFFICER = VC_ACCOUNT_OFFICER;
	}

	public String getVC_REQ_FREQUENCY() {
		return this.VC_REQ_FREQUENCY;
	}

	public void setVC_REQ_FREQUENCY(String VC_REQ_FREQUENCY) {
		this.VC_REQ_FREQUENCY = VC_REQ_FREQUENCY;
	}

	public String getVC_POLICY_TYPE() {
		return this.VC_POLICY_TYPE;
	}

	public void setVC_POLICY_TYPE(String VC_POLICY_TYPE) {
		this.VC_POLICY_TYPE = VC_POLICY_TYPE;
	}

	public String getVC_LOANTYPE() {
		return this.VC_LOANTYPE;
	}

	public void setVC_LOANTYPE(String VC_LOANTYPE) {
		this.VC_LOANTYPE = VC_LOANTYPE;
	}

	public BigDecimal getN_ADD_RATE() {
		return this.N_ADD_RATE;
	}

	public void setN_ADD_RATE(BigDecimal N_ADD_RATE) {
		this.N_ADD_RATE = N_ADD_RATE;
	}

	public BigDecimal getN_EFFECTIVE_YIELD() {
		return this.N_EFFECTIVE_YIELD;
	}

	public void setN_EFFECTIVE_YIELD(BigDecimal N_EFFECTIVE_YIELD) {
		this.N_EFFECTIVE_YIELD = N_EFFECTIVE_YIELD;
	}

	public BigDecimal getN_NET_EFFECTIVE() {
		return this.N_NET_EFFECTIVE;
	}

	public void setN_NET_EFFECTIVE(BigDecimal N_NET_EFFECTIVE) {
		this.N_NET_EFFECTIVE = N_NET_EFFECTIVE;
	}

	public String getVC_BRANCH() {
		return this.VC_BRANCH;
	}

	public void setVC_BRANCH(String VC_BRANCH) {
		this.VC_BRANCH = VC_BRANCH;
	}

	public String getN_BILLING_CYCLE_ID() {
		return this.N_BILLING_CYCLE_ID;
	}

	public void setN_BILLING_CYCLE_ID(String N_BILLING_CYCLE_ID) {
		this.N_BILLING_CYCLE_ID = N_BILLING_CYCLE_ID;
	}

	public BigDecimal getLAA_CALCULATED_INCOME() {
		return this.LAA_CALCULATED_INCOME;
	}

	public void setLAA_CALCULATED_INCOME(BigDecimal LAA_CALCULATED_INCOME) {
		this.LAA_CALCULATED_INCOME = LAA_CALCULATED_INCOME;
	}

	public BigDecimal getLAA_DBR() {
		return this.LAA_DBR;
	}

	public void setLAA_DBR(BigDecimal LAA_DBR) {
		this.LAA_DBR = LAA_DBR;
	}

	public BigDecimal getLAA_APPRAISED_NET_LTV() {
		return this.LAA_APPRAISED_NET_LTV;
	}

	public void setLAA_APPRAISED_NET_LTV(BigDecimal LAA_APPRAISED_NET_LTV) {
		this.LAA_APPRAISED_NET_LTV = LAA_APPRAISED_NET_LTV;
	}

	public String getNCM_DRAFTSAVE() {
		return this.NCM_DRAFTSAVE;
	}

	public void setNCM_DRAFTSAVE(String NCM_DRAFTSAVE) {
		this.NCM_DRAFTSAVE = NCM_DRAFTSAVE;
	}

	public String getVC_PRE_COMPANY() {
		return this.VC_PRE_COMPANY;
	}

	public void setVC_PRE_COMPANY(String VC_PRE_COMPANY) {
		this.VC_PRE_COMPANY = VC_PRE_COMPANY;
	}

	public String getVC_PLAN_TYPE() {
		return this.VC_PLAN_TYPE;
	}

	public void setVC_PLAN_TYPE(String VC_PLAN_TYPE) {
		this.VC_PLAN_TYPE = VC_PLAN_TYPE;
	}

	public String getVC_PLAN_CLASS() {
		return this.VC_PLAN_CLASS;
	}

	public void setVC_PLAN_CLASS(String VC_PLAN_CLASS) {
		this.VC_PLAN_CLASS = VC_PLAN_CLASS;
	}

	public String getVC_POL_NO() {
		return this.VC_POL_NO;
	}

	public void setVC_POL_NO(String VC_POL_NO) {
		this.VC_POL_NO = VC_POL_NO;
	}

	public BigDecimal getN_PRE_PRICE() {
		return this.N_PRE_PRICE;
	}

	public void setN_PRE_PRICE(BigDecimal N_PRE_PRICE) {
		this.N_PRE_PRICE = N_PRE_PRICE;
	}

	public Date getD_POLICYISSUEDATE() {
		return this.D_POLICYISSUEDATE;
	}

	public void setD_POLICYISSUEDATE(Date D_POLICYISSUEDATE) {
		this.D_POLICYISSUEDATE = D_POLICYISSUEDATE;
	}

	public Date getDATED_POLICYMATURITY() {
		return this.DATED_POLICYMATURITY;
	}

	public void setDATED_POLICYMATURITY(Date DATED_POLICYMATURITY) {
		this.DATED_POLICYMATURITY = DATED_POLICYMATURITY;
	}

	public String getVC_RELATION_AIF() {
		return this.VC_RELATION_AIF;
	}

	public void setVC_RELATION_AIF(String VC_RELATION_AIF) {
		this.VC_RELATION_AIF = VC_RELATION_AIF;
	}

	public BigDecimal getN_CONSTRUCTION_COST() {
		return this.N_CONSTRUCTION_COST;
	}

	public void setN_CONSTRUCTION_COST(BigDecimal N_CONSTRUCTION_COST) {
		this.N_CONSTRUCTION_COST = N_CONSTRUCTION_COST;
	}

	public String getVC_RATE_FIXING() {
		return this.VC_RATE_FIXING;
	}

	public void setVC_RATE_FIXING(String VC_RATE_FIXING) {
		this.VC_RATE_FIXING = VC_RATE_FIXING;
	}

	public String getVC_REPRICING_FORMULA() {
		return this.VC_REPRICING_FORMULA;
	}

	public void setVC_REPRICING_FORMULA(String VC_REPRICING_FORMULA) {
		this.VC_REPRICING_FORMULA = VC_REPRICING_FORMULA;
	}

	public Short getN_INTEREST_RATE() {
		return this.N_INTEREST_RATE;
	}

	public void setN_INTEREST_RATE(Short N_INTEREST_RATE) {
		this.N_INTEREST_RATE = N_INTEREST_RATE;
	}

	public Short getN_EQUITY_PERCNT() {
		return this.N_EQUITY_PERCNT;
	}

	public void setN_EQUITY_PERCNT(Short N_EQUITY_PERCNT) {
		this.N_EQUITY_PERCNT = N_EQUITY_PERCNT;
	}

	public String getVC_AIF() {
		return this.VC_AIF;
	}

	public void setVC_AIF(String VC_AIF) {
		this.VC_AIF = VC_AIF;
	}

	public BigDecimal getLAA_GROSS_MONTHLY_PAY() {
		return this.LAA_GROSS_MONTHLY_PAY;
	}

	public void setLAA_GROSS_MONTHLY_PAY(BigDecimal LAA_GROSS_MONTHLY_PAY) {
		this.LAA_GROSS_MONTHLY_PAY = LAA_GROSS_MONTHLY_PAY;
	}

	public BigDecimal getLAA_CREDIT_LIMIT() {
		return this.LAA_CREDIT_LIMIT;
	}

	public void setLAA_CREDIT_LIMIT(BigDecimal LAA_CREDIT_LIMIT) {
		this.LAA_CREDIT_LIMIT = LAA_CREDIT_LIMIT;
	}

	public String getCPV_INITIATED_AGENCY_TYPE() {
		return this.CPV_INITIATED_AGENCY_TYPE;
	}

	public void setCPV_INITIATED_AGENCY_TYPE(String CPV_INITIATED_AGENCY_TYPE) {
		this.CPV_INITIATED_AGENCY_TYPE = CPV_INITIATED_AGENCY_TYPE;
	}

	public Short getDEALER_PARTIC_RATE() {
		return this.DEALER_PARTIC_RATE;
	}

	public void setDEALER_PARTIC_RATE(Short DEALER_PARTIC_RATE) {
		this.DEALER_PARTIC_RATE = DEALER_PARTIC_RATE;
	}

	public BigDecimal getFINANCIAL_QUANTUM() {
		return this.FINANCIAL_QUANTUM;
	}

	public void setFINANCIAL_QUANTUM(BigDecimal FINANCIAL_QUANTUM) {
		this.FINANCIAL_QUANTUM = FINANCIAL_QUANTUM;
	}

	public String getDUEMONTH_C() {
		return this.DUEMONTH_C;
	}

	public void setDUEMONTH_C(String DUEMONTH_C) {
		this.DUEMONTH_C = DUEMONTH_C;
	}

	public BigDecimal getLAA_RATE_N() {
		return this.LAA_RATE_N;
	}

	public void setLAA_RATE_N(BigDecimal LAA_RATE_N) {
		this.LAA_RATE_N = LAA_RATE_N;
	}

	public BigDecimal getLAA_COST_OF_FUNDS_N() {
		return this.LAA_COST_OF_FUNDS_N;
	}

	public void setLAA_COST_OF_FUNDS_N(BigDecimal LAA_COST_OF_FUNDS_N) {
		this.LAA_COST_OF_FUNDS_N = LAA_COST_OF_FUNDS_N;
	}

	public BigDecimal getLAA_LOSS_N() {
		return this.LAA_LOSS_N;
	}

	public void setLAA_LOSS_N(BigDecimal LAA_LOSS_N) {
		this.LAA_LOSS_N = LAA_LOSS_N;
	}

	public BigDecimal getLAA_EXPENSES_N() {
		return this.LAA_EXPENSES_N;
	}

	public void setLAA_EXPENSES_N(BigDecimal LAA_EXPENSES_N) {
		this.LAA_EXPENSES_N = LAA_EXPENSES_N;
	}

	public BigDecimal getLAA_CUSTOMER_YIELD_N() {
		return this.LAA_CUSTOMER_YIELD_N;
	}

	public void setLAA_CUSTOMER_YIELD_N(BigDecimal LAA_CUSTOMER_YIELD_N) {
		this.LAA_CUSTOMER_YIELD_N = LAA_CUSTOMER_YIELD_N;
	}

	public String getLAA_SALESPERSON_C() {
		return this.LAA_SALESPERSON_C;
	}

	public void setLAA_SALESPERSON_C(String LAA_SALESPERSON_C) {
		this.LAA_SALESPERSON_C = LAA_SALESPERSON_C;
	}

	public String getDEALID_C() {
		return this.DEALID_C;
	}

	public void setDEALID_C(String DEALID_C) {
		this.DEALID_C = DEALID_C;
	}

	public String getBD_TYPE_C() {
		return this.BD_TYPE_C;
	}

	public void setBD_TYPE_C(String BD_TYPE_C) {
		this.BD_TYPE_C = BD_TYPE_C;
	}

	public Short getLAA_APP_LOANDTL_TERM_N() {
		return this.LAA_APP_LOANDTL_TERM_N;
	}

	public void setLAA_APP_LOANDTL_TERM_N(Short LAA_APP_LOANDTL_TERM_N) {
		this.LAA_APP_LOANDTL_TERM_N = LAA_APP_LOANDTL_TERM_N;
	}

	public String getLAA_QUOTE_FLAG_C() {
		return this.LAA_QUOTE_FLAG_C;
	}

	public void setLAA_QUOTE_FLAG_C(String LAA_QUOTE_FLAG_C) {
		this.LAA_QUOTE_FLAG_C = LAA_QUOTE_FLAG_C;
	}

	public String getLAA_TOPUP_FLAG() {
		return this.LAA_TOPUP_FLAG;
	}

	public void setLAA_TOPUP_FLAG(String LAA_TOPUP_FLAG) {
		this.LAA_TOPUP_FLAG = LAA_TOPUP_FLAG;
	}

	public Set getLOS_APP_STATUSs() {
		return this.LOS_APP_STATUSs;
	}

	public void setLOS_APP_STATUSs(Set LOS_APP_STATUSs) {
		this.LOS_APP_STATUSs = LOS_APP_STATUSs;
	}

}
