package com.pruvn.tools.common.hibernate.finnone.cas;

// Generated May 31, 2011 2:37:34 PM by Hibernate Tools 3.2.4.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NBFC_STATE_M generated by hbm2java
 */
public class NBFC_STATE_M implements java.io.Serializable {

	private int STATEID;
	private String STATEDESC;
	private Integer COUNTRYID;
	private String MC_STATUS;
	private String MAKERID;
	private Date MAKEDATE;
	private String AUTHID;
	private Date AUTHDATE;
	private String GEOGRAPHIC_LOC_CD;
	private String LMT_TIMEZONE_ID_C;
	private Set LOS_APP_APPLICATIONSs = new HashSet(0);

	public NBFC_STATE_M() {
	}

	public NBFC_STATE_M(int STATEID, Date AUTHDATE) {
		this.STATEID = STATEID;
		this.AUTHDATE = AUTHDATE;
	}

	public NBFC_STATE_M(int STATEID, String STATEDESC, Integer COUNTRYID,
			String MC_STATUS, String MAKERID, Date MAKEDATE, String AUTHID,
			Date AUTHDATE, String GEOGRAPHIC_LOC_CD, String LMT_TIMEZONE_ID_C,
			Set LOS_APP_APPLICATIONSs) {
		this.STATEID = STATEID;
		this.STATEDESC = STATEDESC;
		this.COUNTRYID = COUNTRYID;
		this.MC_STATUS = MC_STATUS;
		this.MAKERID = MAKERID;
		this.MAKEDATE = MAKEDATE;
		this.AUTHID = AUTHID;
		this.AUTHDATE = AUTHDATE;
		this.GEOGRAPHIC_LOC_CD = GEOGRAPHIC_LOC_CD;
		this.LMT_TIMEZONE_ID_C = LMT_TIMEZONE_ID_C;
		this.LOS_APP_APPLICATIONSs = LOS_APP_APPLICATIONSs;
	}

	public int getSTATEID() {
		return this.STATEID;
	}

	public void setSTATEID(int STATEID) {
		this.STATEID = STATEID;
	}

	public String getSTATEDESC() {
		return this.STATEDESC;
	}

	public void setSTATEDESC(String STATEDESC) {
		this.STATEDESC = STATEDESC;
	}

	public Integer getCOUNTRYID() {
		return this.COUNTRYID;
	}

	public void setCOUNTRYID(Integer COUNTRYID) {
		this.COUNTRYID = COUNTRYID;
	}

	public String getMC_STATUS() {
		return this.MC_STATUS;
	}

	public void setMC_STATUS(String MC_STATUS) {
		this.MC_STATUS = MC_STATUS;
	}

	public String getMAKERID() {
		return this.MAKERID;
	}

	public void setMAKERID(String MAKERID) {
		this.MAKERID = MAKERID;
	}

	public Date getMAKEDATE() {
		return this.MAKEDATE;
	}

	public void setMAKEDATE(Date MAKEDATE) {
		this.MAKEDATE = MAKEDATE;
	}

	public String getAUTHID() {
		return this.AUTHID;
	}

	public void setAUTHID(String AUTHID) {
		this.AUTHID = AUTHID;
	}

	public Date getAUTHDATE() {
		return this.AUTHDATE;
	}

	public void setAUTHDATE(Date AUTHDATE) {
		this.AUTHDATE = AUTHDATE;
	}

	public String getGEOGRAPHIC_LOC_CD() {
		return this.GEOGRAPHIC_LOC_CD;
	}

	public void setGEOGRAPHIC_LOC_CD(String GEOGRAPHIC_LOC_CD) {
		this.GEOGRAPHIC_LOC_CD = GEOGRAPHIC_LOC_CD;
	}

	public String getLMT_TIMEZONE_ID_C() {
		return this.LMT_TIMEZONE_ID_C;
	}

	public void setLMT_TIMEZONE_ID_C(String LMT_TIMEZONE_ID_C) {
		this.LMT_TIMEZONE_ID_C = LMT_TIMEZONE_ID_C;
	}

	public Set getLOS_APP_APPLICATIONSs() {
		return this.LOS_APP_APPLICATIONSs;
	}

	public void setLOS_APP_APPLICATIONSs(Set LOS_APP_APPLICATIONSs) {
		this.LOS_APP_APPLICATIONSs = LOS_APP_APPLICATIONSs;
	}

}
