package com.pruvn.tools.common.hibernate.finnone.cas;

// Generated May 31, 2011 2:37:34 PM by Hibernate Tools 3.2.4.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NBFC_PRODUCT_M generated by hbm2java
 */
public class NBFC_PRODUCT_M implements java.io.Serializable {

	private String CODE;
	private String DESCRIPTION;
	private BigDecimal GRACE_AMT;
	private Byte GRACE_DAYS;
	private String MC_STATUS;
	private String MAKERID;
	private Date MAKERDATE;
	private String AUTHID;
	private Date AUTHDATE;
	private Date DATELASTUPDT;
	private BigDecimal IIR;
	private String RETAIL_CORP;
	private String LOANTYPE;
	private String LOAN_NORMS;
	private String COLLATERALS;
	private String EXPOSURE_TRACK_CUST;
	private String EXPOSURE_TRACK_DSA;
	private String ASSET_BASED;
	private String GROUP_LEVEL;
	private String BRANCH_LEVEL;
	private BigDecimal EXPOSURE_LIMIT;
	private BigDecimal CURRENT_EXPOSURE;
	private String PRODUCTTYPE;
	private String BALANCE_TRANSFER;
	private String CO_APPL_REQ;
	private String GUARANTOR_REQ;
	private String SEC_DEPOSIT_REQ;
	private String FORECLOSE_ALLOWED;
	private Short FORECLOSE_LOCK_PERIOD;
	private String RELATIONSHIP_DISC;
	private String PROFESSIONAL_DISC;
	private String PREPAY_ALLOWED;
	private String PREPAY_PENALTY;
	private Short PREPAY_LOCK_PERIOD;
	private String FORECLOSURE_PENALTY;
	private String INSURANCE_FLAG;
	private Character RESET;
	private Date START_DT;
	private Date END_DT;
	private String ENABLED_FLAG;
	private String PRODUCT_TYPE_CD;
	private String COLLATERAL_CD;
	private Short NO_OF_EMI;
	private String COMMON_COA;
	private String NPM_LPP_PRODCAT_C;
	private String NPM_LWW_WORKFLOW_ID_C;
	private String NPM_LFFM_FORM_ID_C;
	private String NPM_POLICY_FLAG_C;
	private String ELIGIBILITY_FLAG_C;
	private String EQUIVALENT_CODE;
	private String RC_COLLECTION_FLAG;
	private String LOGO;
	private String LOB_CODE;
	private Set LOS_APP_APPLICATIONSs = new HashSet(0);

	public NBFC_PRODUCT_M() {
	}

	public NBFC_PRODUCT_M(String CODE, String ASSET_BASED) {
		this.CODE = CODE;
		this.ASSET_BASED = ASSET_BASED;
	}

	public NBFC_PRODUCT_M(String CODE, String DESCRIPTION,
			BigDecimal GRACE_AMT, Byte GRACE_DAYS, String MC_STATUS,
			String MAKERID, Date MAKERDATE, String AUTHID, Date AUTHDATE,
			Date DATELASTUPDT, BigDecimal IIR, String RETAIL_CORP,
			String LOANTYPE, String LOAN_NORMS, String COLLATERALS,
			String EXPOSURE_TRACK_CUST, String EXPOSURE_TRACK_DSA,
			String ASSET_BASED, String GROUP_LEVEL, String BRANCH_LEVEL,
			BigDecimal EXPOSURE_LIMIT, BigDecimal CURRENT_EXPOSURE,
			String PRODUCTTYPE, String BALANCE_TRANSFER, String CO_APPL_REQ,
			String GUARANTOR_REQ, String SEC_DEPOSIT_REQ,
			String FORECLOSE_ALLOWED, Short FORECLOSE_LOCK_PERIOD,
			String RELATIONSHIP_DISC, String PROFESSIONAL_DISC,
			String PREPAY_ALLOWED, String PREPAY_PENALTY,
			Short PREPAY_LOCK_PERIOD, String FORECLOSURE_PENALTY,
			String INSURANCE_FLAG, Character RESET, Date START_DT, Date END_DT,
			String ENABLED_FLAG, String PRODUCT_TYPE_CD, String COLLATERAL_CD,
			Short NO_OF_EMI, String COMMON_COA, String NPM_LPP_PRODCAT_C,
			String NPM_LWW_WORKFLOW_ID_C, String NPM_LFFM_FORM_ID_C,
			String NPM_POLICY_FLAG_C, String ELIGIBILITY_FLAG_C,
			String EQUIVALENT_CODE, String RC_COLLECTION_FLAG, String LOGO,
			String LOB_CODE, Set LOS_APP_APPLICATIONSs) {
		this.CODE = CODE;
		this.DESCRIPTION = DESCRIPTION;
		this.GRACE_AMT = GRACE_AMT;
		this.GRACE_DAYS = GRACE_DAYS;
		this.MC_STATUS = MC_STATUS;
		this.MAKERID = MAKERID;
		this.MAKERDATE = MAKERDATE;
		this.AUTHID = AUTHID;
		this.AUTHDATE = AUTHDATE;
		this.DATELASTUPDT = DATELASTUPDT;
		this.IIR = IIR;
		this.RETAIL_CORP = RETAIL_CORP;
		this.LOANTYPE = LOANTYPE;
		this.LOAN_NORMS = LOAN_NORMS;
		this.COLLATERALS = COLLATERALS;
		this.EXPOSURE_TRACK_CUST = EXPOSURE_TRACK_CUST;
		this.EXPOSURE_TRACK_DSA = EXPOSURE_TRACK_DSA;
		this.ASSET_BASED = ASSET_BASED;
		this.GROUP_LEVEL = GROUP_LEVEL;
		this.BRANCH_LEVEL = BRANCH_LEVEL;
		this.EXPOSURE_LIMIT = EXPOSURE_LIMIT;
		this.CURRENT_EXPOSURE = CURRENT_EXPOSURE;
		this.PRODUCTTYPE = PRODUCTTYPE;
		this.BALANCE_TRANSFER = BALANCE_TRANSFER;
		this.CO_APPL_REQ = CO_APPL_REQ;
		this.GUARANTOR_REQ = GUARANTOR_REQ;
		this.SEC_DEPOSIT_REQ = SEC_DEPOSIT_REQ;
		this.FORECLOSE_ALLOWED = FORECLOSE_ALLOWED;
		this.FORECLOSE_LOCK_PERIOD = FORECLOSE_LOCK_PERIOD;
		this.RELATIONSHIP_DISC = RELATIONSHIP_DISC;
		this.PROFESSIONAL_DISC = PROFESSIONAL_DISC;
		this.PREPAY_ALLOWED = PREPAY_ALLOWED;
		this.PREPAY_PENALTY = PREPAY_PENALTY;
		this.PREPAY_LOCK_PERIOD = PREPAY_LOCK_PERIOD;
		this.FORECLOSURE_PENALTY = FORECLOSURE_PENALTY;
		this.INSURANCE_FLAG = INSURANCE_FLAG;
		this.RESET = RESET;
		this.START_DT = START_DT;
		this.END_DT = END_DT;
		this.ENABLED_FLAG = ENABLED_FLAG;
		this.PRODUCT_TYPE_CD = PRODUCT_TYPE_CD;
		this.COLLATERAL_CD = COLLATERAL_CD;
		this.NO_OF_EMI = NO_OF_EMI;
		this.COMMON_COA = COMMON_COA;
		this.NPM_LPP_PRODCAT_C = NPM_LPP_PRODCAT_C;
		this.NPM_LWW_WORKFLOW_ID_C = NPM_LWW_WORKFLOW_ID_C;
		this.NPM_LFFM_FORM_ID_C = NPM_LFFM_FORM_ID_C;
		this.NPM_POLICY_FLAG_C = NPM_POLICY_FLAG_C;
		this.ELIGIBILITY_FLAG_C = ELIGIBILITY_FLAG_C;
		this.EQUIVALENT_CODE = EQUIVALENT_CODE;
		this.RC_COLLECTION_FLAG = RC_COLLECTION_FLAG;
		this.LOGO = LOGO;
		this.LOB_CODE = LOB_CODE;
		this.LOS_APP_APPLICATIONSs = LOS_APP_APPLICATIONSs;
	}

	public String getCODE() {
		return this.CODE;
	}

	public void setCODE(String CODE) {
		this.CODE = CODE;
	}

	public String getDESCRIPTION() {
		return this.DESCRIPTION;
	}

	public void setDESCRIPTION(String DESCRIPTION) {
		this.DESCRIPTION = DESCRIPTION;
	}

	public BigDecimal getGRACE_AMT() {
		return this.GRACE_AMT;
	}

	public void setGRACE_AMT(BigDecimal GRACE_AMT) {
		this.GRACE_AMT = GRACE_AMT;
	}

	public Byte getGRACE_DAYS() {
		return this.GRACE_DAYS;
	}

	public void setGRACE_DAYS(Byte GRACE_DAYS) {
		this.GRACE_DAYS = GRACE_DAYS;
	}

	public String getMC_STATUS() {
		return this.MC_STATUS;
	}

	public void setMC_STATUS(String MC_STATUS) {
		this.MC_STATUS = MC_STATUS;
	}

	public String getMAKERID() {
		return this.MAKERID;
	}

	public void setMAKERID(String MAKERID) {
		this.MAKERID = MAKERID;
	}

	public Date getMAKERDATE() {
		return this.MAKERDATE;
	}

	public void setMAKERDATE(Date MAKERDATE) {
		this.MAKERDATE = MAKERDATE;
	}

	public String getAUTHID() {
		return this.AUTHID;
	}

	public void setAUTHID(String AUTHID) {
		this.AUTHID = AUTHID;
	}

	public Date getAUTHDATE() {
		return this.AUTHDATE;
	}

	public void setAUTHDATE(Date AUTHDATE) {
		this.AUTHDATE = AUTHDATE;
	}

	public Date getDATELASTUPDT() {
		return this.DATELASTUPDT;
	}

	public void setDATELASTUPDT(Date DATELASTUPDT) {
		this.DATELASTUPDT = DATELASTUPDT;
	}

	public BigDecimal getIIR() {
		return this.IIR;
	}

	public void setIIR(BigDecimal IIR) {
		this.IIR = IIR;
	}

	public String getRETAIL_CORP() {
		return this.RETAIL_CORP;
	}

	public void setRETAIL_CORP(String RETAIL_CORP) {
		this.RETAIL_CORP = RETAIL_CORP;
	}

	public String getLOANTYPE() {
		return this.LOANTYPE;
	}

	public void setLOANTYPE(String LOANTYPE) {
		this.LOANTYPE = LOANTYPE;
	}

	public String getLOAN_NORMS() {
		return this.LOAN_NORMS;
	}

	public void setLOAN_NORMS(String LOAN_NORMS) {
		this.LOAN_NORMS = LOAN_NORMS;
	}

	public String getCOLLATERALS() {
		return this.COLLATERALS;
	}

	public void setCOLLATERALS(String COLLATERALS) {
		this.COLLATERALS = COLLATERALS;
	}

	public String getEXPOSURE_TRACK_CUST() {
		return this.EXPOSURE_TRACK_CUST;
	}

	public void setEXPOSURE_TRACK_CUST(String EXPOSURE_TRACK_CUST) {
		this.EXPOSURE_TRACK_CUST = EXPOSURE_TRACK_CUST;
	}

	public String getEXPOSURE_TRACK_DSA() {
		return this.EXPOSURE_TRACK_DSA;
	}

	public void setEXPOSURE_TRACK_DSA(String EXPOSURE_TRACK_DSA) {
		this.EXPOSURE_TRACK_DSA = EXPOSURE_TRACK_DSA;
	}

	public String getASSET_BASED() {
		return this.ASSET_BASED;
	}

	public void setASSET_BASED(String ASSET_BASED) {
		this.ASSET_BASED = ASSET_BASED;
	}

	public String getGROUP_LEVEL() {
		return this.GROUP_LEVEL;
	}

	public void setGROUP_LEVEL(String GROUP_LEVEL) {
		this.GROUP_LEVEL = GROUP_LEVEL;
	}

	public String getBRANCH_LEVEL() {
		return this.BRANCH_LEVEL;
	}

	public void setBRANCH_LEVEL(String BRANCH_LEVEL) {
		this.BRANCH_LEVEL = BRANCH_LEVEL;
	}

	public BigDecimal getEXPOSURE_LIMIT() {
		return this.EXPOSURE_LIMIT;
	}

	public void setEXPOSURE_LIMIT(BigDecimal EXPOSURE_LIMIT) {
		this.EXPOSURE_LIMIT = EXPOSURE_LIMIT;
	}

	public BigDecimal getCURRENT_EXPOSURE() {
		return this.CURRENT_EXPOSURE;
	}

	public void setCURRENT_EXPOSURE(BigDecimal CURRENT_EXPOSURE) {
		this.CURRENT_EXPOSURE = CURRENT_EXPOSURE;
	}

	public String getPRODUCTTYPE() {
		return this.PRODUCTTYPE;
	}

	public void setPRODUCTTYPE(String PRODUCTTYPE) {
		this.PRODUCTTYPE = PRODUCTTYPE;
	}

	public String getBALANCE_TRANSFER() {
		return this.BALANCE_TRANSFER;
	}

	public void setBALANCE_TRANSFER(String BALANCE_TRANSFER) {
		this.BALANCE_TRANSFER = BALANCE_TRANSFER;
	}

	public String getCO_APPL_REQ() {
		return this.CO_APPL_REQ;
	}

	public void setCO_APPL_REQ(String CO_APPL_REQ) {
		this.CO_APPL_REQ = CO_APPL_REQ;
	}

	public String getGUARANTOR_REQ() {
		return this.GUARANTOR_REQ;
	}

	public void setGUARANTOR_REQ(String GUARANTOR_REQ) {
		this.GUARANTOR_REQ = GUARANTOR_REQ;
	}

	public String getSEC_DEPOSIT_REQ() {
		return this.SEC_DEPOSIT_REQ;
	}

	public void setSEC_DEPOSIT_REQ(String SEC_DEPOSIT_REQ) {
		this.SEC_DEPOSIT_REQ = SEC_DEPOSIT_REQ;
	}

	public String getFORECLOSE_ALLOWED() {
		return this.FORECLOSE_ALLOWED;
	}

	public void setFORECLOSE_ALLOWED(String FORECLOSE_ALLOWED) {
		this.FORECLOSE_ALLOWED = FORECLOSE_ALLOWED;
	}

	public Short getFORECLOSE_LOCK_PERIOD() {
		return this.FORECLOSE_LOCK_PERIOD;
	}

	public void setFORECLOSE_LOCK_PERIOD(Short FORECLOSE_LOCK_PERIOD) {
		this.FORECLOSE_LOCK_PERIOD = FORECLOSE_LOCK_PERIOD;
	}

	public String getRELATIONSHIP_DISC() {
		return this.RELATIONSHIP_DISC;
	}

	public void setRELATIONSHIP_DISC(String RELATIONSHIP_DISC) {
		this.RELATIONSHIP_DISC = RELATIONSHIP_DISC;
	}

	public String getPROFESSIONAL_DISC() {
		return this.PROFESSIONAL_DISC;
	}

	public void setPROFESSIONAL_DISC(String PROFESSIONAL_DISC) {
		this.PROFESSIONAL_DISC = PROFESSIONAL_DISC;
	}

	public String getPREPAY_ALLOWED() {
		return this.PREPAY_ALLOWED;
	}

	public void setPREPAY_ALLOWED(String PREPAY_ALLOWED) {
		this.PREPAY_ALLOWED = PREPAY_ALLOWED;
	}

	public String getPREPAY_PENALTY() {
		return this.PREPAY_PENALTY;
	}

	public void setPREPAY_PENALTY(String PREPAY_PENALTY) {
		this.PREPAY_PENALTY = PREPAY_PENALTY;
	}

	public Short getPREPAY_LOCK_PERIOD() {
		return this.PREPAY_LOCK_PERIOD;
	}

	public void setPREPAY_LOCK_PERIOD(Short PREPAY_LOCK_PERIOD) {
		this.PREPAY_LOCK_PERIOD = PREPAY_LOCK_PERIOD;
	}

	public String getFORECLOSURE_PENALTY() {
		return this.FORECLOSURE_PENALTY;
	}

	public void setFORECLOSURE_PENALTY(String FORECLOSURE_PENALTY) {
		this.FORECLOSURE_PENALTY = FORECLOSURE_PENALTY;
	}

	public String getINSURANCE_FLAG() {
		return this.INSURANCE_FLAG;
	}

	public void setINSURANCE_FLAG(String INSURANCE_FLAG) {
		this.INSURANCE_FLAG = INSURANCE_FLAG;
	}

	public Character getRESET() {
		return this.RESET;
	}

	public void setRESET(Character RESET) {
		this.RESET = RESET;
	}

	public Date getSTART_DT() {
		return this.START_DT;
	}

	public void setSTART_DT(Date START_DT) {
		this.START_DT = START_DT;
	}

	public Date getEND_DT() {
		return this.END_DT;
	}

	public void setEND_DT(Date END_DT) {
		this.END_DT = END_DT;
	}

	public String getENABLED_FLAG() {
		return this.ENABLED_FLAG;
	}

	public void setENABLED_FLAG(String ENABLED_FLAG) {
		this.ENABLED_FLAG = ENABLED_FLAG;
	}

	public String getPRODUCT_TYPE_CD() {
		return this.PRODUCT_TYPE_CD;
	}

	public void setPRODUCT_TYPE_CD(String PRODUCT_TYPE_CD) {
		this.PRODUCT_TYPE_CD = PRODUCT_TYPE_CD;
	}

	public String getCOLLATERAL_CD() {
		return this.COLLATERAL_CD;
	}

	public void setCOLLATERAL_CD(String COLLATERAL_CD) {
		this.COLLATERAL_CD = COLLATERAL_CD;
	}

	public Short getNO_OF_EMI() {
		return this.NO_OF_EMI;
	}

	public void setNO_OF_EMI(Short NO_OF_EMI) {
		this.NO_OF_EMI = NO_OF_EMI;
	}

	public String getCOMMON_COA() {
		return this.COMMON_COA;
	}

	public void setCOMMON_COA(String COMMON_COA) {
		this.COMMON_COA = COMMON_COA;
	}

	public String getNPM_LPP_PRODCAT_C() {
		return this.NPM_LPP_PRODCAT_C;
	}

	public void setNPM_LPP_PRODCAT_C(String NPM_LPP_PRODCAT_C) {
		this.NPM_LPP_PRODCAT_C = NPM_LPP_PRODCAT_C;
	}

	public String getNPM_LWW_WORKFLOW_ID_C() {
		return this.NPM_LWW_WORKFLOW_ID_C;
	}

	public void setNPM_LWW_WORKFLOW_ID_C(String NPM_LWW_WORKFLOW_ID_C) {
		this.NPM_LWW_WORKFLOW_ID_C = NPM_LWW_WORKFLOW_ID_C;
	}

	public String getNPM_LFFM_FORM_ID_C() {
		return this.NPM_LFFM_FORM_ID_C;
	}

	public void setNPM_LFFM_FORM_ID_C(String NPM_LFFM_FORM_ID_C) {
		this.NPM_LFFM_FORM_ID_C = NPM_LFFM_FORM_ID_C;
	}

	public String getNPM_POLICY_FLAG_C() {
		return this.NPM_POLICY_FLAG_C;
	}

	public void setNPM_POLICY_FLAG_C(String NPM_POLICY_FLAG_C) {
		this.NPM_POLICY_FLAG_C = NPM_POLICY_FLAG_C;
	}

	public String getELIGIBILITY_FLAG_C() {
		return this.ELIGIBILITY_FLAG_C;
	}

	public void setELIGIBILITY_FLAG_C(String ELIGIBILITY_FLAG_C) {
		this.ELIGIBILITY_FLAG_C = ELIGIBILITY_FLAG_C;
	}

	public String getEQUIVALENT_CODE() {
		return this.EQUIVALENT_CODE;
	}

	public void setEQUIVALENT_CODE(String EQUIVALENT_CODE) {
		this.EQUIVALENT_CODE = EQUIVALENT_CODE;
	}

	public String getRC_COLLECTION_FLAG() {
		return this.RC_COLLECTION_FLAG;
	}

	public void setRC_COLLECTION_FLAG(String RC_COLLECTION_FLAG) {
		this.RC_COLLECTION_FLAG = RC_COLLECTION_FLAG;
	}

	public String getLOGO() {
		return this.LOGO;
	}

	public void setLOGO(String LOGO) {
		this.LOGO = LOGO;
	}

	public String getLOB_CODE() {
		return this.LOB_CODE;
	}

	public void setLOB_CODE(String LOB_CODE) {
		this.LOB_CODE = LOB_CODE;
	}

	public Set getLOS_APP_APPLICATIONSs() {
		return this.LOS_APP_APPLICATIONSs;
	}

	public void setLOS_APP_APPLICATIONSs(Set LOS_APP_APPLICATIONSs) {
		this.LOS_APP_APPLICATIONSs = LOS_APP_APPLICATIONSs;
	}

}
